# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

output: prefixed

includes:
  site:
    taskfile: ./site/Taskfile.yml
    dir: ./site
  spa:
    taskfile: ./spa/Taskfile.yml
    dir: ./spa
  docs:
    taskfile: ./docs/Taskfile.yml
    dir: ./docs

tasks:
  gen:oapi:main:
    dir: ./cmd/server/oapi
    preconditions:
      - redocly bundle ../../../api/openapi.yaml -o ./bundle.openapi.yaml
    cmds:
      - go tool oapi-codegen -config ./oapi.cfg.yaml ./bundle.openapi.yaml
      - rm ./bundle.openapi.yaml

  gen:oapi:
    cmds:
      - task: gen:oapi:main

  gen:db:
    cmds:
      - sqlc generate
      - goose up
      - jet -source=sqlite -dsn=./database/tunkunia.db -path=./database/jet

  gen:all:
    cmds:
      - task: gen:oapi:main
      - task: gen:oapi:catalog
      - task: gen:db

  oapi:join:
    desc: Joins multiple openapi specs into one
    cmds:
      - >
        watchexec
        -w ./internal/catalog/api
        redocly join
        ./api/openapi.yaml
        ./internal/catalog/api/openapi.yaml
        -o ./api/joined.openapi.yaml
        --without-x-tag-groups

  scalar:serve:
    desc: Serves a scalar api reference
    preconditions:
      - test -f ./api/joined.openapi.yaml
    cmds:
      - scalar document serve --watch --port 8491 ./api/joined.openapi.yaml

  server:dev:
    desc: Run server with hot reload (air)
    cmds:
      - air

  server:build:
    desc: Build server binary
    cmds:
      - go build -o bin/server ./cmd/api

  dev:all:
    desc: Run all dev servers in parallel
    deps:
      - oapi:join
      - scalar:serve
      - server:dev
      - site:dev
      - spa:dev
    cmds:
      - echo ""

  build:all:
    desc: Build all projects
    cmds:
      - task: server:build
      - task: site:build
      - task: spa:build

  docs:all:
    desc: Generate all documentation
    cmds:
      - task: docs:typstout
      - task: docs:plantuml
