# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv:
  - ".env"

output: prefixed

includes:
  site:
    taskfile: ./site/Taskfile.yml
    dir: ./site
  spa:
    taskfile: ./spa/Taskfile.yml
    dir: ./spa
  docs:
    taskfile: ./docs/Taskfile.yml
    dir: ./docs

tasks:
  migrate:fresh:
    cmds:
      - echo "Using $GOOSE_DBSTRING"
      - rm -f $GOOSE_DBSTRING
      - go tool goose up

  openapi:bundle:
    desc: Joins multiple openapi specs into one
    cmds:
      - >
        watchexec
        -w ./internal/api/v1
        redocly bundle
        ./internal/api/v1/openapi.yaml
        -o ./v1.openapi.yaml

  gen:heyapi:
    desc: Genera cliente de api
    dir: ./spa
    cmds:
      - pnpm openapi-ts

  dex:serve:
    desc: Start local Dex OIDC sandbox server
    preconditions:
      - test -f ./bin/dex
    cmds:
      - ./bin/dex serve ./dex/config.tunkunia.yaml

  scalar:serve:
    desc: Serves a scalar api reference
    preconditions:
      - test -f ./v1.openapi.yaml
    cmds:
      - pnpm dlx @scalar/cli document serve --watch --port 8491 ./v1.openapi.yaml
    failfast: true

  scalar:dev:
    prefix: scalar
    deps:
      - openapi:bundle
      - scalar:serve
    failfast: true

  server:dev:
    prefix: GO
    desc: Run server with hot reload (air)
    cmds:
      - go tool air serve

  server:build:
    desc: Build server binary
    cmds:
      - go build -o bin/server ./cmd/api

  dev:tools:
    desc: Run dev tooling servers
    deps:
      - dex:serve
      - scalar:dev

  dev:main:
    desc: Run project dev servers
    deps:
      - server:dev
      - spa:dev

  dev:all:
    desc: Run all dev servers in parallel
    deps:
      - dex:serve
      - scalar:serve
      - server:dev
      - spa:dev
    cmds:
      - echo ""

  build:all:
    desc: Build all projects
    cmds:
      - task: server:build
      - task: site:build
      - task: spa:build

  docs:all:
    desc: Generate all documentation
    cmds:
      - task: docs:typstout
      - task: docs:plantuml
