openapi: "3.0.3"
info:
  title: CatalogModuleAPI
  version: "1.0"
paths:
  /health:
    get:
      operationId: GetHealth
      tags:
        - health
      summary: Salud Módulo
      security: []
      responses:
        "200":
          description: The service is healthy and operating normally
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Health"
        "503":
          description: The service is unhealthy or degraded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Health"
        "404":
          $ref: openapi.yaml#/components/responses/NotFound
components:
  schemas:
    Health:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          enum:
            - UP
            - DOWN
            - DEGRADED
        timestamp:
          type: string
          format: date-time
          example: "2026-06-06T15:30:00Z"
