openapi: "3.0.3"
info:
  title: Tunkunia API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: "1.0"
  description: |
    Interfaz de interacción con el subsistema de gestión de flujos de trámite Tunkunia.
    Esta especificación se usará para consumo de los distintos tipos de clientes.
    Para lograr uniformidad se siguen prácticas de la industria y estándares vigentes:
      - [RFC 9457](https://datatracker.ietf.org/doc/html/rfc9457)
      - [Documentación](https://docs.stripe.com/api-v2-overview) y [Referencia](https://docs.stripe.com/api/v2/core/accounts) de la API de Stripe v2
      - Guías de diseño de APIs de [Google](https://docs.cloud.google.com/apis/design) y de [Microsoft](https://github.com/microsoft/api-guidelines) (Azure y Legacy)

servers:
  - url: /api/v1
    description: Same origin as the API reference
paths:
  /health:
    $ref: health.openapi.yaml#/paths/~1health
  /tramites:
    $ref: tramites.openapi.yaml#/paths/~1tramites
  /tramites/{id}:
    $ref: tramites.openapi.yaml#/paths/~1tramites~1{id}
  /me:
    $ref: users.openapi.yaml#/paths/~1me

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Enter your application JWT token
  schemas:
    CollectionBase:
      type: object
      required:
        - next_page_url
        - previous_page_url
      properties:
        next_page_url:
          type: string
          nullable: true
          example: "https://api.example.com/users?page=3"
        previous_page_url:
          type: string
          nullable: true
          example: "https://api.example.com/users?page=1"

    ProblemDetails:
      type: object
      description: >
        Objeto de Detalles de Problema según RFC 9457.
        Se serializa con el tipo de medio "application/problem+json".
        Todos los miembros son OPCIONALES; los miembros ausentes no tienen
        valor por defecto salvo donde se indique explícitamente.
        Pueden estar presentes miembros adicionales (de extensión); los consumidores
        DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
      required: [title, status, detail]
      properties:
        type:
          type: string
          format: uri-reference
          default: "about:blank"
          description: >
            Referencia URI (RFC 3986) que identifica el tipo de problema.
            Al ser desreferenciada (si es una URI http/https), DEBERÍA ofrecer
            documentación legible por humanos sobre el tipo de problema.
            Si está ausente, se asume el valor "about:blank", que remite al
            código de estado HTTP como único identificador del tipo de problema.
            En el caso de Tunkunia se usan rutas relativas a modo de identificador
            y eventual creación de sitio de documentación de problemas específicos
          example: "/problems/invalid-citizen"
        status:
          type: integer
          format: int32
          minimum: 400
          maximum: 599
          description: >
            Código de estado HTTP generado por el servidor de origen para esta
            ocurrencia del problema. Se incluye por conveniencia; DEBE coincidir
            con el código de estado de la respuesta HTTP real.
          example: 403
        title:
          type: string
          description: >
            Contiene un resumen corto y legible por humanos del tipo de problema.
            Es de carácter consultivo y se incluye únicamente para los usuarios que no conocen y no pueden descubrir la semántica del URI del campo "type".
          example: "Usted no es participante de este caso de trámite."
        detail:
          type: string
          description: >
            Contiene una explicación legible para humanos, específica de esta ocurrencia del problema.
            Si está presente, debería centrarse en ayudar al cliente a corregir el problema, en lugar de proporcionar información de depuración.
            Los consumidores NO DEBERÍAN analizar (parsear) el miembro "detail" para obtener información; las extensiones son una forma más adecuada y menos propensa a errores de obtener dicha información.
          example: "Su caso de trámite con código 500424 no se encuentra vigente"
        instance:
          type: string
          format: uri-reference
          description: >
            Referencia URI que identifica la ocurrencia específica del problema.
            Cuando es desreferenciable, el objeto de detalles de problema PUEDE
            obtenerse desde ella. Puede ser relativa o absoluta.
            No suele incluirse en la API de Tunkunia y se conserva en el esquema para obedecer el RFC 9457
          example: "/cuenta/12345/mensajes/abc"
    ErrorDetail:
      type: object
      description: El formato se adecúa al ejemplo brindado en la sección 3 del RFC 9457
      required:
        - detail
        - pointer
      properties:
        detail:
          type: string
        pointer:
          type: string
  responses:
    BadRequest:
      description: Solicitud no aceptada o entendida. Quizá falte algún parámetro requerido.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"

    Unauthorized:
      description: No se ha provisto con una llave válida.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"

    Forbidden:
      description: No tiene permisos para realizar esta solicitud
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"

    NotFound:
      description: El recurso solicitado no existe
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"

    ValidationError:
      description: Los datos provistos son incorrectos
      content:
        application/problem+json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ProblemDetails"
              - type: object
                required: [errors]
                properties:
                  errors:
                    description: >
                      Lista de errores de validación identificados. El formato
                      se adecúa al ejemplo brindado en la sección 3 del RFC 9457
                    type: array
                    items:
                      $ref: "#/components/schemas/ErrorDetail"

    InternalError:
      description: No se pudo ejecutar la solicitud
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
