//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Cases = newCasesTable("", "cases", "")

type casesTable struct {
	sqlite.Table

	// Columns
	ID                 sqlite.ColumnInteger
	TramiteID          sqlite.ColumnInteger
	ProcedureVersionID sqlite.ColumnInteger
	Status             sqlite.ColumnString
	Revision           sqlite.ColumnInteger
	Marking            sqlite.ColumnString
	InitiatedBy        sqlite.ColumnInteger
	StartedAt          sqlite.ColumnString
	UpdatedAt          sqlite.ColumnString
	CompletedAt        sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type CasesTable struct {
	casesTable

	EXCLUDED casesTable
}

// AS creates new CasesTable with assigned alias
func (a CasesTable) AS(alias string) *CasesTable {
	return newCasesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CasesTable with assigned schema name
func (a CasesTable) FromSchema(schemaName string) *CasesTable {
	return newCasesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CasesTable with assigned table prefix
func (a CasesTable) WithPrefix(prefix string) *CasesTable {
	return newCasesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CasesTable with assigned table suffix
func (a CasesTable) WithSuffix(suffix string) *CasesTable {
	return newCasesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCasesTable(schemaName, tableName, alias string) *CasesTable {
	return &CasesTable{
		casesTable: newCasesTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newCasesTableImpl("", "excluded", ""),
	}
}

func newCasesTableImpl(schemaName, tableName, alias string) casesTable {
	var (
		IDColumn                 = sqlite.IntegerColumn("id")
		TramiteIDColumn          = sqlite.IntegerColumn("tramite_id")
		ProcedureVersionIDColumn = sqlite.IntegerColumn("procedure_version_id")
		StatusColumn             = sqlite.StringColumn("status")
		RevisionColumn           = sqlite.IntegerColumn("revision")
		MarkingColumn            = sqlite.StringColumn("marking")
		InitiatedByColumn        = sqlite.IntegerColumn("initiated_by")
		StartedAtColumn          = sqlite.StringColumn("started_at")
		UpdatedAtColumn          = sqlite.StringColumn("updated_at")
		CompletedAtColumn        = sqlite.StringColumn("completed_at")
		allColumns               = sqlite.ColumnList{IDColumn, TramiteIDColumn, ProcedureVersionIDColumn, StatusColumn, RevisionColumn, MarkingColumn, InitiatedByColumn, StartedAtColumn, UpdatedAtColumn, CompletedAtColumn}
		mutableColumns           = sqlite.ColumnList{TramiteIDColumn, ProcedureVersionIDColumn, StatusColumn, RevisionColumn, MarkingColumn, InitiatedByColumn, StartedAtColumn, UpdatedAtColumn, CompletedAtColumn}
		defaultColumns           = sqlite.ColumnList{StatusColumn, RevisionColumn, StartedAtColumn, UpdatedAtColumn}
	)

	return casesTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                 IDColumn,
		TramiteID:          TramiteIDColumn,
		ProcedureVersionID: ProcedureVersionIDColumn,
		Status:             StatusColumn,
		Revision:           RevisionColumn,
		Marking:            MarkingColumn,
		InitiatedBy:        InitiatedByColumn,
		StartedAt:          StartedAtColumn,
		UpdatedAt:          UpdatedAtColumn,
		CompletedAt:        CompletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
