//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var CaseTasks = newCaseTasksTable("", "case_tasks", "")

type caseTasksTable struct {
	sqlite.Table

	// Columns
	ID              sqlite.ColumnInteger
	CaseID          sqlite.ColumnInteger
	TransitionID    sqlite.ColumnString
	TransitionLabel sqlite.ColumnString
	Role            sqlite.ColumnString
	AssigneeID      sqlite.ColumnInteger
	Status          sqlite.ColumnString
	CreatedAt       sqlite.ColumnString
	FinishedAt      sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type CaseTasksTable struct {
	caseTasksTable

	EXCLUDED caseTasksTable
}

// AS creates new CaseTasksTable with assigned alias
func (a CaseTasksTable) AS(alias string) *CaseTasksTable {
	return newCaseTasksTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CaseTasksTable with assigned schema name
func (a CaseTasksTable) FromSchema(schemaName string) *CaseTasksTable {
	return newCaseTasksTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CaseTasksTable with assigned table prefix
func (a CaseTasksTable) WithPrefix(prefix string) *CaseTasksTable {
	return newCaseTasksTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CaseTasksTable with assigned table suffix
func (a CaseTasksTable) WithSuffix(suffix string) *CaseTasksTable {
	return newCaseTasksTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCaseTasksTable(schemaName, tableName, alias string) *CaseTasksTable {
	return &CaseTasksTable{
		caseTasksTable: newCaseTasksTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newCaseTasksTableImpl("", "excluded", ""),
	}
}

func newCaseTasksTableImpl(schemaName, tableName, alias string) caseTasksTable {
	var (
		IDColumn              = sqlite.IntegerColumn("id")
		CaseIDColumn          = sqlite.IntegerColumn("case_id")
		TransitionIDColumn    = sqlite.StringColumn("transition_id")
		TransitionLabelColumn = sqlite.StringColumn("transition_label")
		RoleColumn            = sqlite.StringColumn("role")
		AssigneeIDColumn      = sqlite.IntegerColumn("assignee_id")
		StatusColumn          = sqlite.StringColumn("status")
		CreatedAtColumn       = sqlite.StringColumn("created_at")
		FinishedAtColumn      = sqlite.StringColumn("finished_at")
		allColumns            = sqlite.ColumnList{IDColumn, CaseIDColumn, TransitionIDColumn, TransitionLabelColumn, RoleColumn, AssigneeIDColumn, StatusColumn, CreatedAtColumn, FinishedAtColumn}
		mutableColumns        = sqlite.ColumnList{CaseIDColumn, TransitionIDColumn, TransitionLabelColumn, RoleColumn, AssigneeIDColumn, StatusColumn, CreatedAtColumn, FinishedAtColumn}
		defaultColumns        = sqlite.ColumnList{StatusColumn, CreatedAtColumn}
	)

	return caseTasksTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		CaseID:          CaseIDColumn,
		TransitionID:    TransitionIDColumn,
		TransitionLabel: TransitionLabelColumn,
		Role:            RoleColumn,
		AssigneeID:      AssigneeIDColumn,
		Status:          StatusColumn,
		CreatedAt:       CreatedAtColumn,
		FinishedAt:      FinishedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
