//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var CaseActions = newCaseActionsTable("", "case_actions", "")

type caseActionsTable struct {
	sqlite.Table

	// Columns
	ID              sqlite.ColumnInteger
	CaseID          sqlite.ColumnInteger
	TaskID          sqlite.ColumnInteger
	TransitionID    sqlite.ColumnString
	TransitionLabel sqlite.ColumnString
	ActorID         sqlite.ColumnInteger
	RevisionBefore  sqlite.ColumnInteger
	MarkingBefore   sqlite.ColumnString
	MarkingAfter    sqlite.ColumnString
	OccurredAt      sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type CaseActionsTable struct {
	caseActionsTable

	EXCLUDED caseActionsTable
}

// AS creates new CaseActionsTable with assigned alias
func (a CaseActionsTable) AS(alias string) *CaseActionsTable {
	return newCaseActionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CaseActionsTable with assigned schema name
func (a CaseActionsTable) FromSchema(schemaName string) *CaseActionsTable {
	return newCaseActionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CaseActionsTable with assigned table prefix
func (a CaseActionsTable) WithPrefix(prefix string) *CaseActionsTable {
	return newCaseActionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CaseActionsTable with assigned table suffix
func (a CaseActionsTable) WithSuffix(suffix string) *CaseActionsTable {
	return newCaseActionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCaseActionsTable(schemaName, tableName, alias string) *CaseActionsTable {
	return &CaseActionsTable{
		caseActionsTable: newCaseActionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newCaseActionsTableImpl("", "excluded", ""),
	}
}

func newCaseActionsTableImpl(schemaName, tableName, alias string) caseActionsTable {
	var (
		IDColumn              = sqlite.IntegerColumn("id")
		CaseIDColumn          = sqlite.IntegerColumn("case_id")
		TaskIDColumn          = sqlite.IntegerColumn("task_id")
		TransitionIDColumn    = sqlite.StringColumn("transition_id")
		TransitionLabelColumn = sqlite.StringColumn("transition_label")
		ActorIDColumn         = sqlite.IntegerColumn("actor_id")
		RevisionBeforeColumn  = sqlite.IntegerColumn("revision_before")
		MarkingBeforeColumn   = sqlite.StringColumn("marking_before")
		MarkingAfterColumn    = sqlite.StringColumn("marking_after")
		OccurredAtColumn      = sqlite.StringColumn("occurred_at")
		allColumns            = sqlite.ColumnList{IDColumn, CaseIDColumn, TaskIDColumn, TransitionIDColumn, TransitionLabelColumn, ActorIDColumn, RevisionBeforeColumn, MarkingBeforeColumn, MarkingAfterColumn, OccurredAtColumn}
		mutableColumns        = sqlite.ColumnList{CaseIDColumn, TaskIDColumn, TransitionIDColumn, TransitionLabelColumn, ActorIDColumn, RevisionBeforeColumn, MarkingBeforeColumn, MarkingAfterColumn, OccurredAtColumn}
		defaultColumns        = sqlite.ColumnList{OccurredAtColumn}
	)

	return caseActionsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		CaseID:          CaseIDColumn,
		TaskID:          TaskIDColumn,
		TransitionID:    TransitionIDColumn,
		TransitionLabel: TransitionLabelColumn,
		ActorID:         ActorIDColumn,
		RevisionBefore:  RevisionBeforeColumn,
		MarkingBefore:   MarkingBeforeColumn,
		MarkingAfter:    MarkingAfterColumn,
		OccurredAt:      OccurredAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
