//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Notifications = newNotificationsTable("", "notifications", "")

type notificationsTable struct {
	sqlite.Table

	// Columns
	ID        sqlite.ColumnInteger
	UserID    sqlite.ColumnInteger
	CaseID    sqlite.ColumnInteger
	TaskID    sqlite.ColumnInteger
	Type      sqlite.ColumnString
	Title     sqlite.ColumnString
	CreatedAt sqlite.ColumnString
	ReadAt    sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type NotificationsTable struct {
	notificationsTable

	EXCLUDED notificationsTable
}

// AS creates new NotificationsTable with assigned alias
func (a NotificationsTable) AS(alias string) *NotificationsTable {
	return newNotificationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new NotificationsTable with assigned schema name
func (a NotificationsTable) FromSchema(schemaName string) *NotificationsTable {
	return newNotificationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new NotificationsTable with assigned table prefix
func (a NotificationsTable) WithPrefix(prefix string) *NotificationsTable {
	return newNotificationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new NotificationsTable with assigned table suffix
func (a NotificationsTable) WithSuffix(suffix string) *NotificationsTable {
	return newNotificationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newNotificationsTable(schemaName, tableName, alias string) *NotificationsTable {
	return &NotificationsTable{
		notificationsTable: newNotificationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newNotificationsTableImpl("", "excluded", ""),
	}
}

func newNotificationsTableImpl(schemaName, tableName, alias string) notificationsTable {
	var (
		IDColumn        = sqlite.IntegerColumn("id")
		UserIDColumn    = sqlite.IntegerColumn("user_id")
		CaseIDColumn    = sqlite.IntegerColumn("case_id")
		TaskIDColumn    = sqlite.IntegerColumn("task_id")
		TypeColumn      = sqlite.StringColumn("type")
		TitleColumn     = sqlite.StringColumn("title")
		CreatedAtColumn = sqlite.StringColumn("created_at")
		ReadAtColumn    = sqlite.StringColumn("read_at")
		allColumns      = sqlite.ColumnList{IDColumn, UserIDColumn, CaseIDColumn, TaskIDColumn, TypeColumn, TitleColumn, CreatedAtColumn, ReadAtColumn}
		mutableColumns  = sqlite.ColumnList{UserIDColumn, CaseIDColumn, TaskIDColumn, TypeColumn, TitleColumn, CreatedAtColumn, ReadAtColumn}
		defaultColumns  = sqlite.ColumnList{CreatedAtColumn}
	)

	return notificationsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		UserID:    UserIDColumn,
		CaseID:    CaseIDColumn,
		TaskID:    TaskIDColumn,
		Type:      TypeColumn,
		Title:     TitleColumn,
		CreatedAt: CreatedAtColumn,
		ReadAt:    ReadAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
