//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Tramites = newTramitesTable("", "tramites", "")

type tramitesTable struct {
	sqlite.Table

	// Columns
	ID                   sqlite.ColumnInteger
	Name                 sqlite.ColumnString
	Description          sqlite.ColumnString
	ProcedureDescription sqlite.ColumnString
	Type                 sqlite.ColumnString
	Status               sqlite.ColumnString
	CreatedAt            sqlite.ColumnString
	UpdatedAt            sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type TramitesTable struct {
	tramitesTable

	EXCLUDED tramitesTable
}

// AS creates new TramitesTable with assigned alias
func (a TramitesTable) AS(alias string) *TramitesTable {
	return newTramitesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TramitesTable with assigned schema name
func (a TramitesTable) FromSchema(schemaName string) *TramitesTable {
	return newTramitesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TramitesTable with assigned table prefix
func (a TramitesTable) WithPrefix(prefix string) *TramitesTable {
	return newTramitesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TramitesTable with assigned table suffix
func (a TramitesTable) WithSuffix(suffix string) *TramitesTable {
	return newTramitesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTramitesTable(schemaName, tableName, alias string) *TramitesTable {
	return &TramitesTable{
		tramitesTable: newTramitesTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newTramitesTableImpl("", "excluded", ""),
	}
}

func newTramitesTableImpl(schemaName, tableName, alias string) tramitesTable {
	var (
		IDColumn                   = sqlite.IntegerColumn("id")
		NameColumn                 = sqlite.StringColumn("name")
		DescriptionColumn          = sqlite.StringColumn("description")
		ProcedureDescriptionColumn = sqlite.StringColumn("procedure_description")
		TypeColumn                 = sqlite.StringColumn("type")
		StatusColumn               = sqlite.StringColumn("status")
		CreatedAtColumn            = sqlite.StringColumn("created_at")
		UpdatedAtColumn            = sqlite.StringColumn("updated_at")
		allColumns                 = sqlite.ColumnList{IDColumn, NameColumn, DescriptionColumn, ProcedureDescriptionColumn, TypeColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns             = sqlite.ColumnList{NameColumn, DescriptionColumn, ProcedureDescriptionColumn, TypeColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns             = sqlite.ColumnList{DescriptionColumn, TypeColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return tramitesTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                   IDColumn,
		Name:                 NameColumn,
		Description:          DescriptionColumn,
		ProcedureDescription: ProcedureDescriptionColumn,
		Type:                 TypeColumn,
		Status:               StatusColumn,
		CreatedAt:            CreatedAtColumn,
		UpdatedAt:            UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
