# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

output: prefixed

tasks:
  dev:
    prefix: site
    desc: Run site dev server
    cmds:
      - pnpm dev

  build:
    desc: Build site for production
    cmds:
      - pnpm build
