#let acronyms = (
  "SIAI": "Sistema de Información Ambiental Industrial",
  "MDPyEP": "Ministerio de Desarrollo Productivo y Economía Plural",
  "RASIM": "Reglamento Ambiental del Sector Industrial Manufacturero",
  "WFMS": ("Workflow Management System", "Workflow Management Systems"),
  "WF": "Workflow",
  "UML": "Unified Modeling Language",
  "BID": "Banco Interamericano de Desarrollo",
  "D.C.": "Después de Cristo",
  "IEEE": "The Institute of Electrical and Electronics Engineers",
  "DS": "Decreto Supremo",
  "SERI": "Sistema de Evaluación y Revelación de Información",
  "GAD": ("Gobierno Autónomo Departamental", "Gobiernos Autónomos Departamentales"),
  "GAM": ("Gobierno Autónomo Municipal", "Gobiernos Autónomos Municipales"),
  "PHP": "Personal Home Page",
  "REST": "Representational State Transfer",
  "API": "Application Programming Interface",
  "SPA": "Single Page Application",
  "FOSS": "Free and Open Source Software",
  "ERP": "Enterprise Resource Planning",
  "LGPLv3": "GNU Lesser General Public License v3",
  "AGETIC": "Agencia de Gobierno Electrónico y Tecnologías de Información y Comunicación",
  "TICs": "Tecnologías de la Información y Comunicación",
  "EGDI": "E-government Development Index",
  "IRAP": ("Instrumento de Regulación Ambiental Particular", "Instrumentos de Regulación Ambiental Particular"),
  "RAI": "Registro Ambiental Industrial",
  "EEIA": "Estudio de Evaluación de Impacto Ambiental",
  "DP": "Descripción del Proyecto",
  "PMA": "Plan de Manejo Ambiental",
  "MAI": "Manifiesto Ambiental Industrial",
  "ARI-PC": "Análisis de Riesgos Industriales y Plan de Contingencias",
  "IAA": "Informe Ambiental Anual",
  "MIT": "Massachusetts Institute of Technology",
  "BPM": "Business Process Management",
  "GUI": "Graphical User Interface",
  "CRM": "Customer Relationship Management",
  "UIMS": "User Interface Management System",
  "DBMS": "Database Management System",
  "OS": "Operating System",
  "LLM": "Large Language Model",
  "DRY": "Don't Repeat Yourself",
  "SRP": "Single Responsibility Principle",
  "SOLID": "SRP, Open-Closed Principle, Liskov Substitution Principle, Interface Segregation Principle, Dependency Inversion Principle",
  "VPS": "Virtual Private Server",
  "UMSA": "Universidad Mayor de San Andrés",
  "CLI": "Command Line Interface",
  "RUP": "Rational Unified Process",
  "UIT": "Unión Internacional de Telecomunicaciones",
  "NPM": "Node Package Manager",
)
