package api

import (
	"net/http"

	"github.com/C-ArenA/Tunkunia/internal/api/v1/oapi"
	"github.com/C-ArenA/Tunkunia/internal/authn"
	"github.com/C-ArenA/Tunkunia/internal/catalog"
	"github.com/C-ArenA/Tunkunia/internal/health"
)

var _ oapi.StrictServerInterface = (*StrictHandlerV1)(nil)

func NewStrictHandlerV1(catalogService *catalog.Service) *StrictHandlerV1 {
	return &StrictHandlerV1{
		health.NewStrictApiHandler(),
		catalog.NewStrictApiHandler(catalogService),
	}
}

type StrictHandlerV1 struct {
	*health.StrictApiHandler
	*catalog.StrictCatalogHandlerV1
}

func (h *StrictHandlerV1) Handler() http.Handler {
	server := oapi.NewStrictHandler(h, nil)
	return oapi.HandlerWithOptions(server, oapi.ChiServerOptions{
		// We are adding the requireAuthenticated middleware here because
		// since we cannot group routes that were generated by oapi-codegen
		// the only way to distinguish between routes that need auth and
		// routes that don't is by using a context value that is injected
		// by the oapi-codegen generated handler wrapper for each route.
		// We cannot access that context value before it was injected inside
		// the wrapper so we need to inject our own middleware to that wrapper
		Middlewares: []oapi.MiddlewareFunc{authn.RequireAuthenticated},
	})
}
