// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Tramite struct {
	ID                   int64
	Name                 string
	Description          sql.NullString
	ProcedureDescription sql.NullString
	Type                 sql.NullString
	Status               sql.NullString
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
}
