// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CaseStatus.
const (
	CaseStatusActive    CaseStatus = "active"
	CaseStatusCompleted CaseStatus = "completed"
)

// Valid indicates whether the value is a known member of the CaseStatus enum.
func (e CaseStatus) Valid() bool {
	switch e {
	case CaseStatusActive:
		return true
	case CaseStatusCompleted:
		return true
	default:
		return false
	}
}

// Defines values for CaseSummaryStatus.
const (
	CaseSummaryStatusActive    CaseSummaryStatus = "active"
	CaseSummaryStatusCompleted CaseSummaryStatus = "completed"
)

// Valid indicates whether the value is a known member of the CaseSummaryStatus enum.
func (e CaseSummaryStatus) Valid() bool {
	switch e {
	case CaseSummaryStatusActive:
		return true
	case CaseSummaryStatusCompleted:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	DEGRADED HealthStatus = "DEGRADED"
	DOWN     HealthStatus = "DOWN"
	UP       HealthStatus = "UP"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case DEGRADED:
		return true
	case DOWN:
		return true
	case UP:
		return true
	default:
		return false
	}
}

// Defines values for NotificationType.
const (
	ActionEnabled NotificationType = "action_enabled"
)

// Valid indicates whether the value is a known member of the NotificationType enum.
func (e NotificationType) Valid() bool {
	switch e {
	case ActionEnabled:
		return true
	default:
		return false
	}
}

// Defines values for ProcedureStatus.
const (
	ProcedureStatusDraft     ProcedureStatus = "draft"
	ProcedureStatusPublished ProcedureStatus = "published"
)

// Valid indicates whether the value is a known member of the ProcedureStatus enum.
func (e ProcedureStatus) Valid() bool {
	switch e {
	case ProcedureStatusDraft:
		return true
	case ProcedureStatusPublished:
		return true
	default:
		return false
	}
}

// Defines values for ProcedureNodeKind.
const (
	Place      ProcedureNodeKind = "place"
	Transition ProcedureNodeKind = "transition"
)

// Valid indicates whether the value is a known member of the ProcedureNodeKind enum.
func (e ProcedureNodeKind) Valid() bool {
	switch e {
	case Place:
		return true
	case Transition:
		return true
	default:
		return false
	}
}

// Defines values for ProcedureRole.
const (
	Citizen ProcedureRole = "citizen"
	Servant ProcedureRole = "servant"
)

// Valid indicates whether the value is a known member of the ProcedureRole enum.
func (e ProcedureRole) Valid() bool {
	switch e {
	case Citizen:
		return true
	case Servant:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	TaskStatusCancelled TaskStatus = "cancelled"
	TaskStatusCompleted TaskStatus = "completed"
	TaskStatusPending   TaskStatus = "pending"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusCancelled:
		return true
	case TaskStatusCompleted:
		return true
	case TaskStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for TramiteStatus.
const (
	TramiteStatusArchived  TramiteStatus = "archived"
	TramiteStatusDraft     TramiteStatus = "draft"
	TramiteStatusPublished TramiteStatus = "published"
)

// Valid indicates whether the value is a known member of the TramiteStatus enum.
func (e TramiteStatus) Valid() bool {
	switch e {
	case TramiteStatusArchived:
		return true
	case TramiteStatusDraft:
		return true
	case TramiteStatusPublished:
		return true
	default:
		return false
	}
}

// Defines values for TramiteType.
const (
	Certification TramiteType = "Trámite de certificación"
	Constancia    TramiteType = "Trámite de constancia"
	Obligation    TramiteType = "Trámite para cumplir con obligaciones"
	Otro          TramiteType = "Otro"
	Permiso       TramiteType = "Trámite para obtener permisos"
	Registro      TramiteType = "Trámite de registro"
	Servicio      TramiteType = "Trámite para acceder a servicios"
)

// Valid indicates whether the value is a known member of the TramiteType enum.
func (e TramiteType) Valid() bool {
	switch e {
	case Certification:
		return true
	case Constancia:
		return true
	case Obligation:
		return true
	case Otro:
		return true
	case Permiso:
		return true
	case Registro:
		return true
	case Servicio:
		return true
	default:
		return false
	}
}

// Defines values for ListCasesParamsScope.
const (
	Mine       ListCasesParamsScope = "mine"
	Unassigned ListCasesParamsScope = "unassigned"
)

// Valid indicates whether the value is a known member of the ListCasesParamsScope enum.
func (e ListCasesParamsScope) Valid() bool {
	switch e {
	case Mine:
		return true
	case Unassigned:
		return true
	default:
		return false
	}
}

// Defines values for ListTasksParamsStatus.
const (
	ListTasksParamsStatusCompleted ListTasksParamsStatus = "completed"
	ListTasksParamsStatusPending   ListTasksParamsStatus = "pending"
)

// Valid indicates whether the value is a known member of the ListTasksParamsStatus enum.
func (e ListTasksParamsStatus) Valid() bool {
	switch e {
	case ListTasksParamsStatusCompleted:
		return true
	case ListTasksParamsStatusPending:
		return true
	default:
		return false
	}
}

// AuditMetadata defines model for AuditMetadata.
type AuditMetadata struct {
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// Case defines model for Case.
type Case struct {
	AvailableTasks     []Task         `json:"availableTasks"`
	CompletedAt        *time.Time     `json:"completedAt,omitempty"`
	EnabledTransitions []string       `json:"enabledTransitions"`
	History            []CaseAction   `json:"history"`
	Id                 int64          `json:"id"`
	Marking            map[string]int `json:"marking"`
	Net                Net            `json:"net"`
	Participants       []Participant  `json:"participants"`
	ProcedureId        int64          `json:"procedureId"`
	ProcedureVersion   int            `json:"procedureVersion"`
	Revision           int64          `json:"revision"`
	StartedAt          time.Time      `json:"startedAt"`
	Status             CaseStatus     `json:"status"`
	TramiteId          int64          `json:"tramiteId"`
	TramiteName        string         `json:"tramiteName"`
	UpdatedAt          time.Time      `json:"updatedAt"`
}

// CaseStatus defines model for Case.Status.
type CaseStatus string

// CaseAction defines model for CaseAction.
type CaseAction struct {
	ActorId         int64     `json:"actorId"`
	ActorName       string    `json:"actorName"`
	Id              int64     `json:"id"`
	OccurredAt      time.Time `json:"occurredAt"`
	TransitionId    string    `json:"transitionId"`
	TransitionLabel string    `json:"transitionLabel"`
}

// CaseSummary defines model for CaseSummary.
type CaseSummary struct {
	Id          int64             `json:"id"`
	Revision    int64             `json:"revision"`
	StartedAt   time.Time         `json:"startedAt"`
	Status      CaseSummaryStatus `json:"status"`
	TramiteId   int64             `json:"tramiteId"`
	TramiteName string            `json:"tramiteName"`
	UpdatedAt   time.Time         `json:"updatedAt"`
}

// CaseSummaryStatus defines model for CaseSummary.Status.
type CaseSummaryStatus string

// ErrorDetail Error de validación basado en el ejemplo de la sección 3 de RFC 9457.
type ErrorDetail struct {
	Detail  string `json:"detail"`
	Pointer string `json:"pointer"`
}

// Health defines model for Health.
type Health struct {
	Status    HealthStatus `json:"status"`
	Timestamp time.Time    `json:"timestamp"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Institution defines model for Institution.
type Institution struct {
	AccentColor  string `json:"accentColor"`
	Acronym      string `json:"acronym"`
	Address      string `json:"address"`
	Description  string `json:"description"`
	Email        string `json:"email"`
	LogoUrl      string `json:"logoUrl"`
	Name         string `json:"name"`
	Phone        string `json:"phone"`
	PrimaryColor string `json:"primaryColor"`
	Website      string `json:"website"`
}

// Net defines model for Net.
type Net struct {
	Arcs           []ProcedureArc  `json:"arcs"`
	FinalPlaceId   string          `json:"finalPlaceId"`
	InitialPlaceId string          `json:"initialPlaceId"`
	Nodes          []ProcedureNode `json:"nodes"`
}

// Notification defines model for Notification.
type Notification struct {
	CaseId    int64            `json:"caseId"`
	CreatedAt time.Time        `json:"createdAt"`
	Id        int64            `json:"id"`
	ReadAt    *time.Time       `json:"readAt,omitempty"`
	TaskId    int64            `json:"taskId"`
	Title     string           `json:"title"`
	Type      NotificationType `json:"type"`
}

// NotificationType defines model for Notification.Type.
type NotificationType string

// Participant defines model for Participant.
type Participant struct {
	AssignedAt time.Time     `json:"assignedAt"`
	Name       string        `json:"name"`
	Role       ProcedureRole `json:"role"`
	UserId     int64         `json:"userId"`
}

// ProblemDetails Objeto estricto de detalles de problema de Tunkunia, basado en RFC 9457. Se serializa con el tipo de medio "application/problem+json" y admite miembros adicionales de extensión.
type ProblemDetails struct {
	// Detail Explicación de esta ocurrencia orientada a corregir el problema.
	Detail string `json:"detail"`

	// Instance Referencia URI que identifica esta ocurrencia del problema.
	Instance *string `json:"instance,omitempty"`

	// Status Código de estado que coincide con la respuesta HTTP.
	Status int32 `json:"status"`

	// Title Resumen legible del tipo de problema.
	Title string `json:"title"`

	// Type Referencia URI que identifica el tipo de problema.
	Type *string `json:"type,omitempty"`
}

// Procedure defines model for Procedure.
type Procedure struct {
	Id            int64           `json:"id"`
	Net           Net             `json:"net"`
	Status        ProcedureStatus `json:"status"`
	TramiteId     int64           `json:"tramiteId"`
	VersionNumber *int            `json:"versionNumber,omitempty"`
}

// ProcedureStatus defines model for Procedure.Status.
type ProcedureStatus string

// ProcedureArc defines model for ProcedureArc.
type ProcedureArc struct {
	From string `json:"from"`
	Id   string `json:"id"`
	To   string `json:"to"`
}

// ProcedureNode defines model for ProcedureNode.
type ProcedureNode struct {
	Id    string            `json:"id"`
	Kind  ProcedureNodeKind `json:"kind"`
	Label string            `json:"label"`
	Role  *ProcedureRole    `json:"role,omitempty"`
	X     int               `json:"x"`
	Y     int               `json:"y"`
}

// ProcedureNodeKind defines model for ProcedureNode.Kind.
type ProcedureNodeKind string

// ProcedureRole defines model for ProcedureRole.
type ProcedureRole string

// ProcedureViolation defines model for ProcedureViolation.
type ProcedureViolation struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Task defines model for Task.
type Task struct {
	AssigneeId      *int64        `json:"assigneeId,omitempty"`
	CaseId          int64         `json:"caseId"`
	CreatedAt       time.Time     `json:"createdAt"`
	Id              int64         `json:"id"`
	Role            ProcedureRole `json:"role"`
	Status          TaskStatus    `json:"status"`
	TransitionId    string        `json:"transitionId"`
	TransitionLabel string        `json:"transitionLabel"`
}

// TaskStatus defines model for Task.Status.
type TaskStatus string

// Tramite defines model for Tramite.
type Tramite struct {
	Id                   TramiteId     `json:"id"`
	Name                 string        `json:"name"`
	Description          string        `json:"description"`
	ProcedureDescription string        `json:"procedureDescription"`
	Status               TramiteStatus `json:"status"`
	Type                 TramiteType   `json:"type"`
	CreatedAt            time.Time     `json:"createdAt"`
	UpdatedAt            time.Time     `json:"updatedAt"`
}

// TramiteBase defines model for TramiteBase.
type TramiteBase struct {
	Id          TramiteId `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

// TramiteCollection defines model for TramiteCollection.
type TramiteCollection struct {
	Data []TramiteBase `json:"data"`
}

// TramiteCreate defines model for TramiteCreate.
type TramiteCreate struct {
	Description          *string      `json:"description,omitempty"`
	Name                 string       `json:"name"`
	ProcedureDescription *string      `json:"procedureDescription,omitempty"`
	Type                 *TramiteType `json:"type,omitempty"`
}

// TramiteId defines model for TramiteId.
type TramiteId = int64

// TramiteStatus defines model for TramiteStatus.
type TramiteStatus string

// TramiteType defines model for TramiteType.
type TramiteType string

// TramiteUpdate defines model for TramiteUpdate.
type TramiteUpdate struct {
	Description          string      `json:"description"`
	Name                 string      `json:"name"`
	ProcedureDescription string      `json:"procedureDescription"`
	Type                 TramiteType `json:"type"`
}

// TramiteWritableFields defines model for TramiteWritableFields.
type TramiteWritableFields struct {
	Description          *string      `json:"description,omitempty"`
	Name                 *string      `json:"name,omitempty"`
	ProcedureDescription *string      `json:"procedureDescription,omitempty"`
	Type                 *TramiteType `json:"type,omitempty"`
}

// User Every user is a citizen. The access flags grant additional, independent capabilities.
type User struct {
	Id            int64               `json:"id"`
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"emailVerified"`

	// IsAdmin Whether the citizen also has system administration access.
	IsAdmin bool `json:"isAdmin"`

	// IsPublicServant Whether the citizen is also authorized to act as a public servant.
	IsPublicServant bool   `json:"isPublicServant"`
	Name            string `json:"name"`
	Sub             string `json:"sub"`
}

// CaseId defines model for CaseId.
type CaseId = int64

// WorkflowTramiteId defines model for WorkflowTramiteId.
type WorkflowTramiteId = TramiteId

// BadRequest Objeto estricto de detalles de problema de Tunkunia, basado en RFC 9457. Se serializa con el tipo de medio "application/problem+json" y admite miembros adicionales de extensión.
type BadRequest = ProblemDetails

// Conflict Objeto estricto de detalles de problema de Tunkunia, basado en RFC 9457. Se serializa con el tipo de medio "application/problem+json" y admite miembros adicionales de extensión.
type Conflict = ProblemDetails

// Forbidden Objeto estricto de detalles de problema de Tunkunia, basado en RFC 9457. Se serializa con el tipo de medio "application/problem+json" y admite miembros adicionales de extensión.
type Forbidden = ProblemDetails

// InternalError Objeto estricto de detalles de problema de Tunkunia, basado en RFC 9457. Se serializa con el tipo de medio "application/problem+json" y admite miembros adicionales de extensión.
type InternalError = ProblemDetails

// NotFound Objeto estricto de detalles de problema de Tunkunia, basado en RFC 9457. Se serializa con el tipo de medio "application/problem+json" y admite miembros adicionales de extensión.
type NotFound = ProblemDetails

// Unauthorized Objeto estricto de detalles de problema de Tunkunia, basado en RFC 9457. Se serializa con el tipo de medio "application/problem+json" y admite miembros adicionales de extensión.
type Unauthorized = ProblemDetails

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// Detail Explicación de esta ocurrencia orientada a corregir el problema.
	Detail string `json:"detail"`

	// Errors Lista de errores de validación identificados.
	Errors []ErrorDetail `json:"errors"`

	// Instance Referencia URI que identifica esta ocurrencia del problema.
	Instance *string `json:"instance,omitempty"`

	// Status Código de estado que coincide con la respuesta HTTP.
	Status int32 `json:"status"`

	// Title Resumen legible del tipo de problema.
	Title string `json:"title"`

	// Type Referencia URI que identifica el tipo de problema.
	Type *string `json:"type,omitempty"`
}

// ListCasesParams defines parameters for ListCases.
type ListCasesParams struct {
	Scope ListCasesParamsScope `form:"scope" json:"scope"`
}

// ListCasesParamsScope defines parameters for ListCases.
type ListCasesParamsScope string

// FireTransitionJSONBody defines parameters for FireTransition.
type FireTransitionJSONBody struct {
	ExpectedRevision int64 `json:"expectedRevision"`
}

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	Status *ListTasksParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListTasksParamsStatus defines parameters for ListTasks.
type ListTasksParamsStatus string

// ListTramitesParams defines parameters for ListTramites.
type ListTramitesParams struct {
	// Status Filtra los trámites por estado.
	Status *TramiteStatus `form:"status,omitempty" json:"status,omitempty"`
}

// UpdateUserAccessJSONBody defines parameters for UpdateUserAccess.
type UpdateUserAccessJSONBody struct {
	IsAdmin         bool `json:"isAdmin"`
	IsPublicServant bool `json:"isPublicServant"`
}

// FireTransitionJSONRequestBody defines body for FireTransition for application/json ContentType.
type FireTransitionJSONRequestBody FireTransitionJSONBody

// UpdateInstitutionJSONRequestBody defines body for UpdateInstitution for application/json ContentType.
type UpdateInstitutionJSONRequestBody = Institution

// CreateTramiteJSONRequestBody defines body for CreateTramite for application/json ContentType.
type CreateTramiteJSONRequestBody = TramiteCreate

// UpdateTramiteJSONRequestBody defines body for UpdateTramite for application/json ContentType.
type UpdateTramiteJSONRequestBody = TramiteUpdate

// SaveDraftProcedureJSONRequestBody defines body for SaveDraftProcedure for application/json ContentType.
type SaveDraftProcedureJSONRequestBody = Net

// UpdateUserAccessJSONRequestBody defines body for UpdateUserAccess for application/json ContentType.
type UpdateUserAccessJSONRequestBody UpdateUserAccessJSONBody

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Hzbchs3mvCroHrmYlJ/S6QOnkx09Wsk26NUbGstOa5a27sFAh9J2GigA6AZ0y49jB8gF1u521u92NYH",
	"9JHdTTYZS3KmKlWRJRy+M75jf46YTlKtQDkbnXyOUmpoAg6M/9cZtXDB8SehopMopW4exZGiCUQnkeBR",
	"HBn4JRMGeHTiTAZxZNkcEoo7ptok1OE65f5+HMVRIpRIsiQ6OYgjt0wh/AlmYKKbmzh6rc2HqdS/Xhua",
	"CLfztX81MI1Oor+MKrxG4a92VB19gzcasKlWFjyq/6T8JfySgXX4L6aVA+V/pGkqBaNOaDVKjZ5ISP7f",
	"e6sV/m3YtZdh1zk4KqQNd3OwzIgUT41OoistBRMu40RpQhmkjnJKNAGEggtO98l/ZOLT7RcypdIBoXJ2",
	"+7+KpNTcfknAGU2QIGAE1/vRTRydaTWVgj0EKj9RolMwlInb3xUiYCgBRVgOkcafCEgC1lGOyLqMSg/0",
	"E20mgnNQDwD1c02cAAUkBZMIqy3SlhIDVIpP1HhoiS245MG9UA6MovKxMdo8DMgWSJpxTeA9sMxRQ+Qq",
	"kM+1e6IzxR8AvseSGGCZsbqACfmtNIGPwjrw4F0azYBnBtbAtzVc+YkdIIU/ikSAchrvf6Vo5ubaiE/A",
	"H4yFc0pSoxfCOk0yRQkzwEExQSVZ3H6RqP0I688Uf8Sdu0sclfLFNDp5sx3g8ecoNajUTgRbCQiA/2lF",
	"9wWqCQfiF4DFHxce7GANBAflxFQwyrXdj+JIOEjsJjp6dAMw0U35dFBj6DK6uam/BW8KyN6Vy/TkPTAX",
	"3bzrMlXaEk6dtiX9LbFaEaGYNgaYQyBxWw4JAnqaceGeAdpn50napAwzQB3wU88T+EiTVCIUh+PDv++N",
	"j/YOHl0fHJ8cjU/G4/+M4uqJ5NTBnhMJRCXg1hmhZlEcfdzThoOJTg7G45s4ylLef8Px3vjw+uDg5ODR",
	"yeHhLjccrBK0Qqh+dZu+sfcVhssYrr7KkoSaZYeA0QUVkk4kXFP7wf9mkKTg6raIxN7FkVBSbQBRbuII",
	"FALArw1VVqDENOForV+9dI4CZZaDgUeKnDK8qOu0hJoPeBESh3MPD5WXDaKV/tW47V918EuB2wTSc/Ar",
	"U2qcYCKluY84CJ3LalMXPmlhpy94gyWFs9hGoNzxMxgrgmXrcCPrwlu/pOOAiqqBGiuYdopAvCqbFaO7",
	"jE4c1djashaUOW0GE8Cvfu6d4A7xE0OP0YxlxmynC66kQIB2zYKf6ARkx5oV1ngvvnFs+5C4JFAd+QYG",
	"fYaoMC0tkg8mk4GFKMRswHLrqNnSwFhHXRbeU4Vq+waRFAtcWxqs6F3HRlePkAbAlq/vFZ3GkzIE9h5e",
	"5kA1LyzxrJG0Tq5Nz0r99W85HP6Pq17GhFr0NCGEGe8hSaXGNegcAwtrjvAXL5+ckR+OH32/H8UrUsLL",
	"+1rESjVS1myW8PyMakcXdv8CKt28LaZt2Xh1GcXR+YvXz/F/j5++PD1/fN4tHSIB62iSdjkI+N/1waOt",
	"XJBVxEp+Vjd1oXahrBMu67N8DJQ70zI4sil1Dgxy9L/+8ma89wPdm57uPXn3+e83f+3SHMqMVssEdyb0",
	"40+gZkjDw7HPMRT/POjayLkB2/1+NySr4++Q9ImE1DP9ysiG9mRG7BmYggHFOrVf5dq4AeJ0rlW31qZG",
	"oInblYa/wsQKB9sAvSIHKqh3wYwmBSuqFJQrcKm4UAGxgk3ckI8u4XoOrkOoDNvCPym8gVPDuhyUqUAH",
	"S1IGPU+eUMKJ9UuU5rADRM81h42RTjg7Dki3oFmBv5OEOoRi3QrKyszfgAemEfUMe/y2eIfpVgc7aj8M",
	"fxmFk7DGm28+zVr9d+4RdhjerjcxJ2IJVL6puLdOuC4O1V3otrBbK2ZqO6KrPg/AaAmDxfMlLka3wcJQ",
	"53WFOP668oC4tCQVSp3kaKYlWs7Ai8l7cJoAooWJRg4E32ApQyIiz4r4/MR1pj5kStC45iyU3gC5AmLB",
	"CJ/6K9KVTqT+xAS40ORtb77lbUSWhPJEOCCJgGRitCWUC+YDtgAJfHSgLPoh+2/VGt9jxdf56G8M/gue",
	"grkW7T1hxQQl2ghQPm+MQBsDM2EQ8gJv9HIqd+AqI4xaj5LDJDLCi6iy29+5mGnyaDw+PjzGdJ0FAopl",
	"IZO7EDNQrlujlXVUMWhD/jJ/UgQlr15ekF8yqGWCWnjwXphHHgo6Ojg8On40SkBZ+h7siE5YFA9+xOp+",
	"dxPMsxz1nLZce0iZFooJHqgjMSVs08zD/K/r68sGgMfjo7ihC0eHPsb8GMLyRz/8UCuCHI/Hay3SKglt",
	"loAiEmZiIoHwmkh2E+uVdeDLCeBz2YUhgRw9aLF/v9Oa5maQw5RmEtGiE525k4mk6kMUb8foTSAXimRH",
	"QnmHfo8JJz6B2oK9K5amMLSlz5prV499qZLRO0aNw5MqbQ+fGzr1SYhsIoWdf6XgbxGSHc+zZNKIWvps",
	"cyuYK0mHuK2lG3pSLdJNjU4G+LmCD1jk9MZFXdh4EPzuteB7t6uH9RsA+yAUr7MyRb+rkdHo5KXsyZXs",
	"+CB/7GJvHC2Hct1jUUCFx+HetSR7mYNZ4F3pqwWzoMp1ol1u/1lo2ed/5sxobU7AWjqDzfG3P6Fa34WH",
	"zxf3eVZbuL/fjK+8i9S0DVEKioesaJWHQiwVAyn7zdJdZAgrD3pTqjD3KUtrtd61zjsBhtcr8g3/pBZ8",
	"vWLd2maNqF3dKBPR582UQ/USPpYksxk1Al/LCb7VZoblXW19oV9Y4bQlXiIk2JiATcFQ00iDccDiOrVk",
	"ScKFYAhFD2YqDHrBYiYcVt7XekgDSHIVFtechQGbrnFpb7r+vJFIyGOmHKjuLHudPS2F5n1kvi48Xwkz",
	"KkPJX1KiJw5UIOKSoB9tnQluCxirFZjb3yh5n5nb3zj6NUhoq5mgTGgFljCxEBLs/rpK21Gp1sP6VepF",
	"ulogV6FyoTyOJesva6D+WIC6DqLDTv3LI7M6Bdeo05mWEnpqHUW9dFghr6Ft6xMh/uB1QHlDsLWmvzbC",
	"Yaz/RIDkoQjeSn6tlcWeF2FdF1QcNXVqrXPoUz9zsQgGuZKEYmVLq+uqVzv5hTM6iitd4FDK/MqvGZjg",
	"ynspW/2jDvGfoPU/eJViWZJKYXAJ0RMpZrmmtBZSVpgpdB8EE7q9xisnmLJRp4l8jkxbyhFbrEfYGsov",
	"KzTPCtRym3NWx+aFhzn/y1UOWRRHlwGEqMb0V76WsdEEDc/M9L0VvZHarsa3Q9PjtRZ5jcqt6M6fhBot",
	"bF5ZMC1wo8cLMEuSWTBEWMy1BJ93n1zPwUuwtWQq6cySmaHKkapcHxOhOKB3BcoRRlM6EVI4Ed6KJonK",
	"akMl2+/1XO1zDf8//9U+82FNaWGKNHt35eJnMGIqQptTeWZonsw3TLSWQNVwj3PlURL2lCdCtSn2eg5u",
	"Doa4ORTUIlRaTebUEru0DhKfMlOojV7Pcjo20gNTKm03sPYSjSK7ykOOQfcLG0Co+r+I892IhCJTvZll",
	"JI9iGnD00az9Jv+o54qc6+4kVDZpLv5+dnT8/fE/vj8+mv3j+Gj2/bCqa661eFpVZ2nyu2JMm1RtHUbQ",
	"gGVGuOUV6kneHAvUgDnNQqly4v/1pJCOH19ftzJB1/oDKPLj6+u88Eqr3CUS06ugp58/qsJ17lwaOuWE",
	"muo2K33T5ZR+wmN9VZXmBd08TWuziRUoUN4tm4F1hUM0ldl7bRv5ziILvP9WPcaEHtgUWPXAYeYzs9hi",
	"mz9jWtksCaVkPElYJxT64U6k4WQmBSgHdv+tusQdUs/QK8+UQFUSnHI804pZBoqk5vYLc4JRm9NIKJ4h",
	"rylZErDu9ovi1IAtcq725K0iZI+8KRLV7/6G1LInoxG6QM5Q9gHMvgA33ddmNuKajeYukSMzZbj8u3z7",
	"uWaYSnQBydohmtl9vD/1lmVEU7G3ONzTC3zw4NfvyJK8qRJ8a/eNFocjpg2MKGM6U85+l6N4enmBP135",
	"1WRxGEB6mt3+FqjAhYXb//EkPr288L9681TrmYSV+5jUGd+f+T8Vt9oRB4zcEVLc+Ewwo62eumrvTLh5",
	"NvEbkuKvHtFZJjhIocB+R/52+ikzQJbkJ5hRtvzO5+ilYKBCcBEUPXp2gWKfGZmLLZ6vU1BWZ4aBZ0G+",
	"yY5wbZXcjQrBQySjMkUXnUQH+2Nch8fQVEQn0dE+/ir2LfBeE0cYEfufZiHV6Juti7jbd2Ce+RVxo5X/",
	"Td5Kj03iy6qX3jLtY6v+dvrCS0yEL91mqijSdJXA3q301B+Ox1s19g7uk6s6B1djg1aT5xm1GnXIYt7c",
	"h6nH46O+O0roR1Uzet0kekLWjeGbd4i0zcEJ9KfG59Z9V2kqtCW+65ki2Sj3Hq2jM+RJOfJgo3d4S+Dt",
	"6LPgN70Mfgqev9EfpPQmAndR8jwU03ztAREMtDzeTMuyCX0rUr7IHX1/VTfNWjLeBUe1ZJSPs9y8axJ7",
	"xCQVyer0yxbHxVGqbQezzvDch2IXCn4pdbvIPe74YfOOctZkK+6eZk4H4Aw+s2odm1e4VeX+7OhzPS94",
	"M5qKvHqzEx/jznmjlcxjv6lcX5foFZInwkDVYZrfANb9U/PlVkKyEkB8TIE54C/X9TFuGMlqdNavntfh",
	"O96skufmAeQ+0DIfPwqDMZx+c/L/uBjZcTVw5yEgRHj7NWFetgz2PRB5U+Ed0j6/oXvqp8jdBCeWWCoz",
	"jtkAsgyTYUT5vHUCKp8C2vIRiaNH46N7RkUV2HCBAPkavCbTTPm+Dt8YQhXixmFmKKd+ZqcpDw32XyFR",
	"yLPb33km62YvhyZwWjQ7KPvYXW+0vEOe16/pem60mopZVgz+5bCHtpcdmTzevKE5hLeqgTfxeiUsXAwM",
	"vnyfAkZoTcgr1tTx965H1sGOkP9b5chu9nwrZtyf3f0DcpBPe4pPpUUewOLaYK7fcrB5S2OsbyfL/xWE",
	"b737UxBiJ+FD45DAOpvw7E5dTp8Y7eD9hfIeRlGEqoqYNMNL/dzf/h/g4v1bkEHmQ/SgXeMfUqx4wFWt",
	"8XZ9JP+8sfI+guv6jUOi62J9XvoMBVJaBtpbc3mHWFv1gtDvQzVYEKIKA5R3hA53/d2D3rDgGTUf6tx4",
	"CTTc2xCB43aKtGIJiqOE298KY3tnofozaliDEyEjm+ji+n5OuGLAs1cJijG7Iemsovmj4kbVuFh1tazr",
	"c3morFb36GpHdEMN0IdRNNe6eg1bQ22tztnVZu3wvQVJiSymxovEPObP98hPedrOUeXAEnv7u9Rk4ae6",
	"IAGfeA9VGj9MXuxgqMd+9hyXUg7J7RdLbFZl4ybamHzJsnZWKKY3zqpqUtWJTnNtff6/3BqauDsEt6BB",
	"S3abpHgipPPFAltRgKTa5F3Ifk5+mLBv0a3zh6V6wF21dpCu6fs223d2De4hVsiVoGhGqAv/GXVU6lmI",
	"CnJjvvLhCTC4idDCNbC+YGW0RAJUcpbbbP8NiKqNS2WwaAhHGG1k1N1+wSmrJhG96CbCJtoSRRmY2y95",
	"eSw0tfv+EGwKy4CHD7MELyZTJK1/H4MsKLv9TbdEO/TT5Cy+o/Cm2bozKMA5+NqXdwY3dbaUfSnwUTht",
	"v/GI5vjwcPOO1W+MbPVMIHEqBenUj/rTUNY5OODT2378z/3v64K2yfWpOCJFIhTlOiYKJ2JwEsGA00ZR",
	"c580vzuX63HAcAO9494AsZes4/vQo/NqLktWGHwDNI4/d4d4G6i89n2/OG+iGd/hV83erc1L3YvRDlfd",
	"d1ZqjbCVVqHKPunCZvsk9DduuO8wbtPcB2zbWu1R3nm6famt/ZG//gj4NFyy0wNQevPfHM0DVr7w0yJ5",
	"XxSVV6mLzo+7I/mVo6anv+DgfgrWQgkmSr7dWfntwl8TmgtCpoKJDMs2Sg/mR1qfF+x7Zy+Lfu1qurDb",
	"Cq7Hstr9h6Wz+4Fruv5lYP2VGi+6ZHANQUehh30NWc9xwVcl6TdkIgqeFJmKYiS6YtAdsqXHgbiiC+gg",
	"+tf3Ivx47GDf4c/K4qcZNZzuwOKNWjPKJ0Tu9qHIzdqfSQPLEHjHhppFMay6wxddqkHXTdNMtVu6G2xa",
	"X9s15Zg/fjz09ZM9Ba74cGhoXAZJnv18uZ2AhkyAIcviLTCDxTOz+deje1P6oRp2H2n1UKncnFZ/VaTl",
	"8tEn36h5Xz7+Drn4Mo1YtI5X00pdJUfPko2NpbjjIcrGOfFrtP/3CK+Kd7yogmNOv/4JXNPBrfghCpDU",
	"sXlfzgABO/XTOF+tNbE2KDRommd10eogzDbjLfealNgk8LWExL+HxNfaWkCGIS690gLEfbfvmg6Jm/Dx",
	"iO5c2jNhE020ETNQPqvrv8hTfnWmnDLZL0czwjzKgfdl8rtaH/4pCyktUGu1qVL9isTITbx60ONQYcnV",
	"aKG9V1f0ENZOKHoOWwecw9QHwL6TIW9enfgJfz9REBc12OVK10Pt7Oo1bh//tJiHarMkf09qBwWGtA+5",
	"KJuVloStafaqHdVoGXt3838DAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
