// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CaseStatus.
const (
	CaseStatusActive    CaseStatus = "active"
	CaseStatusCompleted CaseStatus = "completed"
)

// Valid indicates whether the value is a known member of the CaseStatus enum.
func (e CaseStatus) Valid() bool {
	switch e {
	case CaseStatusActive:
		return true
	case CaseStatusCompleted:
		return true
	default:
		return false
	}
}

// Defines values for CaseSummaryStatus.
const (
	CaseSummaryStatusActive    CaseSummaryStatus = "active"
	CaseSummaryStatusCompleted CaseSummaryStatus = "completed"
)

// Valid indicates whether the value is a known member of the CaseSummaryStatus enum.
func (e CaseSummaryStatus) Valid() bool {
	switch e {
	case CaseSummaryStatusActive:
		return true
	case CaseSummaryStatusCompleted:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	DEGRADED HealthStatus = "DEGRADED"
	DOWN     HealthStatus = "DOWN"
	UP       HealthStatus = "UP"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case DEGRADED:
		return true
	case DOWN:
		return true
	case UP:
		return true
	default:
		return false
	}
}

// Defines values for NotificationType.
const (
	ActionEnabled NotificationType = "action_enabled"
)

// Valid indicates whether the value is a known member of the NotificationType enum.
func (e NotificationType) Valid() bool {
	switch e {
	case ActionEnabled:
		return true
	default:
		return false
	}
}

// Defines values for ProcedureNodeKind.
const (
	Place      ProcedureNodeKind = "place"
	Transition ProcedureNodeKind = "transition"
)

// Valid indicates whether the value is a known member of the ProcedureNodeKind enum.
func (e ProcedureNodeKind) Valid() bool {
	switch e {
	case Place:
		return true
	case Transition:
		return true
	default:
		return false
	}
}

// Defines values for ProcedureRole.
const (
	ProcedureRoleCitizen ProcedureRole = "citizen"
	ProcedureRoleServant ProcedureRole = "servant"
)

// Valid indicates whether the value is a known member of the ProcedureRole enum.
func (e ProcedureRole) Valid() bool {
	switch e {
	case ProcedureRoleCitizen:
		return true
	case ProcedureRoleServant:
		return true
	default:
		return false
	}
}

// Defines values for ProcedureVersionStatus.
const (
	ProcedureVersionStatusDraft     ProcedureVersionStatus = "draft"
	ProcedureVersionStatusPublished ProcedureVersionStatus = "published"
)

// Valid indicates whether the value is a known member of the ProcedureVersionStatus enum.
func (e ProcedureVersionStatus) Valid() bool {
	switch e {
	case ProcedureVersionStatusDraft:
		return true
	case ProcedureVersionStatusPublished:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	TaskStatusCancelled TaskStatus = "cancelled"
	TaskStatusCompleted TaskStatus = "completed"
	TaskStatusPending   TaskStatus = "pending"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusCancelled:
		return true
	case TaskStatusCompleted:
		return true
	case TaskStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for TramiteStatus.
const (
	TramiteStatusArchived  TramiteStatus = "archived"
	TramiteStatusDraft     TramiteStatus = "draft"
	TramiteStatusPublished TramiteStatus = "published"
)

// Valid indicates whether the value is a known member of the TramiteStatus enum.
func (e TramiteStatus) Valid() bool {
	switch e {
	case TramiteStatusArchived:
		return true
	case TramiteStatusDraft:
		return true
	case TramiteStatusPublished:
		return true
	default:
		return false
	}
}

// Defines values for TramiteType.
const (
	Certification TramiteType = "Trámite de certificación"
	Constancia    TramiteType = "Trámite de constancia"
	Obligation    TramiteType = "Trámite para cumplir con obligaciones"
	Otro          TramiteType = "Otro"
	Permiso       TramiteType = "Trámite para obtener permisos"
	Registro      TramiteType = "Trámite de registro"
	Servicio      TramiteType = "Trámite para acceder a servicios"
)

// Valid indicates whether the value is a known member of the TramiteType enum.
func (e TramiteType) Valid() bool {
	switch e {
	case Certification:
		return true
	case Constancia:
		return true
	case Obligation:
		return true
	case Otro:
		return true
	case Permiso:
		return true
	case Registro:
		return true
	case Servicio:
		return true
	default:
		return false
	}
}

// Defines values for ListCasesParamsScope.
const (
	Mine       ListCasesParamsScope = "mine"
	Unassigned ListCasesParamsScope = "unassigned"
)

// Valid indicates whether the value is a known member of the ListCasesParamsScope enum.
func (e ListCasesParamsScope) Valid() bool {
	switch e {
	case Mine:
		return true
	case Unassigned:
		return true
	default:
		return false
	}
}

// Defines values for ListTasksParamsStatus.
const (
	ListTasksParamsStatusCompleted ListTasksParamsStatus = "completed"
	ListTasksParamsStatusPending   ListTasksParamsStatus = "pending"
)

// Valid indicates whether the value is a known member of the ListTasksParamsStatus enum.
func (e ListTasksParamsStatus) Valid() bool {
	switch e {
	case ListTasksParamsStatusCompleted:
		return true
	case ListTasksParamsStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for UpdateUserRolesJSONBodyRoles.
const (
	UpdateUserRolesJSONBodyRolesAdmin   UpdateUserRolesJSONBodyRoles = "admin"
	UpdateUserRolesJSONBodyRolesServant UpdateUserRolesJSONBodyRoles = "servant"
)

// Valid indicates whether the value is a known member of the UpdateUserRolesJSONBodyRoles enum.
func (e UpdateUserRolesJSONBodyRoles) Valid() bool {
	switch e {
	case UpdateUserRolesJSONBodyRolesAdmin:
		return true
	case UpdateUserRolesJSONBodyRolesServant:
		return true
	default:
		return false
	}
}

// AuditMetadata defines model for AuditMetadata.
type AuditMetadata struct {
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// Case defines model for Case.
type Case struct {
	AvailableTasks     []Task              `json:"availableTasks"`
	CompletedAt        *time.Time          `json:"completedAt,omitempty"`
	Definition         ProcedureDefinition `json:"definition"`
	EnabledTransitions []string            `json:"enabledTransitions"`
	History            []CaseAction        `json:"history"`
	Id                 int64               `json:"id"`
	Marking            map[string]int      `json:"marking"`
	Participants       []Participant       `json:"participants"`
	ProcedureVersion   int                 `json:"procedureVersion"`
	ProcedureVersionId int64               `json:"procedureVersionId"`
	Revision           int64               `json:"revision"`
	StartedAt          time.Time           `json:"startedAt"`
	Status             CaseStatus          `json:"status"`
	TramiteId          int64               `json:"tramiteId"`
	TramiteName        string              `json:"tramiteName"`
	UpdatedAt          time.Time           `json:"updatedAt"`
}

// CaseStatus defines model for Case.Status.
type CaseStatus string

// CaseAction defines model for CaseAction.
type CaseAction struct {
	ActorId         int64     `json:"actorId"`
	ActorName       string    `json:"actorName"`
	Id              int64     `json:"id"`
	OccurredAt      time.Time `json:"occurredAt"`
	TransitionId    string    `json:"transitionId"`
	TransitionLabel string    `json:"transitionLabel"`
}

// CaseSummary defines model for CaseSummary.
type CaseSummary struct {
	Id          int64             `json:"id"`
	Revision    int64             `json:"revision"`
	StartedAt   time.Time         `json:"startedAt"`
	Status      CaseSummaryStatus `json:"status"`
	TramiteId   int64             `json:"tramiteId"`
	TramiteName string            `json:"tramiteName"`
	UpdatedAt   time.Time         `json:"updatedAt"`
}

// CaseSummaryStatus defines model for CaseSummary.Status.
type CaseSummaryStatus string

// CollectionBase defines model for CollectionBase.
type CollectionBase struct {
	NextPageUrl     *string `json:"nextPageUrl"`
	PreviousPageUrl *string `json:"previousPageUrl"`
}

// ErrorDetail Error de validación basado en el ejemplo de la sección 3 de RFC 9457.
type ErrorDetail struct {
	Detail  string `json:"detail"`
	Pointer string `json:"pointer"`
}

// Health defines model for Health.
type Health struct {
	Status    HealthStatus `json:"status"`
	Timestamp time.Time    `json:"timestamp"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Notification defines model for Notification.
type Notification struct {
	CaseId    int64            `json:"caseId"`
	CreatedAt time.Time        `json:"createdAt"`
	Id        int64            `json:"id"`
	ReadAt    *time.Time       `json:"readAt,omitempty"`
	TaskId    int64            `json:"taskId"`
	Title     string           `json:"title"`
	Type      NotificationType `json:"type"`
}

// NotificationType defines model for Notification.Type.
type NotificationType string

// Participant defines model for Participant.
type Participant struct {
	AssignedAt time.Time     `json:"assignedAt"`
	Name       string        `json:"name"`
	Role       ProcedureRole `json:"role"`
	UserId     int64         `json:"userId"`
}

// ProblemDetails Objeto estricto de detalles de problema de Tunkunia, basado en RFC 9457. Se serializa con el tipo de medio "application/problem+json" y admite miembros adicionales de extensión.
type ProblemDetails struct {
	// Detail Explicación de esta ocurrencia orientada a corregir el problema.
	Detail string `json:"detail"`

	// Instance Referencia URI que identifica esta ocurrencia del problema.
	Instance *string `json:"instance,omitempty"`

	// Status Código de estado que coincide con la respuesta HTTP.
	Status int32 `json:"status"`

	// Title Resumen legible del tipo de problema.
	Title string `json:"title"`

	// Type Referencia URI que identifica el tipo de problema.
	Type *string `json:"type,omitempty"`
}

// ProcedureArc defines model for ProcedureArc.
type ProcedureArc struct {
	From string `json:"from"`
	Id   string `json:"id"`
	To   string `json:"to"`
}

// ProcedureDefinition defines model for ProcedureDefinition.
type ProcedureDefinition struct {
	Arcs           []ProcedureArc  `json:"arcs"`
	FinalPlaceId   string          `json:"finalPlaceId"`
	InitialPlaceId string          `json:"initialPlaceId"`
	Nodes          []ProcedureNode `json:"nodes"`
}

// ProcedureNode defines model for ProcedureNode.
type ProcedureNode struct {
	Id    string            `json:"id"`
	Kind  ProcedureNodeKind `json:"kind"`
	Label string            `json:"label"`
	Role  *ProcedureRole    `json:"role,omitempty"`
	X     int               `json:"x"`
	Y     int               `json:"y"`
}

// ProcedureNodeKind defines model for ProcedureNode.Kind.
type ProcedureNodeKind string

// ProcedureRole defines model for ProcedureRole.
type ProcedureRole string

// ProcedureVersion defines model for ProcedureVersion.
type ProcedureVersion struct {
	Definition    ProcedureDefinition    `json:"definition"`
	Id            int64                  `json:"id"`
	Status        ProcedureVersionStatus `json:"status"`
	TramiteId     int64                  `json:"tramiteId"`
	VersionNumber *int                   `json:"versionNumber,omitempty"`
}

// ProcedureVersionStatus defines model for ProcedureVersion.Status.
type ProcedureVersionStatus string

// ProcedureViolation defines model for ProcedureViolation.
type ProcedureViolation struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Task defines model for Task.
type Task struct {
	AssigneeId      *int64        `json:"assigneeId,omitempty"`
	CaseId          int64         `json:"caseId"`
	CreatedAt       time.Time     `json:"createdAt"`
	Id              int64         `json:"id"`
	Role            ProcedureRole `json:"role"`
	Status          TaskStatus    `json:"status"`
	TransitionId    string        `json:"transitionId"`
	TransitionLabel string        `json:"transitionLabel"`
}

// TaskStatus defines model for Task.Status.
type TaskStatus string

// Tramite defines model for Tramite.
type Tramite struct {
	Id                   TramiteId     `json:"id"`
	Name                 string        `json:"name"`
	Description          string        `json:"description"`
	ProcedureDescription string        `json:"procedureDescription"`
	Status               TramiteStatus `json:"status"`
	Type                 TramiteType   `json:"type"`
	CreatedAt            time.Time     `json:"createdAt"`
	UpdatedAt            time.Time     `json:"updatedAt"`
}

// TramiteBase defines model for TramiteBase.
type TramiteBase struct {
	Id          TramiteId `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

// TramiteCollection defines model for TramiteCollection.
type TramiteCollection struct {
	Data            []TramiteBase `json:"data"`
	NextPageUrl     *string       `json:"nextPageUrl"`
	PreviousPageUrl *string       `json:"previousPageUrl"`
}

// TramiteCreate defines model for TramiteCreate.
type TramiteCreate struct {
	Description          *string      `json:"description,omitempty"`
	Name                 string       `json:"name"`
	ProcedureDescription *string      `json:"procedureDescription,omitempty"`
	Type                 *TramiteType `json:"type,omitempty"`
}

// TramiteId defines model for TramiteId.
type TramiteId = int64

// TramiteStatus defines model for TramiteStatus.
type TramiteStatus string

// TramiteType defines model for TramiteType.
type TramiteType string

// TramiteUpdate defines model for TramiteUpdate.
type TramiteUpdate struct {
	Description          *string        `json:"description,omitempty"`
	Name                 *string        `json:"name,omitempty"`
	ProcedureDescription *string        `json:"procedureDescription,omitempty"`
	Status               *TramiteStatus `json:"status,omitempty"`
	Type                 *TramiteType   `json:"type,omitempty"`
}

// TramiteWritableFields defines model for TramiteWritableFields.
type TramiteWritableFields struct {
	Description          *string      `json:"description,omitempty"`
	Name                 *string      `json:"name,omitempty"`
	ProcedureDescription *string      `json:"procedureDescription,omitempty"`
	Type                 *TramiteType `json:"type,omitempty"`
}

// User defines model for User.
type User struct {
	Id            int64               `json:"id"`
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"emailVerified"`
	Name          string              `json:"name"`
	Roles         []string            `json:"roles"`
	Sub           string              `json:"sub"`
}

// CaseId defines model for CaseId.
type CaseId = int64

// WorkflowTramiteId defines model for WorkflowTramiteId.
type WorkflowTramiteId = TramiteId

// BadRequest Objeto estricto de detalles de problema de Tunkunia, basado en RFC 9457. Se serializa con el tipo de medio "application/problem+json" y admite miembros adicionales de extensión.
type BadRequest = ProblemDetails

// Conflict Objeto estricto de detalles de problema de Tunkunia, basado en RFC 9457. Se serializa con el tipo de medio "application/problem+json" y admite miembros adicionales de extensión.
type Conflict = ProblemDetails

// Forbidden Objeto estricto de detalles de problema de Tunkunia, basado en RFC 9457. Se serializa con el tipo de medio "application/problem+json" y admite miembros adicionales de extensión.
type Forbidden = ProblemDetails

// InternalError Objeto estricto de detalles de problema de Tunkunia, basado en RFC 9457. Se serializa con el tipo de medio "application/problem+json" y admite miembros adicionales de extensión.
type InternalError = ProblemDetails

// NotFound Objeto estricto de detalles de problema de Tunkunia, basado en RFC 9457. Se serializa con el tipo de medio "application/problem+json" y admite miembros adicionales de extensión.
type NotFound = ProblemDetails

// Unauthorized Objeto estricto de detalles de problema de Tunkunia, basado en RFC 9457. Se serializa con el tipo de medio "application/problem+json" y admite miembros adicionales de extensión.
type Unauthorized = ProblemDetails

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// Detail Explicación de esta ocurrencia orientada a corregir el problema.
	Detail string `json:"detail"`

	// Errors Lista de errores de validación identificados.
	Errors []ErrorDetail `json:"errors"`

	// Instance Referencia URI que identifica esta ocurrencia del problema.
	Instance *string `json:"instance,omitempty"`

	// Status Código de estado que coincide con la respuesta HTTP.
	Status int32 `json:"status"`

	// Title Resumen legible del tipo de problema.
	Title string `json:"title"`

	// Type Referencia URI que identifica el tipo de problema.
	Type *string `json:"type,omitempty"`
}

// ListCasesParams defines parameters for ListCases.
type ListCasesParams struct {
	Scope ListCasesParamsScope `form:"scope" json:"scope"`
}

// ListCasesParamsScope defines parameters for ListCases.
type ListCasesParamsScope string

// FireTransitionJSONBody defines parameters for FireTransition.
type FireTransitionJSONBody struct {
	ExpectedRevision int64 `json:"expectedRevision"`
}

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	Status *ListTasksParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListTasksParamsStatus defines parameters for ListTasks.
type ListTasksParamsStatus string

// ListTramitesParams defines parameters for ListTramites.
type ListTramitesParams struct {
	// Status Filtra los trámites por estado.
	Status *TramiteStatus `form:"status,omitempty" json:"status,omitempty"`
	Page   *string        `form:"page,omitempty" json:"page,omitempty"`
	Limit  *int           `form:"limit,omitempty" json:"limit,omitempty"`
}

// UpdateUserRolesJSONBody defines parameters for UpdateUserRoles.
type UpdateUserRolesJSONBody struct {
	Roles []UpdateUserRolesJSONBodyRoles `json:"roles"`
}

// UpdateUserRolesJSONBodyRoles defines parameters for UpdateUserRoles.
type UpdateUserRolesJSONBodyRoles string

// FireTransitionJSONRequestBody defines body for FireTransition for application/json ContentType.
type FireTransitionJSONRequestBody FireTransitionJSONBody

// CreateTramiteJSONRequestBody defines body for CreateTramite for application/json ContentType.
type CreateTramiteJSONRequestBody = TramiteCreate

// UpdateTramiteJSONRequestBody defines body for UpdateTramite for application/json ContentType.
type UpdateTramiteJSONRequestBody = TramiteUpdate

// SaveDraftProcedureJSONRequestBody defines body for SaveDraftProcedure for application/json ContentType.
type SaveDraftProcedureJSONRequestBody = ProcedureDefinition

// UpdateUserRolesJSONRequestBody defines body for UpdateUserRoles for application/json ContentType.
type UpdateUserRolesJSONRequestBody UpdateUserRolesJSONBody

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3HzZbhw5luivEHHvQxcmlJla3NUlYDCjkmy3CmVbI8tlYGxjwAyeTNFmkFEkI1uykR/jD6iHQb3Nq35s",
	"cEjGlrHkYstyD2DAqQguZ+fZGJ+iRKWZkiCtiY4/RRnVNAUL2v11Sg2cM/zFZXQcZdReR3EkaQrRccRZ",
	"FEcafs+5BhYdW51DHJnkGlKKM2ZKp9TiOGn/ehTFUcolT/M0Ot6PI3ubgX8Fc9DRchlHr5X+MBPqH1ea",
	"ptzuvO3/1zCLjqP/N67wGvu3ZlwtvcQdNZhMSQMO1Z8pu4TfczAW/0qUtCDdT5plgifUciXHmVZTAem/",
	"vDdK4rvNtr3ws87AUi6M35uBSTTPcNXoOHqpBE+4zRmRitAEMksZJYoAQsE4oyPyHzn/ePeZzKiwQKiY",
	"3/2PJBnVd59TsFoRJAhoztQoWsbRqZIzwZOHQOVXSlQGmib87k+JCGhKQJIkQKTwFwFBwFjKEFmbU+GA",
	"fqL0lDMG8gGgfq6I5SCBZKBTbpRB2lKigQr+kWoHLTEFlxy459KCllQ81lrphwHZAMlypgi8hyS3VBOx",
	"CuRzZZ+oXLIHgO+xIBqSXBtVwIT8lorADTcWHHgXWiXAcg2/gTZcDXF+a/CaC3cA6F6hkDIgmRvPUw7S",
	"KoTslaS5vVaafwT2YMy9pgjYghurSC4pSTQwkAmngizuPgu0CwjrbxR/4szdZZEK8WIWHb/ZDvD4U5Rp",
	"VHfLvRUFBMD9WrEKHBWIAXEDwODPhQPb2wnOQFo+4wllyoyiOOIWUrOOjg5dD0y0LA8VqjW9jZbL+inx",
	"poDsXTlMTd9DYqPluy4jpgxh1CpT0t8QoyThMlFaQ2IRSJwWIEFAT3LG7TNAy20dSZuUSTRQC+zE8QRu",
	"aJoJhOJgcvDXvcnh3v6jq/2j48PJ8WTyn1FcHZ6MWtizPIWoBNxYzeU8iqObPaUZ6Oh4fzJZxlGesf4d",
	"jvYmB1f7+8f7j44PDnbZYX+VoBVC9a3b9I2dF7G5jOHol3maUn3bIWB0QbmgUwFX1HxwTzaSFBzdFpHY",
	"OT8CSqptQBQnKzMuuQ32aiMzdFZNWcYRSMSAXWkqjXvYRKS14SrU1yiR+nZj7JGkJ0mx++pqKdUfcCOk",
	"LmMOHiouGlQvXbdJ23XrYHhGteUJz2hwKjcC8qKa1AVl1nFUtEFZHXXOGmwtXNEO97Mu2h2rdABQUa4h",
	"Eivod3I7XpXjiqddBiqOahxsWRaaWKU3RDT2o587V7pD0vimy6gkybXeTm9sSQEP7cCAX+kURMeYFUa5",
	"WKCxbHuRuCRQHfkGBn1GqzBDLZJvTCYNC15I6wbDjaV6S2NkLLW5P3slaugbRJIvcGxp3KJ3HRNtPc7a",
	"ALYwvld0GsfPJrD38DIA1dywxLNG0jq51h5BSghw+vNzOIyaDJVwYy/oHF5p0Tw9r63NzPF4TDM+Ck9H",
	"iUrHATjzbxmdw7/i9D3n6+r60ZprXqL9pjpVZS5E9M5ZK1hwlZsv2LlYYuvdV6hfJ0AbsC6S1p2vlr/n",
	"Xq46eVNqMAQAH/+9hzQTCsdg1AKJH3OIDy6fnJKfjh79OIriFT6xcr+W/GUKhVWvNxphjWpGF3Z/Byrs",
	"dVtQ2ur26iKKo7MXr5/jf4+fXp6cPT7rVjiegrE0zbr8M/x3tf9oKw9wFbFSRaqdulB7rryn3X2aJGXK",
	"ZwOb0HBqN7NXW5hOutXClpoPmxszbgUM+FpNa6rkf4VDvIOxXWYsELEEKkwq9q0TrotDdVeofdwbw+dy",
	"O6LLPqOtlYC1jlnh+FziYLT0BvRujpXbrlwgwBXXUeokRzPqbBmbF9P3YBUBRAszTAwI6rgQPs4MQa8L",
	"P69y+SGXnMY1Y1RaG/ISiAHNXc6nyFNZnrkVU2Bckbe94fTbiNwSytA0k5RDOtXKEMp44txpDwncWJAu",
	"5zB6Kwds24otvXE7JkWuwuWilHNeZMIpUZqDdAlDBFprmHONkBd4oxWtzM3LnCTUOJQsZg8RXkQ1ufuT",
	"8bkijyaTo4MjzNMYICCT3KfwFnwO0nZrtDSWygTakF/CDAKQry7Pye851AL9Fh6sF+axg4KO9w8Ojx6N",
	"U5CGvgczptNk5bzb02HHNa5SE8zTgHqgLVMO0kRxmXDmqSMo0WCy3MH896uriwaAR5PDuKELhwcuOrjx",
	"QdOjn36qZb+PJpNBi7RKQpOnIImAOZ8KIKwmkt3EemUsuDwyuCRmYUggoAct9o86rWkwgwxmNBeIFp2q",
	"3B5PBZUfong7Rq8DuVAkM+bSOQx7Cbf8I8gt2LtiaQpDW56JQbt67Is3cCc6advbmVZpiIF/BTm31/UC",
	"xuq5tmaQVWsHdR0nDgQ3exD8s0ZeYuXU0MkWoXidIB2x+IxjhkDQBHoCOQfG8BCpGOwA0XPFYG2uz68d",
	"e6Rb0KzAP0hSt11P+LeG1x+4ZHVHIsP9GvFpp5coeiLfHc/qm+48yW3X4y7Rc1gUUOFyOHeQZJcBzALv",
	"SpUN6AWVthPtrkrA6vH4hVm3jT3Pto/PNJ3ZKI6yfCq4uf5KEfXCo/o8T6eNuGWQIfUIuWbcSkQHefMb",
	"V6LP7w+S3sIqBWPoHNbHVW6FanwXIC4N2+fRbhF2fDcxyi4q2RavDCTzwXmVskEsZQJC9AvbfSTTqshl",
	"XVYt+PKlDA6HNKH0vnkZIExw6ZplPDy2WXppFw2yyiDUvJZ6EP5YkNzkVHP0UqboI+k51lOVcZV1brhV",
	"hjiJEGBiAiYDTXUjvcEAq9nUkNtQTgRNKHqOM64x+uBzbrHUPeiZbkCSl35wzUnbYNIVDu3Nc9fpUsaq",
	"AajuhHSdPR2muofMV0XEIWBOha+xC0rU1IL0RLwlGL8Yq727CNooCfruD0re5/ruD4b+JBLaqIRTjK3A",
	"kIQvuAAzGipgHZZqvVmDSL32VQugK1TOpcOxZP1FDdRfClCHIDro1L8QEdcpOKBOVVpzi/paMxXa1pai",
	"frlZYa2hpsNumVt4UJxOnQ3Z2ki81txieuYJB8F8Wbq+r6Pp4L49h8lQx1IcNdVx0Ftwrug1X3hbXglR",
	"MbJlEOpaW1v5hdUqiis1YlCqy8rjBLSPvpyArr5UPmTntP7CaWOSp5ngGocQNRV8HpSsNZAmhYVDt44n",
	"XLXHOL0GXTbVNJEPyLQVBLHFrL+poXxZoXlaoBbM1WkdmxcO5vDmZYAsiqMLD0JUY/orVzH4GsLWlyLe",
	"wpgvh8RzZct19nbz9F/fwdibDtjmpGkZrVcGdBt4SEPWq5KM9+pajpiCf6/VPeqpAD+lQ23ci99A8xn3",
	"bTvlmr5NMEyYKiWAbhEUrD0NflHXkpypTm8SHSXTGP4moizlMmRCUSs2r/2bfNrc+sf54dGPR3/78ehw",
	"/rejw/mPmxXawjmDq8UlPZvkKyBvW04EA5Jcc3v7EpkfOiiBatAnuS+bTN1fTwrC/vL6qpU1ulIfQJJf",
	"Xl+FIhCt8px4lju5cuxyS1V4YWXMN01xOVMtBfCdeTP6EZdFDmoaikshpWvyqeHGhpTwHIwtDvGZyN8r",
	"08iNFhnj0Vv52FjqPL+ksqyYJc0N9mEG+6mkyVNf1sKVuLFcou9oeeZXTgQHacGM3soLnCHUHD3JXHKU",
	"Qs4owzUNn+cgSabvPieWJ9QEGnHJcuQrJbcEjL37LBnVYIr8rDl+KwnZI2+KpPa7vxR1RDx9rabJB9Aj",
	"DnY2Uno+ZioZX9tUjPUsweE/hOlnKsG0o/VI1hZRiRnh/pkvRtKM7y0O9tQCLS384wdyS95UycDBeePF",
	"wThRGsY0SVQurfkhoHhycY6/XrrRZHHgQXqa3/3hqcC4gbv/diQ+uTh3j948VWouYGW/RKicjebuVbGr",
	"GTPAaBMhxYnPeKKVUTNbzZ1ze51P3YS0eOsQneecgeASzA/kLycfcw3klvwKc5rc/uDy+YInIL1D7E1E",
	"9OwcxT7XolbQVRlIo3KdgGNBmGTGOLZKBEeF4CGSUZksiI6j/dEEx+EyNOPRcXQ4wkex65N2mjhOaOhq",
	"noMLe11HbhEruma8UzcibvR7vwn91thJfFs1XJtEuXigv+e6cE9SLnFgLouCTle57N1K4/XBZLJV2+fG",
	"HU9VE9mqW9rq9zulRqEOGcyxu9DqaHLYt0cJ/bjqWK6bREfIujF88w6RNgEcT3+qXR7eNRhmXBniWmMp",
	"ko0y50pZOkeelH3xxhftPW/Hnzhb9jL4KTj+Rl9I6XUE7qLkmS+8uToFIuhpebSelmWn8lakfBE8TLdV",
	"N81aMt4FRzVkHO48LN81iT1OBOXp6hWJLZaLo0yZDmad4roPxS4U/FLqdpF7nPHT+hnlhYStuHuSW+WB",
	"03jMyiE2r3CryleZ8ad6Lms5nnENu/Mx7ryUspIt6zeVw7WfXiF5wjVUDYRhBzD2Z8VutxKSFd/7JoPE",
	"ArscalNbc2+n0WS9ul6H77hcJc/yAeTe0zLcUfG3Jxj97uT/cXGvw9bAvaZTLriDt18Trsv2pb4DIjQ4",
	"3SPtww7dV0OKpIF3YomhImcY4pJbf32ISJdrRR8URjscInH0aHL4jVGRBTaMI0CuXq/ILJeuB8Q1kVCJ",
	"uDGYa8qou77RlIcG+18iUcizuz9ZLupmL0DjOZ3CEJef3eup4gL6DqKcS2dEitxolVunOW7qbnkEpu6v",
	"Z2rjKs5ukjBZP6F5nWsnJ4T3oF1jHS4gA+dkrQ9v2Fl/3hj5Lfzn+o6bONDF+JCR93l7WvrSW3N5B3da",
	"9oLQbyYbLPCOgwbKOryD+77/2nvyP6P6Q50bl0D9vg0ROGpnQSqWoDgKuPujOOHuzRt/RnXS4IRPuqSq",
	"2L6fE7a4ztOrBMVFiU0i1qImWXGj6mOqiq1D5deHCly7Lyp1ODBUA30YRbOtrQfYGprVa5xd7d30927x",
	"eqPA9UlG51xSRutZOEyW7ZFfQ4xuqbRgiLn7UyiycO3kgI4CRtNYcvGXCIsZCWq0u3OIQymD9O6zISav",
	"Qu+p0joMua2t5Us2jbVc2pYbq2srWsWUccm+cqrv7uwQ4YIaLSluEuUJF9ZlBk1FAZIpHdoT3f3IzcR+",
	"qwpEtzLhNYMVVWpEkO7eAVEZTYpm/uzuM7LQtQEaTAUYKGtBo670dPfGgqfcdivxwaTWXrmPDZXrjOu9",
	"+UDtSmzXfdIByd7ZD/oKbs0y3kjji6peXdNPqaVCzX2CJZxcTaRdyc0CoYUfZFwCXiuBBKhUKRxQ7npz",
	"1Uohc1g05N9fG0movfss1Fw1iei0M+UmVYZImoC++xzS/b6h1xVasTEjB+a/RuBdtlw2r36TBU3u/lAt",
	"7fWF6cDrLwi/N5Ekt9VmgfL+1968M0dUZ0tZ4IUbbpUJHsUGglj7vsbujv/WsfnBwfoZq9fntzoTkTiV",
	"gnTqR/0cLPO2DNDPaHs6Z+55XdDW+XkVR9BgSspUTJyVQfOrwSotqf6WNL8///Kxx3ANvePeaLiXrJNv",
	"oUdn1Z0UUWHwHdA4/tQdz66h8qALc37WRDO+x0/5YOxEbXLd5rlv8fgmZttv9a3zmwPiVtoF/4kd/tFd",
	"d/JW26XVvnPTvW2W5/5t/TPFXFy7rb0fh+av7YsO7W9i9ScKTvwmOx0dZajz3Zl8j5VLgbdI3hdshnpd",
	"UQO/P5K/tFT3VFr3v03pjkue8JJv91aIOHfb+DKrT+gkPGeUUak25kfZazaUr74oWibLrvmew3oYy/bn",
	"n75USLtPyGbsUCYfvlIluksUB+g69t2kA9Q9wwH3QdnvyGAUrCmSOsW10opP98idOMryLjtBF9BB+6/v",
	"i3TefNrYI/kn5/zTnGpGd+D8Wp0ah07u+z1Ngu37J9TP0vnasQ1hUVxL2+FCaHWlbd31g9ou3W0JrQ9Z",
	"6vIiNaanXz/Zk2CLL+/5dk8Q5NlvF9vJqfdBNbktDgy9sZTmJnyYtbdK8sqN+BaVCl/8XV+peFUk/8JN",
	"Bdfe9q3iiB3KG2Wysmi4rS4XFGzxRK6xJJQOi0bvB6gdDsW/CO6l8oWar9M3VGJaSkr5uZTQ2D5017ch",
	"MXGUS/57Dud+JXc8dXw1xDx4K1Ffs8OrorehCrP/b2TbTgqENHEcIHOhpsWnTHLZ0d1Q6sXSC0B3augZ",
	"N6kiSmPHuktSuo9rlB+QKJvAR2XntG8X33dnZ9irVYYq6wKosNzm/rsrK6WWUv+KaH0Zry507r5bgV34",
	"vY0r5Sq+m6O9xmNfdAi6uFBuqaJNqDa/aCtqLeDdt9DJEPrTpu7iqWsajosa7O1K10Nt7eroaC//tLjy",
	"0KJVYfxqC3mmLt8t/3cA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
