// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Tramite struct {
	ID                   int64
	Name                 string
	Description          string
	ProcedureDescription sql.NullString
	Type                 string
	Status               string
	CreatedAt            string
	UpdatedAt            string
}
