// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

const createTramite = `-- name: CreateTramite :one
INSERT INTO tramites (name, description, procedure_description, type) -- status has its default value set in the database
VALUES (?, ?, ?, ?)
RETURNING id, name, description, procedure_description, type, status, created_at, updated_at
`

type CreateTramiteParams struct {
	Name                 string
	Description          string
	ProcedureDescription sql.NullString
	Type                 string
}

func (q *Queries) CreateTramite(ctx context.Context, arg CreateTramiteParams) (Tramite, error) {
	row := q.db.QueryRowContext(ctx, createTramite,
		arg.Name,
		arg.Description,
		arg.ProcedureDescription,
		arg.Type,
	)
	var i Tramite
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProcedureDescription,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTramite = `-- name: DeleteTramite :execrows
DELETE FROM tramites
WHERE id = ?
`

func (q *Queries) DeleteTramite(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTramite, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTramite = `-- name: GetTramite :one
SELECT id, name, description, procedure_description, type, status, created_at, updated_at
FROM tramites
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetTramite(ctx context.Context, id int64) (Tramite, error) {
	row := q.db.QueryRowContext(ctx, getTramite, id)
	var i Tramite
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProcedureDescription,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTramites = `-- name: ListTramites :many
SELECT id, name, description, procedure_description, type, status, created_at, updated_at
FROM tramites
`

func (q *Queries) ListTramites(ctx context.Context) ([]Tramite, error) {
	rows, err := q.db.QueryContext(ctx, listTramites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tramite
	for rows.Next() {
		var i Tramite
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ProcedureDescription,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
