//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type CaseTasks struct {
	ID              int64 `sql:"primary_key"`
	CaseID          int64
	TransitionID    string
	TransitionLabel string
	Role            string
	AssigneeID      *int64
	Status          string
	CreatedAt       string
	FinishedAt      *string
}
