//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type ProcedureVersions struct {
	ID            int64 `sql:"primary_key"`
	TramiteID     int64
	VersionNumber *int64
	Status        string
	Definition    string
	CreatedAt     string
	UpdatedAt     string
	PublishedAt   *string
}
