// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"
)

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_roles (user_id, role_id)
SELECT ?,
    id
FROM roles
WHERE name = ? ON CONFLICT DO NOTHING
`

type AssignRoleToUserParams struct {
	UserID int64
	Name   string
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.ExecContext(ctx, assignRoleToUser, arg.UserID, arg.Name)
	return err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT id,
    name
FROM roles
    LEFT JOIN user_roles ON roles.id = user_roles.role_id
WHERE user_roles.user_id = ?
`

func (q *Queries) GetUserRoles(ctx context.Context, userID int64) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (name, sub, email, email_verified)
VALUES (?, ?, ?, ?) ON CONFLICT(email) DO
UPDATE
SET sub = excluded.sub,
    name = excluded.name,
    email_verified = excluded.email_verified
RETURNING id, name, sub, email, email_verified, created_at
`

type UpsertUserParams struct {
	Name          string
	Sub           string
	Email         string
	EmailVerified int64
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.Name,
		arg.Sub,
		arg.Email,
		arg.EmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sub,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const userWithRoleExists = `-- name: UserWithRoleExists :one
SELECT EXISTS(
        SELECT 1
        FROM user_roles
            LEFT JOIN roles
        WHERE roles.name = ?
    )
`

func (q *Queries) UserWithRoleExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userWithRoleExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
