// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/nullable"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for HealthStatus.
const (
	DEGRADED HealthStatus = "DEGRADED"
	DOWN     HealthStatus = "DOWN"
	UP       HealthStatus = "UP"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case DEGRADED:
		return true
	case DOWN:
		return true
	case UP:
		return true
	default:
		return false
	}
}

// Defines values for TramiteStatus.
const (
	Archived  TramiteStatus = "archived"
	Draft     TramiteStatus = "draft"
	Published TramiteStatus = "published"
)

// Valid indicates whether the value is a known member of the TramiteStatus enum.
func (e TramiteStatus) Valid() bool {
	switch e {
	case Archived:
		return true
	case Draft:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// CollectionBase defines model for CollectionBase.
type CollectionBase struct {
	NextPageUrl     nullable.Nullable[string] `json:"next_page_url"`
	PreviousPageUrl nullable.Nullable[string] `json:"previous_page_url"`
}

// ErrorDetail El formato se adecúa al ejemplo brindado en la sección 3 del RFC 9457
type ErrorDetail struct {
	Detail  string `json:"detail"`
	Pointer string `json:"pointer"`
}

// Health defines model for Health.
type Health struct {
	Status    HealthStatus `json:"status"`
	Timestamp time.Time    `json:"timestamp"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// ProblemDetails Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type ProblemDetails struct {
	// Detail Contiene una explicación legible para humanos, específica de esta ocurrencia del problema. Si está presente, debería centrarse en ayudar al cliente a corregir el problema, en lugar de proporcionar información de depuración. Los consumidores NO DEBERÍAN analizar (parsear) el miembro "detail" para obtener información; las extensiones son una forma más adecuada y menos propensa a errores de obtener dicha información.
	Detail *string `json:"detail,omitempty"`

	// Instance Referencia URI que identifica la ocurrencia específica del problema. Cuando es desreferenciable, el objeto de detalles de problema PUEDE obtenerse desde ella. Puede ser relativa o absoluta. No suele incluirse en la API de Tunkunia y se conserva en el esquema para obedecer el RFC 9457
	Instance *string `json:"instance,omitempty"`

	// Status Código de estado HTTP generado por el servidor de origen para esta ocurrencia del problema. Se incluye por conveniencia; DEBE coincidir con el código de estado de la respuesta HTTP real.
	Status *int32 `json:"status,omitempty"`

	// Title Contiene un resumen corto y legible por humanos del tipo de problema. Es de carácter consultivo y se incluye únicamente para los usuarios que no conocen y no pueden descubrir la semántica del URI del campo "type".
	Title *string `json:"title,omitempty"`

	// Type Referencia URI (RFC 3986) que identifica el tipo de problema. Al ser desreferenciada (si es una URI http/https), DEBERÍA ofrecer documentación legible por humanos sobre el tipo de problema. Si está ausente, se asume el valor "about:blank", que remite al código de estado HTTP como único identificador del tipo de problema. En el caso de Tunkunia se usan rutas relativas a modo de identificador y eventual creación de sitio de documentación de problemas específicos
	Type *string `json:"type,omitempty"`
}

// Tramite defines model for Tramite.
type Tramite struct {
	CreatedAt            *time.Time     `json:"createdAt,omitempty"`
	CreatedBy            *int           `json:"createdBy,omitempty"`
	Description          *string        `json:"description,omitempty"`
	Id                   int            `json:"id"`
	Name                 string         `json:"name"`
	ProcedureDescription *string        `json:"procedureDescription,omitempty"`
	Status               *TramiteStatus `json:"status,omitempty"`
	Type                 *string        `json:"type,omitempty"`
	UpdatedAt            *time.Time     `json:"updatedAt,omitempty"`
}

// TramiteCollection defines model for TramiteCollection.
type TramiteCollection struct {
	Data            []Tramite                 `json:"data"`
	NextPageUrl     nullable.Nullable[string] `json:"next_page_url"`
	PreviousPageUrl nullable.Nullable[string] `json:"previous_page_url"`
}

// TramiteCreate defines model for TramiteCreate.
type TramiteCreate struct {
	Description          *string                   `json:"description,omitempty"`
	Name                 string                    `json:"name"`
	ProcedureDescription nullable.Nullable[string] `json:"procedureDescription,omitempty"`
	Type                 *string                   `json:"type,omitempty"`
}

// TramiteStatus defines model for TramiteStatus.
type TramiteStatus string

// TramiteUpdate defines model for TramiteUpdate.
type TramiteUpdate struct {
	Description          *string                   `json:"description,omitempty"`
	Name                 *string                   `json:"name,omitempty"`
	ProcedureDescription nullable.Nullable[string] `json:"procedureDescription,omitempty"`
	Status               *TramiteStatus            `json:"status,omitempty"`
	Type                 *string                   `json:"type,omitempty"`
}

// BadRequest Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type BadRequest = ProblemDetails

// Forbidden Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type Forbidden = ProblemDetails

// InternalError Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type InternalError = ProblemDetails

// NotFound Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type NotFound = ProblemDetails

// Unauthorized Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type Unauthorized = ProblemDetails

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// Detail Contiene una explicación legible para humanos, específica de esta ocurrencia del problema. Si está presente, debería centrarse en ayudar al cliente a corregir el problema, en lugar de proporcionar información de depuración. Los consumidores NO DEBERÍAN analizar (parsear) el miembro "detail" para obtener información; las extensiones son una forma más adecuada y menos propensa a errores de obtener dicha información.
	Detail *string `json:"detail,omitempty"`

	// Errors Lista de errores de validación identificados. El formato se adecúa al ejemplo brindado en la sección 3 del RFC 9457
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// Instance Referencia URI que identifica la ocurrencia específica del problema. Cuando es desreferenciable, el objeto de detalles de problema PUEDE obtenerse desde ella. Puede ser relativa o absoluta. No suele incluirse en la API de Tunkunia y se conserva en el esquema para obedecer el RFC 9457
	Instance *string `json:"instance,omitempty"`

	// Status Código de estado HTTP generado por el servidor de origen para esta ocurrencia del problema. Se incluye por conveniencia; DEBE coincidir con el código de estado de la respuesta HTTP real.
	Status *int32 `json:"status,omitempty"`

	// Title Contiene un resumen corto y legible por humanos del tipo de problema. Es de carácter consultivo y se incluye únicamente para los usuarios que no conocen y no pueden descubrir la semántica del URI del campo "type".
	Title *string `json:"title,omitempty"`

	// Type Referencia URI (RFC 3986) que identifica el tipo de problema. Al ser desreferenciada (si es una URI http/https), DEBERÍA ofrecer documentación legible por humanos sobre el tipo de problema. Si está ausente, se asume el valor "about:blank", que remite al código de estado HTTP como único identificador del tipo de problema. En el caso de Tunkunia se usan rutas relativas a modo de identificador y eventual creación de sitio de documentación de problemas específicos
	Type *string `json:"type,omitempty"`
}

// TramiteCreateBody defines model for TramiteCreateBody.
type TramiteCreateBody = TramiteCreate

// TramiteUpdateBody defines model for TramiteUpdateBody.
type TramiteUpdateBody = TramiteUpdate

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// ListTramitesParams defines parameters for ListTramites.
type ListTramitesParams struct {
	// Status Filter trámites by status
	Status *TramiteStatus `form:"status,omitempty" json:"status,omitempty"`
	Page   *string        `form:"page,omitempty" json:"page,omitempty"`
	Limit  *int           `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateTramiteJSONRequestBody defines body for CreateTramite for application/json ContentType.
type CreateTramiteJSONRequestBody = TramiteCreate

// UpdateTramiteJSONRequestBody defines body for UpdateTramite for application/json ContentType.
type UpdateTramiteJSONRequestBody = TramiteUpdate

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFrbbhs5k36VQs9eJF5Fkk//TjRYLBzbyXiQg9d2doCNjd8UWZaYYZMdHjRWAj3CPoQfIFdzN7d6sUWR",
	"3VK31I7j/JlkAAOWWjwUq7766sD+kHGTF0aj9i4bfMgsvgvo/BMjJMYHZ5bl0uO+RebxiRFTesiN9qg9",
	"fWRFoSRnXhrde+uMpmeOjzFn9OnfLF5lg+yH3nKXXvrV9RorZ7PZrBN3lxZFNvA24KxT7f66EH/R7mnl",
	"1t3jE1cY7ZImnjBxkrTzCSEKa4YK83+/nzDHadYBeiaVS9IIdNzKglbNBtmpUZJLHwRoA4xj4ZlgYABJ",
	"CiEF68J/B/l+fgNXTHkEpkbzPzUUzM5vcvTWQLSslcJ0s1kne2rsUAqB+juc5aUBL1EjFGhz6YwjMRlY",
	"ZEq+ZxbQeQauOjBJe6Q9Ws3UobXGfh+JHUIRhAF8izx4ZkGtyPjS+KcmaPEdxDtUYJEH60wlEhOGgILX",
	"0hG6O9lrzYIfGyvfo/huChwzKKyZSOcNcKMhaAZKsQnCZH6jCMQk6v8w+kgTv9zcTKlXV9ngzf3k7nzI",
	"CmsKtL4kPyQB4qfmcZ5LgqhAiAPQ0cdJFJvL+R8apEDt5ZXkTBjXhUMFV8bmzEctMIF8/icDpghMeaEM",
	"DK3UgmyGOuIKeVpnGwQqOHm6D493dv/jXGedTHrM3V0GiYpLxyKN+mmB2SBj1rJpNls+MMO3yH02u2ix",
	"2HPjQDBPzlmazIEzGqTmxlrk3ri4VLklSbRvlEJO858wh/SkqU2N1/6fBRvhP4NVUb3XLC8USTL2vnCD",
	"Xo8Vsls+7XKT94JD6/6L5vzndtbJdFCKDWkGMfTiHM5bqUd00sLiRJrgvnybzbu3aYSKNyvHapPhYk3j",
	"naxuojV8fSXARGHqFhCL/dY1ZySRbMtvK8ct11jOaDvdz8iUH69DwHnmQ3ItHXJa7vVx1skOXv36kv4d",
	"PjvZOzg8qC25FNDLnAJDXjRNutXf+sejPv2dbe4OtvuDfv9/s06W1JcNMgrvj2hudpcdS9nqO7UdbYU0",
	"1mz3avgWvSFGoCFKJXYoZ5GpYmCuTNSFUwSHVsbYF1kRFXhZxBVyFNLA+a2kd5514cwI40AZB7nEfGhL",
	"P311vH/06uXe88PTn5o/suAoaXAUH2IY1kRdxkJhLAi8ItcGx9TEgDBakHQgtZDvAgJeF2r+keJLTmt0",
	"4TigQB0jtoXCYrn0cjMhuTSakRYeEF9ee9SOoPowicWNdiGXIrLoweGTw5cgR9pYCrB1qXmYmoVakrya",
	"gojUXIqm3tAVyEvy7UbOvM0JmobbNzqlJRSW6KSSl3SucCSHClOaMg4508Z10j7zj7RRDAUUEgwP1qLm",
	"kkVHLG3FunAqacD8ZqGkDggcop1/ZMBRe8usQ/JmNg2CWfJ1riQNBDqdtTiSFmpLdqLrhxEjo9HTwtio",
	"agtSR/Qn2QWCwCLY9LULz1eV/vJV1PvJ/P/2XgLTZQ72oCCBmH1Ie5ZWgPNSd+dZUoUZetTY3PAnUMxV",
	"djYaExpJpXEM5PMbFxktUAI7hRx1ijEFaseA1UNqtb6QfMwauyS7LlngNABnLoLDU8YrPUZM8PkfQo4M",
	"7Pb7O1s7BJmoZR6iymEiR6TirIVupHaeaY7rODnBKyxt/PrkCMgvlvGe2LgGgiZG6oDYD0wTf9NBnV0s",
	"OVTYIZWbBYuIGotU0+H49eHBYaUfR4McQVApVvokcQpYVMzLCdUJbOiMCp51gVKxgIqcmqsgS9gpBnvH",
	"R7THWdC/BS3JNi4q0aGdMBqDCtC9C7R/aX4UyDHCspGjLO3Si5pmvc2t7Z3dXk4mfouux4a8ztHBykeV",
	"ClqNsQwbKy5bmrd0P2Hg57OzYxiRVugbURoq0sWE0B4xZcnm6QB3uGypoinGdbjRE9QyjvwpukxFP9JW",
	"/MPX5BFIqqU6MsTdonxU6awgeKe/XVOI1H57K+tkObuWOcXJ3cePO1kudfq20+8vlEQxeIQ2RUiv8JO8",
	"RoKEHDUxijcwXTKbsRWxRS1UTLvUxmEEIKd6knu0iUOUlxOTgFKpav6nljyFh6RkovHgArPSuOgskbe1",
	"4ahhSl+KFENI6DC0MlVWmM9vtK/chvyM/nOWF0RDdPbzbJUEXjuPsT7GWFF6yWXBSI5kDlyjiG4b1tID",
	"UuIVC4qswYYm+MFQMf1b1vk0GTwgP9h+/OM/Hq7yQqtS9yI2mwwgGDxwFC0iadKilLX2Yur6sLPgajBX",
	"NjqfMJxM6ldjVc2izgwttkuwiEtlWtCJCSeBhManQHte18B51olHsxhJlrWBPoKcm9wkNJhGPWRvA1jy",
	"oNJECxZyCMExDTZ45haM5oBBbpJ/NRefAk5Q+0CCWVwGQSe9THza1FdNBleja+NWmawc5XpSx1LvEZde",
	"vkd9DyKbtaSTZR9qPVXmsS8m9nxbvrv9aHP3bHPnfvlup1rzybSx5k4bmTRgXhfgrIqvCkdMlT5e5gJJ",
	"pVOgbMV5myyM1hmdMp23wc4/ijJhYs5wyXhKEricSIWu1SOlaEiw2SauZjk25TzS8QALKx/X5PilkiNr",
	"rSENRxEsHtymgkNVMVpM4ogVR2XCGgsKJ6lajiZRWGaKlNHWWwSkAE6QnkLaEC1ERV5JSpOEHEnPVPfT",
	"0fAzGpynaXCN2FpMKRBOSpO1bRhik/QWKO486m+dbW4ONncHW1tfWHpJkZUmvLjdRZbthc/v8Ky0JNY7",
	"PIL52DD6rLZK5attLZVGiUyLXrS0WTrNdvq606943ZolvgHM7+yxrONoT1Bq4rwlbjZ3WvsuQ5+uNQmE",
	"ZVeeCrkwVNKNkeDCLB/LCQpaaSlKNXJN6ma//4sV//XU+C968Z2hhbZAHqz001NarLzEQGbR7oXUnBnG",
	"b08rh/3l17O1BOdQU7Y3NcFCrQsBv/x6Bt78FsNflJW2TssttU85S+oGU+22npkeIFMOfpd+DH6MoOQV",
	"8ilXCOYKzhfs5M4zePDMTNBqittwXGncPQSmBU2VFpiL4YQywGP0VoJGD3iNPER5nbeBe5rUPdfn+ocf",
	"foC9siGeDnQSFLrBuX4EGxvHFcw2Nha5ogNmibI5OhcTrOEUmJ4ajfAg5r5C6hEwbfQ0N8HB5YgS/kuI",
	"rcWH3bTwAaFzYyOKvbGxVyJ4bRcyKveK4mj6iAK8KQ96GYO4sZdgLDANl4y87zIlw0py1Kn3mhCbvTgi",
	"m8ZO6KL9GWttEyzHrrGjXjnJ9Wjsso7I9plnyoxeGBEU7h0fZZ1sgtYl2212+zSWlmKFzAbZdrff3SYf",
	"ZX4codbjaX5vvGgGjjCGEHK8qPUjkQ2yZ+jLncqu4cq921a//9Vu/codWvrdZ2NMdSJHkA6SzNNoqVJc",
	"PQIdQ7qa0sl3+ju37bYQv7e4FJp1st3+9rc/R9DVSWLiPbJMoGiQQzZ4c9HJXMhzZqfZIDtlKgh4Mf9D",
	"BBW5nI0ccXBpxQuauzCtT/TkasZd7YYue2qqujVZor1gI6mZoGyb/OMZ+Yzb2IDfpVJgtKLSEuFywfuX",
	"EAN16U77yRMWE2hschLzu4YYClyvihNpJjBl9MhJSkyrRYEy0HLJGMoaC+IE7dSPpR4lF2uC97l0/qxS",
	"AoHfshw9WhdTk6YunkpFXLo8/XAKi6azpBHvAtpplQoNlh3pe11pV7GCkp22VQs2wsaaa6GkfZ6SufSN",
	"iYsSeaulHzG7+Av9eD0lbHGFvRJeRJ+EPQorC+V3kw9v3u3DjavT6Mf9uyc1b6xX/K0Zht9czDofZg0f",
	"jPeLFhYRsOaGJVVmF/HOxrW43DHaVJov2y7caLBGxaJjkauV/QLWrJN1wIlxNZBiWZf7+Y0yo0b/xKV2",
	"ci5dbhxoxtHOb3RqhpXtL/JBKnFSjyfZHi0EXVY9MpeovYEJ4/OPZs29Up5c5d2d2usp09ttUHuDpbf+",
	"+spsDZabXxuWbWDcryt5UXjhNZWKLGHxM2BVewflS+G7k8LQpyctXw+hGVtbd89YvbW/C/INvJNylnBv",
	"RXtb1Ol9kGKWHEBhyuqb8DmIz+vwaRh+Z915lpYhuqPQ1AHNBCt7Xt5Yzey31P39soz7KP0wnfAOvXdu",
	"TdpuVWv/W/hT7XJVLU/wN9DxKpe/Ki+x7tDyJzOHo4PmMct0gVLtZXyOTZTmO2wtUb4Rnwvm+XjduKlI",
	"/tdZt/ba3uz7oGThzoz7EK82halIN95R/M2Z9741xl9P1S+MiL32u+g6rmkn7Xg+wAkqU8RyPo1q1KiD",
	"Xk8ZztTYOD/4sf9jv8cK2Ztsxv5ds5T9QGNm1e+dbMJsvESNIBsv8qPqKseX1wpdbvK1VsfPhnJEEIYy",
	"pOrqjure2Wx2Mfv/AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
