// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"time"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for HealthStatus.
const (
	DEGRADED HealthStatus = "DEGRADED"
	DOWN     HealthStatus = "DOWN"
	UP       HealthStatus = "UP"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case DEGRADED:
		return true
	case DOWN:
		return true
	case UP:
		return true
	default:
		return false
	}
}

// Defines values for TramiteStatus.
const (
	Archived  TramiteStatus = "archived"
	Draft     TramiteStatus = "draft"
	Published TramiteStatus = "published"
)

// Valid indicates whether the value is a known member of the TramiteStatus enum.
func (e TramiteStatus) Valid() bool {
	switch e {
	case Archived:
		return true
	case Draft:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// CollectionBase defines model for CollectionBase.
type CollectionBase struct {
	NextPageUrl     *string `json:"next_page_url"`
	PreviousPageUrl *string `json:"previous_page_url"`
}

// Health defines model for Health.
type Health struct {
	Status    HealthStatus `json:"status"`
	Timestamp time.Time    `json:"timestamp"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// ProblemDetails Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type ProblemDetails struct {
	// Detail Contiene una explicación legible para humanos, específica de esta ocurrencia del problema. Si está presente, debería centrarse en ayudar al cliente a corregir el problema, en lugar de proporcionar información de depuración. Los consumidores NO DEBERÍAN analizar (parsear) el miembro "detail" para obtener información; las extensiones son una forma más adecuada y menos propensa a errores de obtener dicha información.
	Detail *string `json:"detail,omitempty"`

	// Instance Referencia URI que identifica la ocurrencia específica del problema. Cuando es desreferenciable, el objeto de detalles de problema PUEDE obtenerse desde ella. Puede ser relativa o absoluta. No suele incluirse en la API de Tunkunia y se conserva en el esquema para obedecer el RFC 9457
	Instance *string `json:"instance,omitempty"`

	// Status Código de estado HTTP generado por el servidor de origen para esta ocurrencia del problema. Se incluye por conveniencia; DEBE coincidir con el código de estado de la respuesta HTTP real.
	Status *int32 `json:"status,omitempty"`

	// Title Contiene un resumen corto y legible por humanos del tipo de problema. Es de carácter consultivo y se incluye únicamente para los usuarios que no conocen y no pueden descubrir la semántica del URI del campo "type".
	Title *string `json:"title,omitempty"`

	// Type Referencia URI (RFC 3986) que identifica el tipo de problema. Al ser desreferenciada (si es una URI http/https), DEBERÍA ofrecer documentación legible por humanos sobre el tipo de problema. Si está ausente, se asume el valor "about:blank", que remite al código de estado HTTP como único identificador del tipo de problema. En el caso de Tunkunia se usan rutas relativas a modo de identificador y eventual creación de sitio de documentación de problemas específicos
	Type *string `json:"type,omitempty"`
}

// Tramite defines model for Tramite.
type Tramite struct {
	CreatedAt            *time.Time     `json:"createdAt,omitempty"`
	CreatedBy            *int           `json:"createdBy,omitempty"`
	Description          *string        `json:"description,omitempty"`
	Id                   int            `json:"id"`
	LegalFramework       *[]string      `json:"legalFramework,omitempty"`
	Name                 string         `json:"name"`
	ProcedureDescription *string        `json:"procedureDescription,omitempty"`
	Status               *TramiteStatus `json:"status,omitempty"`
	Type                 *string        `json:"type,omitempty"`
	UpdatedAt            *time.Time     `json:"updatedAt,omitempty"`
}

// TramiteCollection defines model for TramiteCollection.
type TramiteCollection struct {
	Data            []Tramite `json:"data"`
	NextPageUrl     *string   `json:"next_page_url"`
	PreviousPageUrl *string   `json:"previous_page_url"`
}

// TramiteCreate defines model for TramiteCreate.
type TramiteCreate struct {
	Description          *string   `json:"description,omitempty"`
	LegalFramework       *[]string `json:"legalFramework,omitempty"`
	Name                 string    `json:"name"`
	ProcedureDescription *string   `json:"procedureDescription,omitempty"`
	Type                 string    `json:"type"`
}

// TramiteStatus defines model for TramiteStatus.
type TramiteStatus string

// TramiteUpdate defines model for TramiteUpdate.
type TramiteUpdate struct {
	Description          *string        `json:"description,omitempty"`
	LegalFramework       *[]string      `json:"legalFramework,omitempty"`
	Name                 *string        `json:"name,omitempty"`
	ProcedureDescription *string        `json:"procedureDescription,omitempty"`
	Status               *TramiteStatus `json:"status,omitempty"`
	Type                 *string        `json:"type,omitempty"`
}

// BadRequest Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type BadRequest = ProblemDetails

// Forbidden Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type Forbidden = ProblemDetails

// NotFound Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type NotFound = ProblemDetails

// Unauthorized Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type Unauthorized = ProblemDetails

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// Detail Contiene una explicación legible para humanos, específica de esta ocurrencia del problema. Si está presente, debería centrarse en ayudar al cliente a corregir el problema, en lugar de proporcionar información de depuración. Los consumidores NO DEBERÍAN analizar (parsear) el miembro "detail" para obtener información; las extensiones son una forma más adecuada y menos propensa a errores de obtener dicha información.
	Detail *string `json:"detail,omitempty"`

	// Errors Lista de errores de validación identificados. El formato se adecúa al ejemplo brindado en la sección 3 del RFC 9457
	Errors *[]struct {
		Detail  string `json:"detail"`
		Pointer string `json:"pointer"`
	} `json:"errors,omitempty"`

	// Instance Referencia URI que identifica la ocurrencia específica del problema. Cuando es desreferenciable, el objeto de detalles de problema PUEDE obtenerse desde ella. Puede ser relativa o absoluta. No suele incluirse en la API de Tunkunia y se conserva en el esquema para obedecer el RFC 9457
	Instance *string `json:"instance,omitempty"`

	// Status Código de estado HTTP generado por el servidor de origen para esta ocurrencia del problema. Se incluye por conveniencia; DEBE coincidir con el código de estado de la respuesta HTTP real.
	Status *int32 `json:"status,omitempty"`

	// Title Contiene un resumen corto y legible por humanos del tipo de problema. Es de carácter consultivo y se incluye únicamente para los usuarios que no conocen y no pueden descubrir la semántica del URI del campo "type".
	Title *string `json:"title,omitempty"`

	// Type Referencia URI (RFC 3986) que identifica el tipo de problema. Al ser desreferenciada (si es una URI http/https), DEBERÍA ofrecer documentación legible por humanos sobre el tipo de problema. Si está ausente, se asume el valor "about:blank", que remite al código de estado HTTP como único identificador del tipo de problema. En el caso de Tunkunia se usan rutas relativas a modo de identificador y eventual creación de sitio de documentación de problemas específicos
	Type *string `json:"type,omitempty"`
}

// TramiteCreateBody defines model for TramiteCreateBody.
type TramiteCreateBody = TramiteCreate

// TramiteUpdateBody defines model for TramiteUpdateBody.
type TramiteUpdateBody = TramiteUpdate

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// ListTramitesParams defines parameters for ListTramites.
type ListTramitesParams struct {
	// Status Filter trámites by status
	Status *TramiteStatus `form:"status,omitempty" json:"status,omitempty"`
	Page   *string        `form:"page,omitempty" json:"page,omitempty"`
	Limit  *int           `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateTramiteJSONRequestBody defines body for CreateTramite for application/json ContentType.
type CreateTramiteJSONRequestBody = TramiteCreate

// UpdateTramiteJSONRequestBody defines body for UpdateTramite for application/json ContentType.
type UpdateTramiteJSONRequestBody = TramiteUpdate
