// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Tramite struct {
	ID                   int64
	Name                 string
	Description          string
	ProcedureDescription string
	Type                 string
	Status               string
	CreatedAt            string
	UpdatedAt            string
}

type User struct {
	ID            int64
	Name          string
	Sub           string
	Email         string
	EmailVerified int64
	CreatedAt     string
	UpdatedAt     string
}

type UserRole struct {
	UserID int64
	Role   string
}
