// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTramite = `-- name: CreateTramite :one
INSERT INTO tramites (name, description, procedure_description, type) -- status has its default value set in the database
VALUES (?, ?, ?, ?)
RETURNING id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
`

type CreateTramiteParams struct {
	Name                 string
	Description          string
	ProcedureDescription string
	Type                 string
}

// CreateTramite
//
//	INSERT INTO tramites (name, description, procedure_description, type) -- status has its default value set in the database
//	VALUES (?, ?, ?, ?)
//	RETURNING id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
func (q *Queries) CreateTramite(ctx context.Context, db DBTX, arg CreateTramiteParams) (Tramite, error) {
	row := db.QueryRowContext(ctx, createTramite,
		arg.Name,
		arg.Description,
		arg.ProcedureDescription,
		arg.Type,
	)
	var i Tramite
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProcedureDescription,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentVersionID,
	)
	return i, err
}

const deleteTramite = `-- name: DeleteTramite :execrows
DELETE FROM tramites
WHERE id = ?
`

// DeleteTramite
//
//	DELETE FROM tramites
//	WHERE id = ?
func (q *Queries) DeleteTramite(ctx context.Context, db DBTX, id int64) (int64, error) {
	result, err := db.ExecContext(ctx, deleteTramite, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getInstitution = `-- name: GetInstitution :one
SELECT id, name, acronym, description, logo_url, email, phone, address, website, primary_color, accent_color, updated_at
FROM institution
WHERE id = 1
`

// GetInstitution
//
//	SELECT id, name, acronym, description, logo_url, email, phone, address, website, primary_color, accent_color, updated_at
//	FROM institution
//	WHERE id = 1
func (q *Queries) GetInstitution(ctx context.Context, db DBTX) (Institution, error) {
	row := db.QueryRowContext(ctx, getInstitution)
	var i Institution
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Acronym,
		&i.Description,
		&i.LogoUrl,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Website,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.UpdatedAt,
	)
	return i, err
}

const getTramite = `-- name: GetTramite :one
SELECT id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
FROM tramites
WHERE id = ?
LIMIT 1
`

// GetTramite
//
//	SELECT id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
//	FROM tramites
//	WHERE id = ?
//	LIMIT 1
func (q *Queries) GetTramite(ctx context.Context, db DBTX, id int64) (Tramite, error) {
	row := db.QueryRowContext(ctx, getTramite, id)
	var i Tramite
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProcedureDescription,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentVersionID,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
FROM users
WHERE
  id = ?
`

// GetUserById
//
//	SELECT id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
//	FROM users
//	WHERE
//	  id = ?
func (q *Queries) GetUserById(ctx context.Context, db DBTX, id int64) (User, error) {
	row := db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sub,
		&i.Email,
		&i.EmailVerified,
		&i.IsAdmin,
		&i.IsPublicServant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCaseSummariesByUser = `-- name: ListCaseSummariesByUser :many
SELECT c.id, c.tramite_id, t.name AS tramite_name, c.status, c.revision, c.started_at, c.updated_at
FROM cases c
JOIN tramites t ON t.id = c.tramite_id
JOIN case_participants cp ON cp.case_id = c.id
WHERE cp.user_id = ?
ORDER BY c.updated_at DESC
`

type ListCaseSummariesByUserRow struct {
	ID          int64
	TramiteID   int64
	TramiteName string
	Status      string
	Revision    int64
	StartedAt   string
	UpdatedAt   string
}

// ListCaseSummariesByUser
//
//	SELECT c.id, c.tramite_id, t.name AS tramite_name, c.status, c.revision, c.started_at, c.updated_at
//	FROM cases c
//	JOIN tramites t ON t.id = c.tramite_id
//	JOIN case_participants cp ON cp.case_id = c.id
//	WHERE cp.user_id = ?
//	ORDER BY c.updated_at DESC
func (q *Queries) ListCaseSummariesByUser(ctx context.Context, db DBTX, userID int64) ([]ListCaseSummariesByUserRow, error) {
	rows, err := db.QueryContext(ctx, listCaseSummariesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCaseSummariesByUserRow
	for rows.Next() {
		var i ListCaseSummariesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TramiteID,
			&i.TramiteName,
			&i.Status,
			&i.Revision,
			&i.StartedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, case_id, task_id, type, title, created_at, read_at
FROM notifications
WHERE user_id = ?
ORDER BY created_at DESC
`

type ListNotificationsByUserRow struct {
	ID        int64
	CaseID    int64
	TaskID    int64
	Type      string
	Title     string
	CreatedAt string
	ReadAt    sql.NullString
}

// ListNotificationsByUser
//
//	SELECT id, case_id, task_id, type, title, created_at, read_at
//	FROM notifications
//	WHERE user_id = ?
//	ORDER BY created_at DESC
func (q *Queries) ListNotificationsByUser(ctx context.Context, db DBTX, userID int64) ([]ListNotificationsByUserRow, error) {
	rows, err := db.QueryContext(ctx, listNotificationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsByUserRow
	for rows.Next() {
		var i ListNotificationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.TaskID,
			&i.Type,
			&i.Title,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByAssignee = `-- name: ListTasksByAssignee :many
SELECT id, case_id, transition_id, transition_label, role, assignee_id, status, created_at
FROM case_tasks
WHERE assignee_id = ? AND status = ?
ORDER BY created_at DESC
`

type ListTasksByAssigneeParams struct {
	AssigneeID sql.NullInt64
	Status     string
}

type ListTasksByAssigneeRow struct {
	ID              int64
	CaseID          int64
	TransitionID    string
	TransitionLabel string
	Role            string
	AssigneeID      sql.NullInt64
	Status          string
	CreatedAt       string
}

// ListTasksByAssignee
//
//	SELECT id, case_id, transition_id, transition_label, role, assignee_id, status, created_at
//	FROM case_tasks
//	WHERE assignee_id = ? AND status = ?
//	ORDER BY created_at DESC
func (q *Queries) ListTasksByAssignee(ctx context.Context, db DBTX, arg ListTasksByAssigneeParams) ([]ListTasksByAssigneeRow, error) {
	rows, err := db.QueryContext(ctx, listTasksByAssignee, arg.AssigneeID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksByAssigneeRow
	for rows.Next() {
		var i ListTasksByAssigneeRow
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.TransitionID,
			&i.TransitionLabel,
			&i.Role,
			&i.AssigneeID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTramites = `-- name: ListTramites :many
SELECT id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
FROM tramites
ORDER BY name, id
`

// ListTramites
//
//	SELECT id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
//	FROM tramites
//	ORDER BY name, id
func (q *Queries) ListTramites(ctx context.Context, db DBTX) ([]Tramite, error) {
	rows, err := db.QueryContext(ctx, listTramites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tramite
	for rows.Next() {
		var i Tramite
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ProcedureDescription,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTramitesByStatus = `-- name: ListTramitesByStatus :many
SELECT id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
FROM tramites
WHERE status = ?
ORDER BY name, id
`

// ListTramitesByStatus
//
//	SELECT id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
//	FROM tramites
//	WHERE status = ?
//	ORDER BY name, id
func (q *Queries) ListTramitesByStatus(ctx context.Context, db DBTX, status string) ([]Tramite, error) {
	rows, err := db.QueryContext(ctx, listTramitesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tramite
	for rows.Next() {
		var i Tramite
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ProcedureDescription,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassignedCaseSummaries = `-- name: ListUnassignedCaseSummaries :many
SELECT DISTINCT c.id, c.tramite_id, t.name AS tramite_name, c.status, c.revision, c.started_at, c.updated_at
FROM cases c
JOIN tramites t ON t.id = c.tramite_id
JOIN case_tasks ct ON ct.case_id = c.id AND ct.role = 'servant' AND ct.status = 'pending'
LEFT JOIN case_participants cp ON cp.case_id = c.id AND cp.role = 'servant'
WHERE c.status = 'active' AND cp.user_id IS NULL
ORDER BY c.started_at
`

type ListUnassignedCaseSummariesRow struct {
	ID          int64
	TramiteID   int64
	TramiteName string
	Status      string
	Revision    int64
	StartedAt   string
	UpdatedAt   string
}

// ListUnassignedCaseSummaries
//
//	SELECT DISTINCT c.id, c.tramite_id, t.name AS tramite_name, c.status, c.revision, c.started_at, c.updated_at
//	FROM cases c
//	JOIN tramites t ON t.id = c.tramite_id
//	JOIN case_tasks ct ON ct.case_id = c.id AND ct.role = 'servant' AND ct.status = 'pending'
//	LEFT JOIN case_participants cp ON cp.case_id = c.id AND cp.role = 'servant'
//	WHERE c.status = 'active' AND cp.user_id IS NULL
//	ORDER BY c.started_at
func (q *Queries) ListUnassignedCaseSummaries(ctx context.Context, db DBTX) ([]ListUnassignedCaseSummariesRow, error) {
	rows, err := db.QueryContext(ctx, listUnassignedCaseSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnassignedCaseSummariesRow
	for rows.Next() {
		var i ListUnassignedCaseSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.TramiteID,
			&i.TramiteName,
			&i.Status,
			&i.Revision,
			&i.StartedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
FROM users
ORDER BY name, id
`

// ListUsers
//
//	SELECT id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
//	FROM users
//	ORDER BY name, id
func (q *Queries) ListUsers(ctx context.Context, db DBTX) ([]User, error) {
	rows, err := db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sub,
			&i.Email,
			&i.EmailVerified,
			&i.IsAdmin,
			&i.IsPublicServant,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications
SET read_at = COALESCE(read_at, CURRENT_TIMESTAMP)
WHERE id = ? AND user_id = ?
`

type MarkNotificationReadParams struct {
	ID     int64
	UserID int64
}

// MarkNotificationRead
//
//	UPDATE notifications
//	SET read_at = COALESCE(read_at, CURRENT_TIMESTAMP)
//	WHERE id = ? AND user_id = ?
func (q *Queries) MarkNotificationRead(ctx context.Context, db DBTX, arg MarkNotificationReadParams) (int64, error) {
	result, err := db.ExecContext(ctx, markNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAdmin = `-- name: SetAdmin :exec
UPDATE users
SET
  is_admin = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type SetAdminParams struct {
	IsAdmin int64
	ID      int64
}

// SetAdmin
//
//	UPDATE users
//	SET
//	  is_admin = ?,
//	  updated_at = CURRENT_TIMESTAMP
//	WHERE id = ?
func (q *Queries) SetAdmin(ctx context.Context, db DBTX, arg SetAdminParams) error {
	_, err := db.ExecContext(ctx, setAdmin, arg.IsAdmin, arg.ID)
	return err
}

const updateInstitution = `-- name: UpdateInstitution :one
UPDATE institution
SET name = ?,
    acronym = ?,
    description = ?,
    logo_url = ?,
    email = ?,
    phone = ?,
    address = ?,
    website = ?,
    primary_color = ?,
    accent_color = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = 1
RETURNING id, name, acronym, description, logo_url, email, phone, address, website, primary_color, accent_color, updated_at
`

type UpdateInstitutionParams struct {
	Name         string
	Acronym      string
	Description  string
	LogoUrl      string
	Email        string
	Phone        string
	Address      string
	Website      string
	PrimaryColor string
	AccentColor  string
}

// UpdateInstitution
//
//	UPDATE institution
//	SET name = ?,
//	    acronym = ?,
//	    description = ?,
//	    logo_url = ?,
//	    email = ?,
//	    phone = ?,
//	    address = ?,
//	    website = ?,
//	    primary_color = ?,
//	    accent_color = ?,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = 1
//	RETURNING id, name, acronym, description, logo_url, email, phone, address, website, primary_color, accent_color, updated_at
func (q *Queries) UpdateInstitution(ctx context.Context, db DBTX, arg UpdateInstitutionParams) (Institution, error) {
	row := db.QueryRowContext(ctx, updateInstitution,
		arg.Name,
		arg.Acronym,
		arg.Description,
		arg.LogoUrl,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.Website,
		arg.PrimaryColor,
		arg.AccentColor,
	)
	var i Institution
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Acronym,
		&i.Description,
		&i.LogoUrl,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Website,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTramite = `-- name: UpdateTramite :one
UPDATE tramites
SET name = ?,
    description = ?,
    procedure_description = ?,
    type = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
`

type UpdateTramiteParams struct {
	Name                 string
	Description          string
	ProcedureDescription string
	Type                 string
	ID                   int64
}

// UpdateTramite
//
//	UPDATE tramites
//	SET name = ?,
//	    description = ?,
//	    procedure_description = ?,
//	    type = ?,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = ?
//	RETURNING id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
func (q *Queries) UpdateTramite(ctx context.Context, db DBTX, arg UpdateTramiteParams) (Tramite, error) {
	row := db.QueryRowContext(ctx, updateTramite,
		arg.Name,
		arg.Description,
		arg.ProcedureDescription,
		arg.Type,
		arg.ID,
	)
	var i Tramite
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProcedureDescription,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentVersionID,
	)
	return i, err
}

const updateUserAccess = `-- name: UpdateUserAccess :one
UPDATE users
SET
  is_admin = ?,
  is_public_servant = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
`

type UpdateUserAccessParams struct {
	IsAdmin         int64
	IsPublicServant int64
	ID              int64
}

// UpdateUserAccess
//
//	UPDATE users
//	SET
//	  is_admin = ?,
//	  is_public_servant = ?,
//	  updated_at = CURRENT_TIMESTAMP
//	WHERE id = ?
//	RETURNING id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
func (q *Queries) UpdateUserAccess(ctx context.Context, db DBTX, arg UpdateUserAccessParams) (User, error) {
	row := db.QueryRowContext(ctx, updateUserAccess, arg.IsAdmin, arg.IsPublicServant, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sub,
		&i.Email,
		&i.EmailVerified,
		&i.IsAdmin,
		&i.IsPublicServant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserBySub = `-- name: UpsertUserBySub :one
INSERT INTO users(name, sub, email, email_verified)
VALUES (?, ?, ?, ?)
ON CONFLICT DO UPDATE
SET
	sub = excluded.sub,
	email = excluded.email,
	name = excluded.name,
	email_verified = excluded.email_verified,
	updated_at = CURRENT_TIMESTAMP
RETURNING id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
`

type UpsertUserBySubParams struct {
	Name          string
	Sub           string
	Email         string
	EmailVerified int64
}

// UpsertUserBySub
//
//	INSERT INTO users(name, sub, email, email_verified)
//	VALUES (?, ?, ?, ?)
//	ON CONFLICT DO UPDATE
//	SET
//		sub = excluded.sub,
//		email = excluded.email,
//		name = excluded.name,
//		email_verified = excluded.email_verified,
//		updated_at = CURRENT_TIMESTAMP
//	RETURNING id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
func (q *Queries) UpsertUserBySub(ctx context.Context, db DBTX, arg UpsertUserBySubParams) (User, error) {
	row := db.QueryRowContext(ctx, upsertUserBySub,
		arg.Name,
		arg.Sub,
		arg.Email,
		arg.EmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sub,
		&i.Email,
		&i.EmailVerified,
		&i.IsAdmin,
		&i.IsPublicServant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
