// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
)

const createTramite = `-- name: CreateTramite :one
INSERT INTO tramites (name, description, procedure_description, type) -- status has its default value set in the database
VALUES (?, ?, ?, ?)
RETURNING id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
`

type CreateTramiteParams struct {
	Name                 string
	Description          string
	ProcedureDescription string
	Type                 string
}

// CreateTramite
//
//	INSERT INTO tramites (name, description, procedure_description, type) -- status has its default value set in the database
//	VALUES (?, ?, ?, ?)
//	RETURNING id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
func (q *Queries) CreateTramite(ctx context.Context, db DBTX, arg CreateTramiteParams) (Tramite, error) {
	row := db.QueryRowContext(ctx, createTramite,
		arg.Name,
		arg.Description,
		arg.ProcedureDescription,
		arg.Type,
	)
	var i Tramite
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProcedureDescription,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentVersionID,
	)
	return i, err
}

const deleteTramite = `-- name: DeleteTramite :execrows
DELETE FROM tramites
WHERE id = ?
`

// DeleteTramite
//
//	DELETE FROM tramites
//	WHERE id = ?
func (q *Queries) DeleteTramite(ctx context.Context, db DBTX, id int64) (int64, error) {
	result, err := db.ExecContext(ctx, deleteTramite, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTramite = `-- name: GetTramite :one
SELECT id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
FROM tramites
WHERE id = ?
LIMIT 1
`

// GetTramite
//
//	SELECT id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
//	FROM tramites
//	WHERE id = ?
//	LIMIT 1
func (q *Queries) GetTramite(ctx context.Context, db DBTX, id int64) (Tramite, error) {
	row := db.QueryRowContext(ctx, getTramite, id)
	var i Tramite
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProcedureDescription,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentVersionID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
FROM users
WHERE
  email = ?
`

// GetUserByEmail
//
//	SELECT id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
//	FROM users
//	WHERE
//	  email = ?
func (q *Queries) GetUserByEmail(ctx context.Context, db DBTX, email string) (User, error) {
	row := db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sub,
		&i.Email,
		&i.EmailVerified,
		&i.IsAdmin,
		&i.IsPublicServant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
FROM users
WHERE
  id = ?
`

// GetUserById
//
//	SELECT id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
//	FROM users
//	WHERE
//	  id = ?
func (q *Queries) GetUserById(ctx context.Context, db DBTX, id int64) (User, error) {
	row := db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sub,
		&i.Email,
		&i.EmailVerified,
		&i.IsAdmin,
		&i.IsPublicServant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTramites = `-- name: ListTramites :many
SELECT id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
FROM tramites
ORDER BY name, id
`

// ListTramites
//
//	SELECT id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
//	FROM tramites
//	ORDER BY name, id
func (q *Queries) ListTramites(ctx context.Context, db DBTX) ([]Tramite, error) {
	rows, err := db.QueryContext(ctx, listTramites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tramite
	for rows.Next() {
		var i Tramite
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ProcedureDescription,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTramitesByStatus = `-- name: ListTramitesByStatus :many
SELECT id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
FROM tramites
WHERE status = ?
ORDER BY name, id
`

// ListTramitesByStatus
//
//	SELECT id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
//	FROM tramites
//	WHERE status = ?
//	ORDER BY name, id
func (q *Queries) ListTramitesByStatus(ctx context.Context, db DBTX, status string) ([]Tramite, error) {
	rows, err := db.QueryContext(ctx, listTramitesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tramite
	for rows.Next() {
		var i Tramite
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ProcedureDescription,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
FROM users
ORDER BY name, id
`

// ListUsers
//
//	SELECT id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
//	FROM users
//	ORDER BY name, id
func (q *Queries) ListUsers(ctx context.Context, db DBTX) ([]User, error) {
	rows, err := db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sub,
			&i.Email,
			&i.EmailVerified,
			&i.IsAdmin,
			&i.IsPublicServant,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAdmin = `-- name: SetAdmin :exec
UPDATE users
SET
  is_admin = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type SetAdminParams struct {
	IsAdmin int64
	ID      int64
}

// SetAdmin
//
//	UPDATE users
//	SET
//	  is_admin = ?,
//	  updated_at = CURRENT_TIMESTAMP
//	WHERE id = ?
func (q *Queries) SetAdmin(ctx context.Context, db DBTX, arg SetAdminParams) error {
	_, err := db.ExecContext(ctx, setAdmin, arg.IsAdmin, arg.ID)
	return err
}

const updateTramite = `-- name: UpdateTramite :one
UPDATE tramites
SET name = ?,
    description = ?,
    procedure_description = ?,
    type = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
`

type UpdateTramiteParams struct {
	Name                 string
	Description          string
	ProcedureDescription string
	Type                 string
	ID                   int64
}

// UpdateTramite
//
//	UPDATE tramites
//	SET name = ?,
//	    description = ?,
//	    procedure_description = ?,
//	    type = ?,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = ?
//	RETURNING id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
func (q *Queries) UpdateTramite(ctx context.Context, db DBTX, arg UpdateTramiteParams) (Tramite, error) {
	row := db.QueryRowContext(ctx, updateTramite,
		arg.Name,
		arg.Description,
		arg.ProcedureDescription,
		arg.Type,
		arg.ID,
	)
	var i Tramite
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProcedureDescription,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentVersionID,
	)
	return i, err
}

const updateUserAccess = `-- name: UpdateUserAccess :one
UPDATE users
SET
  is_admin = ?,
  is_public_servant = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
`

type UpdateUserAccessParams struct {
	IsAdmin         int64
	IsPublicServant int64
	ID              int64
}

// UpdateUserAccess
//
//	UPDATE users
//	SET
//	  is_admin = ?,
//	  is_public_servant = ?,
//	  updated_at = CURRENT_TIMESTAMP
//	WHERE id = ?
//	RETURNING id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
func (q *Queries) UpdateUserAccess(ctx context.Context, db DBTX, arg UpdateUserAccessParams) (User, error) {
	row := db.QueryRowContext(ctx, updateUserAccess, arg.IsAdmin, arg.IsPublicServant, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sub,
		&i.Email,
		&i.EmailVerified,
		&i.IsAdmin,
		&i.IsPublicServant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users(name, sub, email, email_verified, is_admin, is_public_servant)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (email) DO UPDATE
SET
  sub = excluded.sub,
  name = excluded.name,
  email_verified = excluded.email_verified,
  is_admin = excluded.is_admin,
  is_public_servant = excluded.is_public_servant,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
`

type UpsertUserParams struct {
	Name            string
	Sub             string
	Email           string
	EmailVerified   int64
	IsAdmin         int64
	IsPublicServant int64
}

// UpsertUser
//
//	INSERT INTO users(name, sub, email, email_verified, is_admin, is_public_servant)
//	VALUES (?, ?, ?, ?, ?, ?)
//	ON CONFLICT (email) DO UPDATE
//	SET
//	  sub = excluded.sub,
//	  name = excluded.name,
//	  email_verified = excluded.email_verified,
//	  is_admin = excluded.is_admin,
//	  is_public_servant = excluded.is_public_servant,
//	  updated_at = CURRENT_TIMESTAMP
//	RETURNING id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
func (q *Queries) UpsertUser(ctx context.Context, db DBTX, arg UpsertUserParams) (User, error) {
	row := db.QueryRowContext(ctx, upsertUser,
		arg.Name,
		arg.Sub,
		arg.Email,
		arg.EmailVerified,
		arg.IsAdmin,
		arg.IsPublicServant,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sub,
		&i.Email,
		&i.EmailVerified,
		&i.IsAdmin,
		&i.IsPublicServant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserBySub = `-- name: UpsertUserBySub :one
INSERT INTO users(name, sub, email, email_verified)
VALUES (?, ?, ?, ?)
ON CONFLICT DO UPDATE
SET
	sub = excluded.sub,
	email = excluded.email,
	name = excluded.name,
	email_verified = excluded.email_verified,
	updated_at = CURRENT_TIMESTAMP
RETURNING id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
`

type UpsertUserBySubParams struct {
	Name          string
	Sub           string
	Email         string
	EmailVerified int64
}

// UpsertUserBySub
//
//	INSERT INTO users(name, sub, email, email_verified)
//	VALUES (?, ?, ?, ?)
//	ON CONFLICT DO UPDATE
//	SET
//		sub = excluded.sub,
//		email = excluded.email,
//		name = excluded.name,
//		email_verified = excluded.email_verified,
//		updated_at = CURRENT_TIMESTAMP
//	RETURNING id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
func (q *Queries) UpsertUserBySub(ctx context.Context, db DBTX, arg UpsertUserBySubParams) (User, error) {
	row := db.QueryRowContext(ctx, upsertUserBySub,
		arg.Name,
		arg.Sub,
		arg.Email,
		arg.EmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sub,
		&i.Email,
		&i.EmailVerified,
		&i.IsAdmin,
		&i.IsPublicServant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
