// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	//AssignRoleToUser
	//
	//  INSERT INTO user_roles (user_id, role)
	//  VALUES(?, ?) ON CONFLICT DO NOTHING
	AssignRoleToUser(ctx context.Context, db DBTX, arg AssignRoleToUserParams) error
	//CreateTramite
	//
	//  INSERT INTO tramites (name, description, procedure_description, type) -- status has its default value set in the database
	//  VALUES (?, ?, ?, ?)
	//  RETURNING id, name, description, procedure_description, type, status, created_at, updated_at
	CreateTramite(ctx context.Context, db DBTX, arg CreateTramiteParams) (Tramite, error)
	//DeleteTramite
	//
	//  DELETE FROM tramites
	//  WHERE id = ?
	DeleteTramite(ctx context.Context, db DBTX, id int64) (int64, error)
	//GetTramite
	//
	//  SELECT id, name, description, procedure_description, type, status, created_at, updated_at
	//  FROM tramites
	//  WHERE id = ?
	//  LIMIT 1
	GetTramite(ctx context.Context, db DBTX, id int64) (Tramite, error)
	//GetUserByEmail
	//
	//  SELECT id, name, sub, email, email_verified, created_at
	//  FROM users
	//  WHERE email = ?
	GetUserByEmail(ctx context.Context, db DBTX, email string) (User, error)
	//GetUserRoles
	//
	//  SELECT role
	//  FROM user_roles
	//  WHERE user_id = ?
	GetUserRoles(ctx context.Context, db DBTX, userID int64) ([]string, error)
	//IsRoleInUse
	//
	//  SELECT EXISTS(
	//          SELECT 1
	//          FROM user_roles
	//          WHERE role = ?
	//      )
	IsRoleInUse(ctx context.Context, db DBTX, role string) (bool, error)
	//RemoveUserRoles
	//
	//  DELETE FROM user_roles
	//  WHERE user_id = ?
	RemoveUserRoles(ctx context.Context, db DBTX, userID int64) error
	//UpsertUser
	//
	//  INSERT INTO users (name, sub, email, email_verified)
	//  VALUES (?, ?, ?, ?) ON CONFLICT(email) DO
	//  UPDATE
	//  SET sub = excluded.sub,
	//      name = excluded.name,
	//      email_verified = excluded.email_verified
	//  RETURNING id, name, sub, email, email_verified, created_at
	UpsertUser(ctx context.Context, db DBTX, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
