// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	//AdminExists
	//
	//  SELECT EXISTS (
	//    SELECT 1
	//    FROM users
	//    WHERE is_admin = 1
	//  )
	AdminExists(ctx context.Context, db DBTX) (bool, error)
	//CreateTramite
	//
	//  INSERT INTO tramites (name, description, procedure_description, type) -- status has its default value set in the database
	//  VALUES (?, ?, ?, ?)
	//  RETURNING id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
	CreateTramite(ctx context.Context, db DBTX, arg CreateTramiteParams) (Tramite, error)
	//DeleteTramite
	//
	//  DELETE FROM tramites
	//  WHERE id = ?
	DeleteTramite(ctx context.Context, db DBTX, id int64) (int64, error)
	//GetTramite
	//
	//  SELECT id, name, description, procedure_description, type, status, created_at, updated_at, current_version_id
	//  FROM tramites
	//  WHERE id = ?
	//  LIMIT 1
	GetTramite(ctx context.Context, db DBTX, id int64) (Tramite, error)
	//GetUserByEmail
	//
	//  SELECT id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
	//  FROM users
	//  WHERE
	//    email = ?
	GetUserByEmail(ctx context.Context, db DBTX, email string) (User, error)
	//GetUserById
	//
	//  SELECT id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
	//  FROM users
	//  WHERE
	//    id = ?
	GetUserById(ctx context.Context, db DBTX, id int64) (User, error)
	//ListUsers
	//
	//  SELECT id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
	//  FROM users
	//  ORDER BY name, id
	ListUsers(ctx context.Context, db DBTX) ([]User, error)
	//SetAdmin
	//
	//  UPDATE users
	//  SET
	//    is_admin = ?,
	//    updated_at = CURRENT_TIMESTAMP
	//  WHERE id = ?
	SetAdmin(ctx context.Context, db DBTX, arg SetAdminParams) error
	//UpdateUserAccess
	//
	//  UPDATE users
	//  SET
	//    is_admin = ?,
	//    is_public_servant = ?,
	//    updated_at = CURRENT_TIMESTAMP
	//  WHERE id = ?
	//  RETURNING id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
	UpdateUserAccess(ctx context.Context, db DBTX, arg UpdateUserAccessParams) (User, error)
	//UpsertUser
	//
	//  INSERT INTO users(name, sub, email, email_verified, is_admin, is_public_servant)
	//  VALUES (?, ?, ?, ?, ?, ?)
	//  ON CONFLICT (email) DO UPDATE
	//  SET
	//    sub = excluded.sub,
	//    name = excluded.name,
	//    email_verified = excluded.email_verified,
	//    is_admin = excluded.is_admin,
	//    is_public_servant = excluded.is_public_servant,
	//    updated_at = CURRENT_TIMESTAMP
	//  RETURNING id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
	UpsertUser(ctx context.Context, db DBTX, arg UpsertUserParams) (User, error)
	//UpsertUserBySub
	//
	//  INSERT INTO users(name, sub, email, email_verified)
	//  VALUES (?, ?, ?, ?)
	//  ON CONFLICT DO UPDATE
	//  SET
	//    email = excluded.email,
	//    name = excluded.name,
	//    email_verified = excluded.email_verified,
	//    updated_at = CURRENT_TIMESTAMP
	//  RETURNING id, name, sub, email, email_verified, is_admin, is_public_servant, created_at, updated_at
	UpsertUserBySub(ctx context.Context, db DBTX, arg UpsertUserBySubParams) (User, error)
}

var _ Querier = (*Queries)(nil)
