openapi: '3.0.3'
info:
  title: Tunkunia API
  version: '1.0'
servers:
  - url: http://localhost:8080
  - url: https://api.server.test/v1
components:
  parameters:
    ApiKeyHeader:
      name: X-TUNKUNIA-KEY
      in: header
      required: true
      example: 4354
      schema:
        type: string

paths:
  /health:
    parameters:
      - $ref: '#/components/parameters/ApiKeyHeader'
    summary: Health check endpoint
    get:
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /tramites:
    parameters:
      - $ref: '#/components/parameters/ApiKeyHeader'
    summary: Tramites endpoint
    get:
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
      deprecated: false
