openapi: 3.0.3
info:
  title: Tunkunia API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: '1.0'
  description: >
    Interfaz de interacción con el subsistema de gestión de flujos de trámite
    Tunkunia.

    Esta especificación se usará para consumo de los distintos tipos de
    clientes.

    Para lograr uniformidad se siguen prácticas de la industria y estándares
    vigentes:
      - [RFC 9457](https://datatracker.ietf.org/doc/html/rfc9457)
      - [Documentación](https://docs.stripe.com/api-v2-overview) y [Referencia](https://docs.stripe.com/api/v2/core/accounts) de la API de Stripe v2
      - Guías de diseño de APIs de [Google](https://docs.cloud.google.com/apis/design) y de [Microsoft](https://github.com/microsoft/api-guidelines) (Azure y Legacy)
servers:
  - url: http://localhost:8080/api/v1
    description: Development server
  - url: https://{host}/api/v1
    variables:
      host:
        default: tunkunia.com
        description: Host o dominio de la API
tags:
  - name: health
    x-displayName: health
  - name: Catalog
    x-displayName: Catalog
paths:
  /health:
    get:
      operationId: GetHealth
      tags:
        - health
      summary: Salud Módulo
      security: []
      responses:
        '200':
          description: The service is healthy and operating normally
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
        '404':
          $ref: '#/components/responses/NotFound'
        '503':
          description: The service is unhealthy or degraded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
  /catalog/tramites:
    get:
      tags:
        - Catalog
      operationId: ListTramites
      summary: Listar Trámites
      description: >
        Obtiene una lista de trámites paginados

        - **Guests** will only see `published` items.

        - **Creators** will see their own drafts/archived items alongside
        published ones.

        - **Admins** will see everything.
      security:
        - BearerAuth: []
        - {}
      parameters:
        - name: status
          in: query
          description: Filter trámites by status
          required: false
          schema:
            $ref: '#/components/schemas/TramiteStatus'
        - name: page
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: A paginated list of trámites.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TramiteCollection'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
    post:
      tags:
        - Catalog
      operationId: createTramite
      summary: Crear Trámite
      description: >-
        Permite a usuarios con rol de administración la creación de nuevos
        trámites en el catálogo de trámites. Los mismos nacerán con estado draft
        y pueden contener un procedimiento vacío
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TramiteCreate'
      responses:
        '201':
          description: Creación de Trámite exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tramite'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '422':
          $ref: '#/components/responses/ValidationError'
  /catalog/tramites/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: ID del Trámite
        schema:
          type: integer
    get:
      tags:
        - Catalog
      operationId: getTramite
      summary: Obtener Trámite
      security:
        - BearerAuth: []
        - {}
      responses:
        '200':
          description: Detalles del Trámite
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tramite'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      deprecated: false
    patch:
      tags:
        - Catalog
      operationId: updateTramite
      summary: Modificar Trámite
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TramiteUpdate'
      responses:
        '200':
          description: Trámite actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tramite'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/ValidationError'
    delete:
      tags:
        - Catalog
      operationId: deleteTramite
      summary: Eliminar Trámite
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Trámite eliminado, nada que retornar
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      deprecated: false
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Enter your application JWT token
  schemas:
    Health:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          enum:
            - UP
            - DOWN
            - DEGRADED
        timestamp:
          type: string
          format: date-time
          example: '2026-06-06T15:30:00Z'
    CollectionBase:
      type: object
      required:
        - next_page_url
        - previous_page_url
      properties:
        next_page_url:
          type: string
          nullable: true
          example: https://api.example.com/users?page=3
        previous_page_url:
          type: string
          nullable: true
          example: https://api.example.com/users?page=1
    ProblemDetails:
      type: object
      description: >
        Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo
        de medio "application/problem+json". Todos los miembros son OPCIONALES;
        los miembros ausentes no tienen valor por defecto salvo donde se indique
        explícitamente. Pueden estar presentes miembros adicionales (de
        extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de
        valor no coincida con el tipo especificado.
      required:
        - title
        - status
        - detail
      properties:
        type:
          type: string
          format: uri-reference
          default: about:blank
          description: >
            Referencia URI (RFC 3986) que identifica el tipo de problema. Al ser
            desreferenciada (si es una URI http/https), DEBERÍA ofrecer
            documentación legible por humanos sobre el tipo de problema. Si está
            ausente, se asume el valor "about:blank", que remite al código de
            estado HTTP como único identificador del tipo de problema. En el
            caso de Tunkunia se usan rutas relativas a modo de identificador y
            eventual creación de sitio de documentación de problemas específicos
          example: /problems/invalid-citizen
        status:
          type: integer
          format: int32
          minimum: 400
          maximum: 599
          description: >
            Código de estado HTTP generado por el servidor de origen para esta
            ocurrencia del problema. Se incluye por conveniencia; DEBE coincidir
            con el código de estado de la respuesta HTTP real.
          example: 403
        title:
          type: string
          description: >
            Contiene un resumen corto y legible por humanos del tipo de
            problema. Es de carácter consultivo y se incluye únicamente para los
            usuarios que no conocen y no pueden descubrir la semántica del URI
            del campo "type".
          example: Usted no es participante de este caso de trámite.
        detail:
          type: string
          description: >
            Contiene una explicación legible para humanos, específica de esta
            ocurrencia del problema. Si está presente, debería centrarse en
            ayudar al cliente a corregir el problema, en lugar de proporcionar
            información de depuración. Los consumidores NO DEBERÍAN analizar
            (parsear) el miembro "detail" para obtener información; las
            extensiones son una forma más adecuada y menos propensa a errores de
            obtener dicha información.
          example: Su caso de trámite con código 500424 no se encuentra vigente
        instance:
          type: string
          format: uri-reference
          description: >
            Referencia URI que identifica la ocurrencia específica del problema.
            Cuando es desreferenciable, el objeto de detalles de problema PUEDE
            obtenerse desde ella. Puede ser relativa o absoluta. No suele
            incluirse en la API de Tunkunia y se conserva en el esquema para
            obedecer el RFC 9457
          example: /cuenta/12345/mensajes/abc
    ErrorDetail:
      type: object
      description: El formato se adecúa al ejemplo brindado en la sección 3 del RFC 9457
      required:
        - detail
        - pointer
      properties:
        detail:
          type: string
        pointer:
          type: string
    AuditMetadata:
      type: object
      required:
        - createdAt
        - updatedAt
      properties:
        createdAt:
          type: string
          format: date-time
          example: '2026-03-15T14:30:00Z'
          x-order: 100
        updatedAt:
          type: string
          format: date-time
          example: '2026-04-02T11:15:22Z'
          x-order: 101
    TramiteStatus:
      type: string
      enum:
        - draft
        - published
        - archived
      example: draft
    TramiteType:
      type: string
      enum:
        - Otro
        - Trámite de registro
        - Trámite de certificación
        - Trámite de constancia
        - Trámite para cumplir con obligaciones
        - Trámite para acceder a servicios
        - Trámite para obtener permisos
      x-enumNames:
        - Otro
        - Registro
        - Certification
        - Constancia
        - Obligation
        - Servicio
        - Permiso
      example: Otro
    TramiteBase:
      type: object
      required:
        - id
        - name
        - description
      properties:
        id:
          type: integer
          format: int64
          x-order: 1
        name:
          type: string
          example: Inscripción de Personería Jurídica
          x-order: 2
        description:
          type: string
          example: >-
            Trámite legal para la obtención y registro de personería jurídica de
            asociaciones civiles.
          x-order: 3
    Tramite:
      allOf:
        - $ref: '#/components/schemas/TramiteBase'
        - $ref: '#/components/schemas/AuditMetadata'
        - type: object
          required:
            - procedureDescription
            - type
            - status
            - createdAt
            - updatedAt
          properties:
            procedureDescription:
              type: string
              example: >-
                El usuario debe cargar los requisitos formales, esperar
                validación de actas y proceder a la firma digital.
            type:
              $ref: '#/components/schemas/TramiteType'
            status:
              $ref: '#/components/schemas/TramiteStatus'
    TramiteCollection:
      allOf:
        - $ref: '#/components/schemas/CollectionBase'
        - type: object
          required:
            - data
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/TramiteBase'
    TramiteCreate:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        description:
          type: string
        procedureDescription:
          type: string
        type:
          $ref: '#/components/schemas/TramiteType'
    TramiteUpdate:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        procedureDescription:
          type: string
        type:
          $ref: '#/components/schemas/TramiteType'
        status:
          $ref: '#/components/schemas/TramiteStatus'
  responses:
    BadRequest:
      description: >-
        Solicitud no aceptada o entendida. Quizá falte algún parámetro
        requerido.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    Unauthorized:
      description: No se ha provisto con una llave válida.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    Forbidden:
      description: No tiene permisos para realizar esta solicitud
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    NotFound:
      description: El recurso solicitado no existe
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    ValidationError:
      description: Los datos provistos son incorrectos
      content:
        application/problem+json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ProblemDetails'
              - type: object
                required:
                  - errors
                properties:
                  errors:
                    description: >
                      Lista de errores de validación identificados. El formato
                      se adecúa al ejemplo brindado en la sección 3 del RFC 9457
                    type: array
                    items:
                      $ref: '#/components/schemas/ErrorDetail'
    InternalError:
      description: No se pudo ejecutar la solicitud
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
