// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const listTramites = `-- name: ListTramites :many
SELECT id, name, created_at, updated_at FROM tramites ORDER BY id
`

func (q *Queries) ListTramites(ctx context.Context) ([]Tramite, error) {
	rows, err := q.db.QueryContext(ctx, listTramites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tramite
	for rows.Next() {
		var i Tramite
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
