// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/nullable"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for HealthStatus.
const (
	DEGRADED HealthStatus = "DEGRADED"
	DOWN     HealthStatus = "DOWN"
	UP       HealthStatus = "UP"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case DEGRADED:
		return true
	case DOWN:
		return true
	case UP:
		return true
	default:
		return false
	}
}

// Defines values for TramiteStatus.
const (
	Archived  TramiteStatus = "archived"
	Draft     TramiteStatus = "draft"
	Published TramiteStatus = "published"
)

// Valid indicates whether the value is a known member of the TramiteStatus enum.
func (e TramiteStatus) Valid() bool {
	switch e {
	case Archived:
		return true
	case Draft:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// CollectionBase defines model for CollectionBase.
type CollectionBase struct {
	NextPageUrl     nullable.Nullable[string] `json:"next_page_url"`
	PreviousPageUrl nullable.Nullable[string] `json:"previous_page_url"`
}

// ErrorDetail El formato se adecúa al ejemplo brindado en la sección 3 del RFC 9457
type ErrorDetail struct {
	Detail  string `json:"detail"`
	Pointer string `json:"pointer"`
}

// Health defines model for Health.
type Health struct {
	Status    HealthStatus `json:"status"`
	Timestamp time.Time    `json:"timestamp"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// ProblemDetails Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type ProblemDetails struct {
	// Detail Contiene una explicación legible para humanos, específica de esta ocurrencia del problema. Si está presente, debería centrarse en ayudar al cliente a corregir el problema, en lugar de proporcionar información de depuración. Los consumidores NO DEBERÍAN analizar (parsear) el miembro "detail" para obtener información; las extensiones son una forma más adecuada y menos propensa a errores de obtener dicha información.
	Detail string `json:"detail"`

	// Instance Referencia URI que identifica la ocurrencia específica del problema. Cuando es desreferenciable, el objeto de detalles de problema PUEDE obtenerse desde ella. Puede ser relativa o absoluta. No suele incluirse en la API de Tunkunia y se conserva en el esquema para obedecer el RFC 9457
	Instance *string `json:"instance,omitempty"`

	// Status Código de estado HTTP generado por el servidor de origen para esta ocurrencia del problema. Se incluye por conveniencia; DEBE coincidir con el código de estado de la respuesta HTTP real.
	Status int32 `json:"status"`

	// Title Contiene un resumen corto y legible por humanos del tipo de problema. Es de carácter consultivo y se incluye únicamente para los usuarios que no conocen y no pueden descubrir la semántica del URI del campo "type".
	Title string `json:"title"`

	// Type Referencia URI (RFC 3986) que identifica el tipo de problema. Al ser desreferenciada (si es una URI http/https), DEBERÍA ofrecer documentación legible por humanos sobre el tipo de problema. Si está ausente, se asume el valor "about:blank", que remite al código de estado HTTP como único identificador del tipo de problema. En el caso de Tunkunia se usan rutas relativas a modo de identificador y eventual creación de sitio de documentación de problemas específicos
	Type *string `json:"type,omitempty"`
}

// Tramite defines model for Tramite.
type Tramite struct {
	Id                   int64         `json:"id"`
	Name                 string        `json:"name"`
	Description          string        `json:"description"`
	ProcedureDescription *string       `json:"procedureDescription,omitempty"`
	Status               TramiteStatus `json:"status"`
	Type                 string        `json:"type"`
	CreatedAt            time.Time     `json:"createdAt"`
	UpdatedAt            time.Time     `json:"updatedAt"`
}

// TramiteBase defines model for TramiteBase.
type TramiteBase struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

// TramiteCollection defines model for TramiteCollection.
type TramiteCollection struct {
	Data            []TramiteBase             `json:"data"`
	NextPageUrl     nullable.Nullable[string] `json:"next_page_url"`
	PreviousPageUrl nullable.Nullable[string] `json:"previous_page_url"`
}

// TramiteCreate defines model for TramiteCreate.
type TramiteCreate struct {
	Description          *string `json:"description,omitempty"`
	Name                 string  `json:"name"`
	ProcedureDescription *string `json:"procedureDescription,omitempty"`
	Type                 *string `json:"type,omitempty"`
}

// TramiteStatus defines model for TramiteStatus.
type TramiteStatus string

// TramiteUpdate defines model for TramiteUpdate.
type TramiteUpdate struct {
	Description          *string                   `json:"description,omitempty"`
	Name                 *string                   `json:"name,omitempty"`
	ProcedureDescription nullable.Nullable[string] `json:"procedureDescription,omitempty"`
	Status               *TramiteStatus            `json:"status,omitempty"`
	Type                 *string                   `json:"type,omitempty"`
}

// BadRequest Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type BadRequest = ProblemDetails

// Forbidden Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type Forbidden = ProblemDetails

// InternalError Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type InternalError = ProblemDetails

// NotFound Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type NotFound = ProblemDetails

// Unauthorized Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type Unauthorized = ProblemDetails

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// Detail Contiene una explicación legible para humanos, específica de esta ocurrencia del problema. Si está presente, debería centrarse en ayudar al cliente a corregir el problema, en lugar de proporcionar información de depuración. Los consumidores NO DEBERÍAN analizar (parsear) el miembro "detail" para obtener información; las extensiones son una forma más adecuada y menos propensa a errores de obtener dicha información.
	Detail string `json:"detail"`

	// Errors Lista de errores de validación identificados. El formato se adecúa al ejemplo brindado en la sección 3 del RFC 9457
	Errors []ErrorDetail `json:"errors"`

	// Instance Referencia URI que identifica la ocurrencia específica del problema. Cuando es desreferenciable, el objeto de detalles de problema PUEDE obtenerse desde ella. Puede ser relativa o absoluta. No suele incluirse en la API de Tunkunia y se conserva en el esquema para obedecer el RFC 9457
	Instance *string `json:"instance,omitempty"`

	// Status Código de estado HTTP generado por el servidor de origen para esta ocurrencia del problema. Se incluye por conveniencia; DEBE coincidir con el código de estado de la respuesta HTTP real.
	Status int32 `json:"status"`

	// Title Contiene un resumen corto y legible por humanos del tipo de problema. Es de carácter consultivo y se incluye únicamente para los usuarios que no conocen y no pueden descubrir la semántica del URI del campo "type".
	Title string `json:"title"`

	// Type Referencia URI (RFC 3986) que identifica el tipo de problema. Al ser desreferenciada (si es una URI http/https), DEBERÍA ofrecer documentación legible por humanos sobre el tipo de problema. Si está ausente, se asume el valor "about:blank", que remite al código de estado HTTP como único identificador del tipo de problema. En el caso de Tunkunia se usan rutas relativas a modo de identificador y eventual creación de sitio de documentación de problemas específicos
	Type *string `json:"type,omitempty"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// ListTramitesParams defines parameters for ListTramites.
type ListTramitesParams struct {
	// Status Filter trámites by status
	Status *TramiteStatus `form:"status,omitempty" json:"status,omitempty"`
	Page   *string        `form:"page,omitempty" json:"page,omitempty"`
	Limit  *int           `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateTramiteJSONRequestBody defines body for CreateTramite for application/json ContentType.
type CreateTramiteJSONRequestBody = TramiteCreate

// UpdateTramiteJSONRequestBody defines body for UpdateTramite for application/json ContentType.
type UpdateTramiteJSONRequestBody = TramiteUpdate

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFrbbhtHk36VwmQvbC1FUqdswmCxkCXZUeCDVpI3wFrCr2Z3iWynp3vcB0a0wUfYh9AD+Cp3ueWLLap7",
	"ZjhDUpLtP78dwIBJqQ9VX1V9dWh9yLjJC6NRe5cNPmQWXWG0w/jlCROn+C6g8/SNG+1Rx4+sKJTkzEuj",
	"e4U1Q4X5v791RtPvHB9jzujTv1m8zgbZd73FFb30W9c7SbsO0TOpXDabzTqZQMetLOjUbJCdGSW59EGA",
	"NsA4Fp4JBgaQpBBSsC78d5Dv57dwzZRHYGo0/1NDwez8NkdvDViS3Uphutmskz01diiFQP0NdHlpwEvU",
	"CAXaXDrjSEwGFpmS75kFdJ6BqxQmaY+1R6uZOrLW2G8jsUMogjCAb5EHzyyoJRlfGv/UBC2+gXhHCizy",
	"YJ2pRGLCkKPgjXQeSbrXmgU/Nla+R/HNABwzKKyZSOcNcKMhaAZKsQnCZH6ryIlJ1P9h9JE2frm5mVKv",
	"rrPBm8+Tu/MhK6wp0HqZQh5JgPiprc5zSS4qEOICdPRxEsXmcv6HBilQe3ktORPGdeFIwbWxOfMRBSaQ",
	"z/9kwBQ5U14oA0MrtSCboY5+hTydswMCFZw+PYAfd/f+40JnnUx6zN1DBonAJbUIUT8tMBtkzFo2zcg4",
	"xAXSkie8qXS8rJeZ4VvkPptdrrHjc+NAME8hWxrSgTMapObGWuTeuHhBKQjJeWCUQk77nzCH9JM2xhpv",
	"/D8KNsJ/BKsi6DcsLxRJMva+cINejxWyW/60y03eCw6t+y/a8587WSfTQSk2pB3eBqz1cN5KPSL9C4sT",
	"aYL78mu2Hr5mCda2WutkWEW8kzUNt+J1f5EbRWGaFhD1favIGUnUu+Z3S+qWZyx2rNPuZ2TKj1ddwHnm",
	"Qwo4HXI67vVJ1skOX/36kv47ena6f3h02DhyIaCXOaWLvGibdLu//f1mn/6db+0NdvqDfv9/s06W4MsG",
	"mWAeN2lv9pAdS9maN61TbYlKVmz3avgWvSGeoCVKJc4od5GpYrquTNSFMwSHVsaMGLkSFXhZxBNyFNLA",
	"xZ1UeJF14dwI40AZB7nEfGjLOH11cnD86uX+86Ozn9q/ZMFRKeEoa8TkrInQjIXCWBB4TaENjqmJAWG0",
	"IOlAaiHfBQS8KdT8I2WdnM7owklAgTrmcQuFxfLoxWVCcmk0IxQeEYveeNSOXPVxEosb7UIuReTWw6Mn",
	"Ry9BjrSxlHabUvMwNTUsSV5NqUVqLkUbN3QF8pKSu5FJ7wqCtuEOjE7FCiUr0lTykuQVjuRQYSpexiFn",
	"2rhOumf+kS6KCYISheHBWtRcshiIpa1YF84kLZjf1iB1QOAQ7fwjA47aW2YdUjSzaRDMUqxzJWkhkHbW",
	"4khaaBzZiaEfRoyMRj8tjI1QW5A6en+SXSAILIJNX7vwfBn0l68i7qfz/9t/CUyXldmjggRi9jHdWVoB",
	"LkrsLrIEhRl61Ni+8CdQzFV2NhqTNxKkcQ3k81sXGS1QWTuFHHXKMQVqx4A1E211vpB8zFq3JLsuWOAs",
	"AGcuOoenOlh6jD7B538IOTKw1+/vbu+Sy0SUeYiQw0SOCOJsDd1I7TzTHFf95BSvsbTx69NjoLhYVAHE",
	"xg0naPtI0yEOAtPE36Sos/WRQ4UdgtzULCIaLFJth5PXR4dHFT6OFjlyQaVYGZPEKWBRMS8n1D2woTMq",
	"eNYFKtACKgpqroIs3U4x2D85pjvOg/4taEm2cRFEh3bCaA0qQPcu0P2l+VEgx+iWrcplYZdeRJr1trZ3",
	"dvd6OZn4LboeG/ImRwcrNysI1hpjkTaWQrY0bxl+wsDP5+cnMCJU6BtRGirCYkLeHn3Kks2TAg+EbAnR",
	"FOM53OgJahlX/hRDpqIfaSv+4SvyCCRoqbsM8bYoH/U/Sx68299pACK139nOOlnObmROeXLvxx87WS51",
	"+rbb79cgUQ4eoU0Z0iu8l9dIkJCjJkbxBqYLZjO2IraIQsW0CzSOogNy6jK5R5s4RHk5MclRKqjmf2rJ",
	"U3pIIBONBxeYlcbFYIm8rQ1HDVP6UqQcQkKHoZWp38J8fqt9FTYUZ/Q/Z3lBNES6X2TLJPDaeYxdM8Y+",
	"00suC0ZyJHPgCkV01/la+gGBeM2CImuwoQl+MFRM/5Z17ieDRxQHOz/+8P3jZV5YC+p+9M02AwgGjxxl",
	"i0iadChVrb1Yuj7u1FwN5trG4BOGk0n9cq5qWNSZocX1EtR5qSwLOrHgJCeh9SnRXjQRuMg6UTWLkWTZ",
	"OqePTs5NbpI3mFaXZO9ysBRBpYlqFnIIwTENNnjmakZzwCA3Kb7ah08BJ6h9IMEsLpKgk14mPm3j1ZDB",
	"NejauGUmK1e5ntSxAdzk0sv3qD+DyJYKzhSvnUXhWVYm66rOc8sI70/veMsNsRNbbXcJGo9i368rpnc2",
	"t/bOt3Y/q5juZDebxgpqILb6/diJGY4iWDxsxkvzsiNV8UIshYhbRmXZF1FyknrOeLfCst6iurDZfgsE",
	"xskxppAuRAsxB19LKjaEHEnPVPf+nPIJMJ6lxQ16WOhxXhUcAuEUR9J5a9ZdGApxN+a7m/3t862twdbe",
	"YHv7SzDfWvEuWttwroXJm6KsGwbU3ra+jRd3GbQGQuGIqZL9yyoxmWsKtgQoxh1aZ3Sqgd8GO/8oylKa",
	"OcMl46l85HIiFbrufervUMEWp13NFPr9braSJpuYzTqZZvmSNY911K52r5OGkL9UQt4ny/ayIaTIyova",
	"yeOeMF9MUj494JemL6sxL5iPE7NPmiu16eP+uVI8+F5HOoi+96ArrYRMZZ41c5717HJnNn9ghEP33GOP",
	"s5WxhbDsmiKpCEMl3RjJxszysZygoJMWDlWtXBGtPPt1jMWvgM2Dw7N/khFXIV6Ck65AHqz00zM6rHxs",
	"QWbR7oc0LhrGb0+rKP7l1/OVkutIU/05NcFCYy4Cv/x6Dt78FhNylJWuTsct0KcqKk2tqZtcrZUPkSkH",
	"v0s/Bj9GUPIa+ZQrBHMNFzXBuYsMHj0zE7SaKgk4qRB3j4FpQVulBeYijVFNeoLeStDoAW+Qhyiv8zZw",
	"T5u6F/pCf/fdd7BfDu6TQqdBoRtc6E3Y2Dip3Gxjo65eHTBL6Y+jc7HkG06B6anRCI9iNS6kHgHTRk9z",
	"ExxcjagFuYI47HzcTQcfkndubESxNzb2Sw9euYWMyr0i/k4fUYA3paJXMbUYewXGAtNwxUQu9VUqz5Xk",
	"qFMaSR6bvTgmm8bZbD2Qjd2/CZZj19hRr9zkerR20dlkB8wzZUYvjAgK90+Os042QeuS7ba6fVpLR7FC",
	"ZoNsp9vv7lCMMj+OrtbjaX9vXI8nRxjTMQVeRP1YZIPsGfrypnKO2Wm/D273+/e8VXzei0p5w5oJ/PkY",
	"U+fKEaSDJPM0WqoUV49Ax/JITUnz3f7uXbfV4vfqx6tZJ9vr73x9PYKuNImtwMgygaJFDtngzWUncyHP",
	"mZ1mg+yMqSDgxfwPEVSsrNjIEQeXVrykvbVpfaIn1zDu8nx2MeVT1evOwtsLNpKaCar/KT6eUcy4jQ34",
	"XSoFRitqdhGuat6/gphPy3A6SJFQb6C1KUjM7xpiKnC9Kk+kncCU0SMnqSCqDgWqfMoj9ymYWgfiBO3U",
	"j6UepRBrO+9z6fx5BQI5v2U5erQuVhBtLJ5KRVy60H44hbpglLTiXUA7reqXwaKa/DSnWMoVVJOsO7Vg",
	"I2yduZJK1u9TMpe+tbFu2rfXTEhml//COF6t3NaEwn7pXkSf5HuUVmrwuymGtx6O4dYTb4zj/sOb2i/r",
	"S/HWTsNvLmedD7NWDMZ3UAt1BmyEYUmV2WV8RXJrQu4EbRoWLAZB3GiwRsVqnxycmoJqgsHanbsOODGu",
	"4aRYTgr8/FaZUWui49KAO5cuNw4042jntzqN58qBHMUgtYtp6pRsjxaCLjtImUvU3sCE8flHsxJeqZSt",
	"2vFURqLzT4yY/uW+lKrmWbtapeJttuLIW3/15evc96Bplrrbwxtq1Fny3k9wxMZf13ypw++mxHX/psUf",
	"vtCO7e2Hdyz/PcJDQdKKEAJnESBr42Ndnup9kGKWQkZh6gPaDncYf950uJbhd1fDbWEZIkhKZh3QTLBy",
	"bueN1cx+Tew/ry75HNCPkoYP4N65s8y7E9b+14inxgOxWmjwN8B4mf1flQ9xD6B8b61xfNhWsywwqDhf",
	"ZPQ4K2lz3Zq6oJXRC+b5eNW4qa3+KjxddvCfxNNfxa9qAmDch/igK0xF0/Fl5m/O1Z/bx/zryf2FEfGF",
	"4SGCj2fayfoIOMQJKlPEkUFa1eqDB72eMpypsXF+8EP/h36PFbI32YqjvHa7/IHWzKrfd7IJs/HpODrZ",
	"uK7BqgcsXz6mdLnJV8YpPxuqQ0EYqsKqB0vqrWez2eXs/wMAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
