// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/nullable"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for HealthStatus.
const (
	DEGRADED HealthStatus = "DEGRADED"
	DOWN     HealthStatus = "DOWN"
	UP       HealthStatus = "UP"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case DEGRADED:
		return true
	case DOWN:
		return true
	case UP:
		return true
	default:
		return false
	}
}

// Defines values for TramiteStatus.
const (
	Archived  TramiteStatus = "archived"
	Draft     TramiteStatus = "draft"
	Published TramiteStatus = "published"
)

// Valid indicates whether the value is a known member of the TramiteStatus enum.
func (e TramiteStatus) Valid() bool {
	switch e {
	case Archived:
		return true
	case Draft:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// Defines values for TramiteType.
const (
	Certification TramiteType = "Trámite de certificación"
	Constancia    TramiteType = "Trámite de constancia"
	Obligation    TramiteType = "Trámite para cumplir con obligaciones"
	Otro          TramiteType = "Otro"
	Permiso       TramiteType = "Trámite para obtener permisos"
	Registro      TramiteType = "Trámite de registro"
	Servicio      TramiteType = "Trámite para acceder a servicios"
)

// Valid indicates whether the value is a known member of the TramiteType enum.
func (e TramiteType) Valid() bool {
	switch e {
	case Certification:
		return true
	case Constancia:
		return true
	case Obligation:
		return true
	case Otro:
		return true
	case Permiso:
		return true
	case Registro:
		return true
	case Servicio:
		return true
	default:
		return false
	}
}

// CollectionBase defines model for CollectionBase.
type CollectionBase struct {
	NextPageUrl     nullable.Nullable[string] `json:"next_page_url"`
	PreviousPageUrl nullable.Nullable[string] `json:"previous_page_url"`
}

// ErrorDetail El formato se adecúa al ejemplo brindado en la sección 3 del RFC 9457
type ErrorDetail struct {
	Detail  string `json:"detail"`
	Pointer string `json:"pointer"`
}

// Health defines model for Health.
type Health struct {
	Status    HealthStatus `json:"status"`
	Timestamp time.Time    `json:"timestamp"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// ProblemDetails Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type ProblemDetails struct {
	// Detail Contiene una explicación legible para humanos, específica de esta ocurrencia del problema. Si está presente, debería centrarse en ayudar al cliente a corregir el problema, en lugar de proporcionar información de depuración. Los consumidores NO DEBERÍAN analizar (parsear) el miembro "detail" para obtener información; las extensiones son una forma más adecuada y menos propensa a errores de obtener dicha información.
	Detail string `json:"detail"`

	// Instance Referencia URI que identifica la ocurrencia específica del problema. Cuando es desreferenciable, el objeto de detalles de problema PUEDE obtenerse desde ella. Puede ser relativa o absoluta. No suele incluirse en la API de Tunkunia y se conserva en el esquema para obedecer el RFC 9457
	Instance *string `json:"instance,omitempty"`

	// Status Código de estado HTTP generado por el servidor de origen para esta ocurrencia del problema. Se incluye por conveniencia; DEBE coincidir con el código de estado de la respuesta HTTP real.
	Status int32 `json:"status"`

	// Title Contiene un resumen corto y legible por humanos del tipo de problema. Es de carácter consultivo y se incluye únicamente para los usuarios que no conocen y no pueden descubrir la semántica del URI del campo "type".
	Title string `json:"title"`

	// Type Referencia URI (RFC 3986) que identifica el tipo de problema. Al ser desreferenciada (si es una URI http/https), DEBERÍA ofrecer documentación legible por humanos sobre el tipo de problema. Si está ausente, se asume el valor "about:blank", que remite al código de estado HTTP como único identificador del tipo de problema. En el caso de Tunkunia se usan rutas relativas a modo de identificador y eventual creación de sitio de documentación de problemas específicos
	Type *string `json:"type,omitempty"`
}

// Tramite defines model for Tramite.
type Tramite struct {
	Id                   int64         `json:"id"`
	Name                 string        `json:"name"`
	Description          string        `json:"description"`
	ProcedureDescription *string       `json:"procedureDescription,omitempty"`
	Status               TramiteStatus `json:"status"`
	Type                 TramiteType   `json:"type"`
	CreatedAt            time.Time     `json:"createdAt"`
	UpdatedAt            time.Time     `json:"updatedAt"`
}

// TramiteBase defines model for TramiteBase.
type TramiteBase struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

// TramiteCollection defines model for TramiteCollection.
type TramiteCollection struct {
	Data            []TramiteBase             `json:"data"`
	NextPageUrl     nullable.Nullable[string] `json:"next_page_url"`
	PreviousPageUrl nullable.Nullable[string] `json:"previous_page_url"`
}

// TramiteCreate defines model for TramiteCreate.
type TramiteCreate struct {
	Description          *string      `json:"description,omitempty"`
	Name                 string       `json:"name"`
	ProcedureDescription *string      `json:"procedureDescription,omitempty"`
	Type                 *TramiteType `json:"type,omitempty"`
}

// TramiteStatus defines model for TramiteStatus.
type TramiteStatus string

// TramiteType defines model for TramiteType.
type TramiteType string

// TramiteUpdate defines model for TramiteUpdate.
type TramiteUpdate struct {
	Description          *string                   `json:"description,omitempty"`
	Name                 *string                   `json:"name,omitempty"`
	ProcedureDescription nullable.Nullable[string] `json:"procedureDescription,omitempty"`
	Status               *TramiteStatus            `json:"status,omitempty"`
	Type                 *TramiteType              `json:"type,omitempty"`
}

// BadRequest Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type BadRequest = ProblemDetails

// Forbidden Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type Forbidden = ProblemDetails

// InternalError Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type InternalError = ProblemDetails

// NotFound Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type NotFound = ProblemDetails

// Unauthorized Objeto de Detalles de Problema según RFC 9457. Se serializa con el tipo de medio "application/problem+json". Todos los miembros son OPCIONALES; los miembros ausentes no tienen valor por defecto salvo donde se indique explícitamente. Pueden estar presentes miembros adicionales (de extensión); los consumidores DEBEN ignorar los miembros cuyo tipo de valor no coincida con el tipo especificado.
type Unauthorized = ProblemDetails

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// Detail Contiene una explicación legible para humanos, específica de esta ocurrencia del problema. Si está presente, debería centrarse en ayudar al cliente a corregir el problema, en lugar de proporcionar información de depuración. Los consumidores NO DEBERÍAN analizar (parsear) el miembro "detail" para obtener información; las extensiones son una forma más adecuada y menos propensa a errores de obtener dicha información.
	Detail string `json:"detail"`

	// Errors Lista de errores de validación identificados. El formato se adecúa al ejemplo brindado en la sección 3 del RFC 9457
	Errors []ErrorDetail `json:"errors"`

	// Instance Referencia URI que identifica la ocurrencia específica del problema. Cuando es desreferenciable, el objeto de detalles de problema PUEDE obtenerse desde ella. Puede ser relativa o absoluta. No suele incluirse en la API de Tunkunia y se conserva en el esquema para obedecer el RFC 9457
	Instance *string `json:"instance,omitempty"`

	// Status Código de estado HTTP generado por el servidor de origen para esta ocurrencia del problema. Se incluye por conveniencia; DEBE coincidir con el código de estado de la respuesta HTTP real.
	Status int32 `json:"status"`

	// Title Contiene un resumen corto y legible por humanos del tipo de problema. Es de carácter consultivo y se incluye únicamente para los usuarios que no conocen y no pueden descubrir la semántica del URI del campo "type".
	Title string `json:"title"`

	// Type Referencia URI (RFC 3986) que identifica el tipo de problema. Al ser desreferenciada (si es una URI http/https), DEBERÍA ofrecer documentación legible por humanos sobre el tipo de problema. Si está ausente, se asume el valor "about:blank", que remite al código de estado HTTP como único identificador del tipo de problema. En el caso de Tunkunia se usan rutas relativas a modo de identificador y eventual creación de sitio de documentación de problemas específicos
	Type *string `json:"type,omitempty"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// ListTramitesParams defines parameters for ListTramites.
type ListTramitesParams struct {
	// Status Filter trámites by status
	Status *TramiteStatus `form:"status,omitempty" json:"status,omitempty"`
	Page   *string        `form:"page,omitempty" json:"page,omitempty"`
	Limit  *int           `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateTramiteJSONRequestBody defines body for CreateTramite for application/json ContentType.
type CreateTramiteJSONRequestBody = TramiteCreate

// UpdateTramiteJSONRequestBody defines body for UpdateTramite for application/json ContentType.
type UpdateTramiteJSONRequestBody = TramiteUpdate

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFrZbhtHl36Vg85c2Jo2SS3OJAwGA0WSEwWOpJHkCTCR8atYdUSWU13VqYURY/AR5iH0AL7KXW75YoNT",
	"1d3sJqnFQX77BwxYFGs5y3e+s5TeZ9wUpdGovcuG7zOLrjTaYfzwLRPn+GtA5+kTN9qjjj+yslSSMy+N",
	"7pfWjBQW//7OGU3fOT7BgtFP/2bxJhtmX/SXV/TTt65/lnYdomdSuWw+n+eZQMetLOnUbJhdGCW59EGA",
	"NsA4lp4JBgaQpBBSsB78d5C/L+7ghimPwNR48aeGktnFXYHeGrAku5XC9LJ5nr0ydiSFQP0ZdDkx4CVq",
	"hBJtIZ1xJCYDi0zJ35kFdJ6BqxUmaY+1R6uZOrLW2M8jsUMogzCA75AHzyyoFRlPjH9lghafQbwjBRZ5",
	"sM7UIjFhCCh4K51Hku6NZsFPjJW/o/hsBpwwKK2ZSucNcKMhaAZKsSnCdHGnCMQk6v8w+pE2/nV3M6VO",
	"b7Lhzx8nd/4+K60p0XqZQh5JgPhTV53XkiAqEOICdPTjNIrN5eIPDVKg9vJGciaM68GRghtjC+ajFZhA",
	"vviTAVMEpqJUBkZWakE+Qx1xhTydswsCFZy/OoCv917+x5XO8kx6LNxjDomGS2qRRf2sxGyYMWvZLCPn",
	"EBdIS0j4udbxbbPMjN4h99n87QY/vjYOBPMUspUjHTijQWpurEXujYsXVIKQnAdGKeS0/1vmkH7TtbHG",
	"W/+Pko3xH8GqaPRbVpSKJJl4X7phv89K2at+2+Om6AeH1v0X7fnP3SzPdFCKjWiHtwEbPZy3Uo9J/9Li",
	"VJrg/vo1249fs2LWrlqbZFi3eJ61HbeGur8JRlGYtgdEc9+65Ywk6t3w3Yq61RnLHZu0+x6Z8pN1CDjP",
	"fEgBp0NBx705y/Ls8PSnE/rv6Lvz/cOjw9aRSwG9LChdFGXXpTuDnS9fDOjf5fbL4e5gOBj8b5ZnyXzZ",
	"MBPM4wvamz3mx0q29k2bVFuhkjXfnY7eoTfEE7REqcQZ1S5yVUzXtYt6cIHg0MqYESNXogIvy3hCgUIa",
	"uLqXCq+yHlwaYRwo46CQWIxsFaenZwfHpyf7r48uvul+yYKjUsJR1ojJWROhGQulsSDwhkIbHFNTA8Jo",
	"QdKB1EL+GhDwtlSLD5R1CjqjB2cBBeqYxy2UFqujl5cJyaXRjKzwjFj01qN2BNXnSSxutAuFFJFbD4++",
	"PToBOdbGUtptS83DzDRmSfJqSi1Scym6dkNXIq8ouReZ9L4g6DruwOhUrFCyIk0lr0he4ViOFKbiZRIK",
	"po3L0z2LD3RRTBCUKAwP1qLmksVArHzFenAhacHirjFSDgJHaBcfGHDU3jLrkKKZzYJglmKdK0kLgbSz",
	"FsfSQuvIPIZ+GDNyGv22NDaa2oLUEf1JdoEgsAw2fezB61Wjn5xGu58v/m//BJiuKrNnJQnE7HO6s/IC",
	"XFW2u8qSKczIo8buhd+AYq72s9GY0EgmjWugWNy5yGiBytoZFKhTjilROwasnWjr84XkE9a5Jfl1yQIX",
	"AThzERye6mDpMWKCL/4Qcmzg5WCwt7NHkIlW5iGaHKZyTCbONtCN1M4zzXEdJ+d4g5WP35wfA8XFsgog",
	"Nm6BoIuRNiAOAtPE36Sos82RI4U5mdw0LCJaLFJvh7M3R4dHtX0cLXIEQaVYFZPEKWBRMS+n1D2wkTMq",
	"eNYDKtACKgpqroKsYKcY7J8d0x2XQf8StCTfuGhEh3bKaA0qQPdroPsr96NAjhGWncpl6Zd+tDTrb+/s",
	"7r3sF+Tid+j6bMTbHB2sfFGbYKMzlmljJWQr91bhJwx8f3l5BmOyCn0iSkNFtpgS2iOmLPk8KfBIyFYm",
	"mmE8hxs9RS3jym9iyNT0I23NP3xNHoFkWuouQ7wtykf9zwqC9wa7LYNI7Xd3sjwr2K0sKE++/PrrPCuk",
	"Tp/2BoPGSJSDx2hThvQKH+Q1EiQUqIlRvIHZktmMrYktWqFm2qU1jiIAOXWZ3KNNHKK8nJoElNpUiz+1",
	"5Ck9JCMTjQcXmJXGxWCJvK0NRw0z+lCmHEJCh5GVqd/CYnGnfR02FGf0P2dFSTREul9lqyTwxnmMXTPG",
	"PtNLLktGciR34BpF9DZhLf2CjHjDgiJvsJEJfjhSTP+S5Q+TwTOKg92vv/ry+SovbDTqfsRmlwEEg2eO",
	"skUkTTqUqtZ+LF2f5w1Xg7mxMfiE4eRSv5qrWh51ZmRxswRNXqrKgjwWnAQSWp8S7VXbAldZHlWzGEmW",
	"bQJ9BDk3hUloMJ0uyd4HsBRBlYsaFnIIwTENNnjmGkZzwKAwKb66h88Ap6h9IMEsLpOgk14mPu3aqyWD",
	"a9G1catMVq1yfaljA/iCSy9/R/0RRLZScKZ4zZeFZ1WZbKo6Ly0jez+94602xE5svd0l03gU+35TMb37",
	"Yvvl5fbeRxXTeXb7wlhBDcT2YBA7McNRBIuH7XhpX3akal6IpRBxy7gq+6KVnKSeM96tsKq3qC5st98C",
	"gXECxgzShWgh5uAbScWGkGPpmeo9nFOeYMaLtLhFD0/YdElL53kWSnG/sfdeDHYut7eH2y+HOzt/xdjb",
	"a7CitS1ULX3dFmXTFKCB2eb+Xdznycu65FI4Zqqi/ao8TH6aARWwztsU9Gid0an4fRfs4oOoamjmDJeM",
	"p7qRy6lU6HoPqb9LlVocc7Vz55d72Vp+bNtsnmeaFdhV4lhH7RpcnbWE/KEW8iFZdlYdIUVWXdTNGg/E",
	"93KE8vRIXxm7rAe7YD6Oyp40UOryxsMDpXjwg0A6iNh7FEprwVm7Z8OAZzOt3JvGnxynq1MdkuABT12s",
	"TTKEZTcUY2UYKekmSN5nlk/kFAWdtIRavXJN6LZArZNPvTVZvgwzgU04rfyak4lv6sZ19UuTehrJ2l/E",
	"aOWhKFVVx5qRkuMqCNcWMl6TbCyquTTra+q2rR76d5WvlFkPI9L2hBUEkEbl86WaB7Vq0eU5lbVLbU6j",
	"zNU3F5VkWZ6dJRGyFiTfRAr8BJB8dFj5qTLQfA3FdDnyYKWfXdCO6tkLmUW7H9LgbhQ/vapp9YefLteK",
	"3yNNncDMBAutCRX88NMlePNLLI2iQHR1Om7peKpn0/sB9fXrXcshMuXgN+kn4CcISt4gn3GFYG7gqgGc",
	"u8rg2XdmilZTTQdntS/cc2Ba0FZpgbmYV6g7OENvJWj0gLfIQ5TXeRu4p029K32lv/jiC9ivnlCSQudB",
	"oRte6RewtXVWR/fWVtNHOGAWY2g4F4vv0QyYnhmN8Cz2RULqMTBt9KwwwcH1mJrBa4hj5+e9dPAhkcLW",
	"VhR7a2u/Io61Wwg+3CtKqOlHFOBNpeh1zPXGXoOxwDRcM1FIfZ0aJSU56pTXE5azH4/Jp3FK3ozG4xzG",
	"BMuxZ+y4X21yfVq77DGzA+aZMuMfjQgK98+OszybonXJd9u9Aa2lo1gps2G22xv0dokamZ9EqPV52t+f",
	"NIPiMcb6iEIyWv1YZMPsO/TVTdVEOe++1O4MBg+8Gn3c21Z1w4a3kMsJVnSHIB0kmWfRU5W4egw6Fqpq",
	"RprvDfbuu60Rv988I87z7OVg99PrEXStSWzKxpYJFB1yyIY/v80zF4qC2Vk2zC6YCgJ+XPwhgookzsaR",
	"rSsvvqW9jWt94iDXcu7qpHw5b1X1O9sS7SUbS80EdWIUH99RzLitLfhNKgVGqxk4RLhu0u01xAKnCqeD",
	"FAnNBlqbgsT8piFmYNev03PaCUwZPXaSKtT6UKAsWB25T8HUORCnaGd+IvU4hVgXvK+l85e1EQj8lhXo",
	"0bpY0nVt8Uoq4tKl9qMZNBW8pBW/BrSzuqAcLsv7p4FiJYtQkbjp1JKNsXPmWge7eZ+ShfSdjc34ZGfD",
	"rGr+9p8Yx+ul9IZQ2K/gRfRJ2KO00hi/l2J4+/EY7jy2xzgePL6p+zcOK/HWTcM/v53n7+edGIwv0haa",
	"DNgKw4oqY7VTGrch5GI9FN8UmpEclXzWqNh+EcCp3qpnSaw7Q9EBp8a1QIrVzMYv7pQZd2ZrLj01FNIV",
	"xoFmHO3iTqdBaTUapRikxj3N/5Lv0ULQVS8vC4naG5gyvvhg1sIr9Rb1YCRV7+j8t0bM/nYspTZm3m0S",
	"qKybrwF5++++fBN8D9puaapvvJXeOJbQ+wQgtv7O6a8Cfi8lroc3Lf8EiXbs7Dy+Y/UvQx4Lkk6EkHGW",
	"AbIxPjblqf57KeYpZBSmDqELuMP4+zbgOo7fWw+3pWeIICmZ5aCZYNUE1Rurmf2Utv+4uuRjjH6UNHzE",
	"7vm9Zd69Zh18inhqPdWrpQb/AjZeZf/Tqrd+xMoP1hrHh101qwKDivNlRo/Dqy7XbagLOhm9ZJ5P1p2b",
	"Gu5PwtNVb/8knv4kuGoIgHEf4tO6MDVNxzeyf3Gu/tg+5p9P7j8aEadAjxF8PNNON0fAIU5RmTKODNKq",
	"Th887PeV4UxNjPPDrwZfDfqslP3pdpytdtvl97RmXn+fZ1Nm4yN+BNmkqcHqp0RfPWv1uCnWxinfG6pD",
	"QRiqwuqnY+qt5/P52/n/BwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
