// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Composable, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateTramiteData, CreateTramiteError, CreateTramiteResponse, DeleteTramiteData, DeleteTramiteError, DeleteTramiteResponse, GetCatalogHealthData, GetCatalogHealthError, GetCatalogHealthResponse, GetHealthData, GetHealthError, GetHealthResponse, GetTramiteData, GetTramiteError, GetTramiteResponse, ListTramitesData, ListTramitesError, ListTramitesResponse, UpdateTramiteData, UpdateTramiteError, UpdateTramiteResponse } from './types.gen';

export type Options<TComposable extends Composable = '$fetch', TData extends TDataShape = TDataShape, ResT = unknown, DefaultT = undefined> = Options2<TComposable, TData, ResT, DefaultT> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Salud Módulo
 */
export const getHealth = <TComposable extends Composable = '$fetch', DefaultT extends GetHealthResponse = GetHealthResponse>(options: Options<TComposable, GetHealthData, GetHealthResponse, DefaultT>): RequestResult<TComposable, GetHealthResponse | DefaultT, DefaultT> => (options.client ?? client).get<TComposable, GetHealthResponse | DefaultT, GetHealthError, DefaultT>({ url: '/health', ...options });

/**
 * Salud Módulo
 */
export const getCatalogHealth = <TComposable extends Composable = '$fetch', DefaultT extends GetCatalogHealthResponse = GetCatalogHealthResponse>(options: Options<TComposable, GetCatalogHealthData, GetCatalogHealthResponse, DefaultT>): RequestResult<TComposable, GetCatalogHealthResponse | DefaultT, DefaultT> => (options.client ?? client).get<TComposable, GetCatalogHealthResponse | DefaultT, GetCatalogHealthError, DefaultT>({ url: '/catalog/health', ...options });

/**
 * Listar Trámites
 *
 * Obtiene una lista de trámites paginados
 * - **Guests** will only see `published` items.
 * - **Creators** will see their own drafts/archived items alongside published ones.
 * - **Admins** will see everything.
 *
 */
export const listTramites = <TComposable extends Composable = '$fetch', DefaultT extends ListTramitesResponse = ListTramitesResponse>(options: Options<TComposable, ListTramitesData, ListTramitesResponse, DefaultT>): RequestResult<TComposable, ListTramitesResponse | DefaultT, DefaultT> => (options.client ?? client).get<TComposable, ListTramitesResponse | DefaultT, ListTramitesError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/catalog/tramites',
    ...options
});

/**
 * Crear Trámite
 *
 * Permite a usuarios con rol de administración la creación de nuevos trámites en el catálogo de trámites. Los mismos nacerán con estado draft y pueden contener un procedimiento vacío
 */
export const createTramite = <TComposable extends Composable = '$fetch', DefaultT extends CreateTramiteResponse = CreateTramiteResponse>(options: Options<TComposable, CreateTramiteData, CreateTramiteResponse, DefaultT>): RequestResult<TComposable, CreateTramiteResponse | DefaultT, DefaultT> => (options.client ?? client).post<TComposable, CreateTramiteResponse | DefaultT, CreateTramiteError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/catalog/tramites',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Eliminar Trámite
 */
export const deleteTramite = <TComposable extends Composable = '$fetch', DefaultT extends DeleteTramiteResponse = DeleteTramiteResponse>(options: Options<TComposable, DeleteTramiteData, DeleteTramiteResponse, DefaultT>): RequestResult<TComposable, DeleteTramiteResponse | DefaultT, DefaultT> => (options.client ?? client).delete<TComposable, DeleteTramiteResponse | DefaultT, DeleteTramiteError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/catalog/tramites/{id}',
    ...options
});

/**
 * Obtener Trámite
 */
export const getTramite = <TComposable extends Composable = '$fetch', DefaultT extends GetTramiteResponse = GetTramiteResponse>(options: Options<TComposable, GetTramiteData, GetTramiteResponse, DefaultT>): RequestResult<TComposable, GetTramiteResponse | DefaultT, DefaultT> => (options.client ?? client).get<TComposable, GetTramiteResponse | DefaultT, GetTramiteError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/catalog/tramites/{id}',
    ...options
});

/**
 * Modificar Trámite
 */
export const updateTramite = <TComposable extends Composable = '$fetch', DefaultT extends UpdateTramiteResponse = UpdateTramiteResponse>(options: Options<TComposable, UpdateTramiteData, UpdateTramiteResponse, DefaultT>): RequestResult<TComposable, UpdateTramiteResponse | DefaultT, DefaultT> => (options.client ?? client).patch<TComposable, UpdateTramiteResponse | DefaultT, UpdateTramiteError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/catalog/tramites/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
