openapi: "3.0.3"
info:
  title: Tunkunia API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: "1.0"
  description: |
    Interfaz de interacción con el subsistema de gestión de flujos de trámite Tunkunia.
    Esta especificación se usará para consumo de los distintos tipos de clientes.
    Para lograr uniformidad se siguen prácticas de la industria y estándares vigentes:
      - [RFC 9457](https://datatracker.ietf.org/doc/html/rfc9457)
      - [Documentación](https://docs.stripe.com/api-v2-overview) y [Referencia](https://docs.stripe.com/api/v2/core/accounts) de la API de Stripe v2
      - Guías de diseño de APIs de [Google](https://docs.cloud.google.com/apis/design) y de [Microsoft](https://github.com/microsoft/api-guidelines) (Azure y Legacy)
servers:
  - url: http://localhost:8080/api/v1
    description: Development server
  - url: https://{host}/api/v1
    variables:
      host:
        default: tunkunia.com
        description: Host o dominio de la API
paths:
  /health:
    $ref: "shared.openapi.yaml#/paths/~1module~1health"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Enter your application JWT token
